Repository Azure/aks-engine, pull requests merged in 2018-12, with the labels that each got.

#78 Fix issues in ip-masq yaml render
  parts/k8s/containeraddons/ip-masq-agent.yaml
Labels: approved, lgtm, size/XS

#88 remove pb6 series vms from the list of accelerated networking support…
  pkg/helpers/helpers.go
Labels: approved, lgtm, size/XS

#89 cosmosdb etcd
  docs/clusterdefinition.md
  examples/cosmos-etcd/kubernetes-3-masters-cosmos.json
  examples/cosmos-etcd/readme.md
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastergenerateproxycertscript.sh
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
Labels: approved, size/L

#102 Gangams/monitoring doc changes
  docs/images/azure_monitor_aks_engine.png
  docs/kubernetes/monitoring.md
Labels: lgtm, size/S

#101 [BUG] orchestratorVersion should not get changed for ACS scale apiVersion 2017-07-01
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
Labels: approved, lgtm, size/M

#103 update to 2018.12.03 VHDs
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#106 install explicit moby version
  parts/k8s/kubernetesinstalls.sh
Labels: approved, size/XS

#108 kubectl top nodes for metrics-server validation
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#111 Add AKSDockerEngine default for sovereign clouds
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/S

#123 Add a FAQ and link to it from the README
  README.md
  docs/faq.md
Labels: approved, area/docs, lgtm, size/M

#125 improve documentation for testing custom hyperkube images on aks-engine
  docs/kubernetes/k8s-developers.md
Labels: approved, size/M

#131 Bump azure CNI version to 1.0.15
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#128 Add HSM support for kms encryption
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-keyvault-encryption.json
  parts/k8s/artifacts/kubernetesazurekms.service
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/S

#133 Update VHD version to 2018.12.12
  pkg/api/azenvtypes.go
Labels: approved, lgtm

#139 Revert "Add hsm support for kms plugin (#128)"
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-keyvault-encryption.json
  parts/k8s/artifacts/kubernetesazurekms.service
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/S

#142 Add "Scaling" constant to provisioning states
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#141 Update go-dev tools image
  .circleci/config.yml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#137 Handle errors in 'upgrade' command
  cmd/upgrade.go
Labels: approved, lgtm, size/M

#79 Add support for Kubernetes 1.13.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, size/S

#145 make cluster autoscaler scan interval configurable
  examples/addons/cluster-autoscaler/README.md
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/api/addons.go
Labels: approved, size/M

#146 Update FAQ to account for 0.27.0 release
  docs/faq.md
Labels: approved, lgtm, size/XS

#149 update Calico network policy examples docs
  examples/networkpolicy/README.md
  examples/networkpolicy/kubernetes-calico-azure.json
  examples/networkpolicy/kubernetes-calico-kubenet.json
Labels: approved, area/docs, lgtm, size/M

#109 disable heapster for kubernetes versions > 1.13
  parts/k8s/containeraddons/1.6/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.7/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.8/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/params_k8s.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#152 Quick documentation rationalization
  README.md
  README_zh-CN.md
  docs/README.md
  docs/aksengine-code-delivery.md
  docs/aksengine.md
  docs/aksengine.zh-CN.md
  docs/clusterdefinition.md
  docs/custom-vnet.md
  docs/design/proposed-template-refactor.md
  docs/extensions.md
  docs/kubernetes.md
  docs/kubernetes/aad.md
  docs/kubernetes/deploy.md
  docs/kubernetes/gpu.md
  docs/kubernetes/scale.md
  docs/serviceprincipal.md
  docs/ssh.md
  examples/README.md
  examples/customfiles/README.md
  examples/disks-managed/README.md
  examples/disks-storageaccount/README.md
  examples/k8s-upgrade/README.md
  examples/keyvault-params/README.md
  examples/keyvaultcerts/README.md
  examples/kubernetes-config/README.md
  examples/largeclusters/README.md
  examples/multiple-nodepools/README.md
  examples/networkplugin/README.md
  examples/networkpolicy/README.md
  examples/vnet/README.md
  examples/windows/README.md
  releases/Dockerfile.linux
  releases/README.Dockerfile.md
Labels: approved, size/L

#156 Add 1.13.1 to VHD image
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#154 Fix default value for kublet's non-masquerade-cidr
  pkg/api/defaults-kubelet.go
Labels: approved, size/XS

#158 Docs: Update version strings and make examples match Windows version
  docs/kubernetes/windows.md
  examples/windows/kubernetes.json
Labels: approved, lgtm, size/M

#157 Add HSM support for kms encryption
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-keyvault-encryption.json
  packer/install-dependencies.sh
  parts/k8s/artifacts/kubernetesazurekms.service
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/S

#155 Add support for Kubernetes 1.11.6
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#153 use a fixed version for flex addons
  pkg/api/addons.go
  pkg/api/defaults_test.go
Labels: approved, size/XS

#129 Add toggle for switching ip-masq-agent logic for AKS.
  parts/k8s/kubernetesagentcustomdata.yml
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/types.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/M

#166 Fix Failing Unit test
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/XS

#164 Replace gometalinter with golangci-lint
  .circleci/config.yml
  .golangci.yml
  Makefile
  pkg/armhelpers/groupsclient.go
  scripts/validate-go.sh
Labels: approved, lgtm, size/M

#167 Allow for disabling ip-masq-agent
  parts/k8s/kubernetesagentcustomdata.yml
  pkg/api/const.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/types.go
  pkg/engine/artifacts.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/M

#169 do not parse azure-cni monitor manifests if addon is disabled in the apimodel
  pkg/api/const.go
  pkg/api/types.go
  pkg/engine/artifacts.go
Labels: approved, lgtm, size/XS

#171 stop defaulting to westcentralus as a regional option for E2E
  test/e2e/config/config.go
  test/e2e/config/config_test.go
Labels: approved, lgtm, size/XS

#170 Update version of cluster-autoscaler for k8s 1.13.1
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#82 Add support for Kubernetes 1.12.4
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#162 cleanup pointer primitive usages
  pkg/api/addons.go
  pkg/api/agentPoolOnlyApi/v20180331/merge_test.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate_test.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/mocks.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/mockclients.go
  pkg/engine/artifacts.go
  pkg/engine/engine.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/helpers/helpers_test.go
  test/e2e/engine/template.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#174 Docs: Added auth-method in scale.md and Removed a typo.
  docs/kubernetes/scale.md
Labels: lgtm, size/XS

#181 add k8s 1.10.12 to vhd
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#180 use latest VHD image: k8s 1.11.6, 1.12.4, 1.13.1
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#186 2018.12.19 VHD image w/ 1.10.12
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS, v0.28.1

#193 using the correct apiVersion Private Cluster NICs
  parts/k8s/kubernetesmasterresources.t
Labels: approved, lgtm, size/XS

#194 change azure disk cachingMode to ReadOnly
  parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes.yaml
  parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml
Labels: approved, lgtm, size/S, v0.29.0

#165 enable AKS VHD images in mooncake
  pkg/api/azenvtypes.go
Labels: approved, size/XS

#183 use containerd 1.1.5, enable w/ non-vhd flows
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/M, v0.29.0
