Repository Azure/aks-engine, pull requests merged in 2018-11, with the labels that each got.

#20 updated readme to reflect acs-engine transition
  README.md
Labels: approved, lgtm, size/M

#24 Add copyright header to source code that isn't Go
  packer/cleanup-vhd.sh
  packer/feature-flagged.sh
  packer/init-variables.sh
  packer/install-dependencies.sh
  pkg/engine/testdata/rename.sh
  pkg/helpers/Get-AzureConstants.py
  scripts/azure-const.sh
  scripts/build-windows-k8s.sh
  scripts/convert-lcg-lcl.sh
  scripts/devenv.sh
  scripts/update-enus-po.sh
  scripts/update-translation.sh
  scripts/validate-dependencies.sh
  scripts/validate-generated.sh
  test/cluster-tests/kubernetes/k8s-utils.sh
  test/cluster-tests/kubernetes/test.sh
  test/cluster-tests/utils.sh
  test/common.sh
  test/deploy.sh
  test/e2e.sh
  test/e2e/cleanup.sh
  test/shunit/deploy_template.sh
  test/shunit/generate_template.sh
  test/shunit/scale_agent_pool.sh
  test/shunit/validate_deployment.sh
  test/step.sh
Labels: approved, lgtm, size/M

#22 E2E: eliminate possible nil dereference
  test/e2e/engine/template.go
Labels: approved, lgtm, size/M

#26 removing openshift artifacts
  .circleci/config.yml
  Makefile
  pkg/openshift/translations/en_US/LC_MESSAGES/acsengine.mo
  pkg/openshift/translations/en_US/LC_MESSAGES/acsengine.po
  scripts/validate-generated.sh
Labels: approved, lgtm, size/L

#28 *string needs nil guard
  pkg/operations/deletevm.go
Labels: approved, lgtm, size/XS

#27 E2E: retry node count test
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#25 accelerated networking rationalization, with tests
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#31 Templates end with .tmpl
  .gitattributes
  docs/design/proposed-template-refactor.md
  parts/agentoutputs.tmpl
  parts/agentparams.tmpl
  parts/iaasoutputs.tmpl
  parts/k8s/kubernetesagentresourcesvmas.tmpl
  parts/k8s/kubernetesagentresourcesvmss.tmpl
  parts/k8s/kubernetesagentvars.tmpl
  parts/k8s/kubernetesbase.tmpl
  parts/k8s/kubernetesmasterresources.tmpl
  parts/k8s/kubernetesmasterresourcesvmss.tmpl
  parts/k8s/kubernetesmastervars.tmpl
  parts/k8s/kubernetesparams.tmpl
  parts/k8s/kuberneteswinagentresourcesvmas.tmpl
  parts/k8s/kuberneteswinagentresourcesvmss.tmpl
  parts/masteroutputs.tmpl
  parts/masterparams.tmpl
  parts/windowsparams.tmpl
  pkg/engine/const.go
Labels: approved, lgtm, size/M

#30 remove additional sed statements for ip-masq addons
  parts/k8s/containeraddons/ip-masq-agent.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesparams.tmpl
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/M

#38 Update go-dev tools image for go 1.11.2
  .circleci/config.yml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#40 fix retrycmd_if_failure: retries should be r
  parts/k8s/kubernetesagentresourcesvmas.tmpl
  parts/k8s/kubernetesagentresourcesvmss.tmpl
  parts/k8s/kubernetesmasterresources.tmpl
  parts/k8s/kubernetesmasterresourcesvmss.tmpl
Labels: approved, lgtm, size/XS

#42 add support PB6 vm skus
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/S

#44 fix outbound connection check for master VMSS
  parts/k8s/kubernetesmasterresourcesvmss.tmpl
Labels: approved, bug, lgtm, size/XS

#48 update azure_const unit test
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/XS

#45 use mcr repos and disable smb flexvol addon
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/L

#46 docker-health monitor doesn't work
  parts/k8s/health-monitor.sh
Labels: approved, lgtm, size/XS

#47 Add docker-engine feature flag for docker-engine w/ Ubuntu distro
  docs/clusterdefinition.md
  docs/kubernetes/gpu.md
  packer/feature-flagged.sh
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/kubernetesagentresourcesvmas.tmpl
  parts/k8s/kubernetesagentresourcesvmss.tmpl
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmasterresources.tmpl
  parts/k8s/kubernetesmasterresourcesvmss.tmpl
  parts/k8s/kubernetesmastervars.tmpl
  parts/k8s/kubernetesprovisionsource.sh
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#33 E2E: rationalize node check + kube-system check, no kms
  .circleci/config.yml
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, bug, lgtm, size/M

#50 update tiller versions in the recent versions of kubernetes
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, size/S

#51 Replace docker engine feature flag by existing cloud spec
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.tmpl
  parts/k8s/kubernetesparams.tmpl
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/M

#52 [docs] Remove docker-engine feature flag docs
  docs/kubernetes/gpu.md
  pkg/engine/params_k8s_test.go
Labels: approved, area/docs, lgtm, size/S

#54 remove extraneous paragraph in CN readme
  README_zh-CN.md
Labels: approved, size/XS

#64 VSTS VHD pipeline hosted ubuntu pool
  .vsts-ci.yaml
Labels: approved, lgtm, size/XS

#62 scale: persist scale down in api model
  cmd/scale.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, bug, lgtm, size/S

#65 Fix issue caused by updating azure.json
  .circleci/config.yml
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: approved, lgtm, size/S

#58 Add support for Kubernetes 1.11.5
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#68 enable typha and add horizontal autoscaler
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
Labels: approved, size/XL

#67 Fix docker-engine install in VHD pipeline
  packer/install-dependencies.sh
Labels: approved, lgtm

#57 Add support for Kubernetes 1.12.3
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#72 Include 1.11.5 in VHD spec
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS
