Repository Azure/aks-engine, pull requests merged in 2019-06, with the labels that each got.

#1245 fix: pause cluster-autoscaler and use VMSS capacity when upgrading
  Gopkg.lock
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_aix.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
Labels: approved, lgtm, size/XL

#1419 feat: add support for Kubernetes 1.12.8 and 1.13.5 on Azure Stack
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#1418 docs: clean up azure-stack examples
  examples/azure-stack/kubernetes-azurestack-adfs.json
  examples/azure-stack/kubernetes-azurestack.json
Labels: approved, lgtm, size/M

#1426 test: quicker “defaults addons image” unit test
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#1412 chore(CIS): Remove log file permission enforcement
  test/e2e/kubernetes/scripts/CIS-files-validate.sh
Labels: approved, lgtm, size/XS

#1388 test: getTemplateFuncMap unit tests part 4
  parts/agentparams.t
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/generate_azure_constants.py
Labels: approved, size/L

#1428 chore: re-enable k8s v1.12.9
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/S

#1430 style: only call validate if validate bool is true in apiloader
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
Labels: approved, size/M

#1411 chore: use CoreDNS 1.5.0 for k8s >= 1.12.0
  packer/install-dependencies.sh
  parts/k8s/addons/coredns.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1409 refactor: simplify default addons enabled enforcement
  docs/topics/clusterdefinitions.md
  parts/k8s/containeraddons/dns-autoscaler.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-heapster-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#1090 feat: use all VMAS fault domains in a region
  cmd/scale.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/azureclient.go
  pkg/armhelpers/azurestack/compute.go
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/httpMockClientData/getAvailabilitySet.json
  pkg/armhelpers/compute.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/engine/armresources_test.go
  pkg/engine/armtype.go
  pkg/engine/armtype_test.go
  pkg/engine/availabilitysets.go
  pkg/engine/availabilitysets_test.go
  pkg/engine/masterarmresources_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  scripts/fault_domains_expr.py
Labels: approved, area/templates, lgtm, size/XL

#1396 docs: docs and log messages about upgrading components
  docs/topics/clusterdefinitions.md
  docs/topics/upgrade.md
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L

#1401 fix: use reconcile mode in addon specs
  docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml
  parts/k8s/addons/1.6/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
Labels: approved, lgtm, size/L

#1441 feat: add support for Kubernetes 1.13.7
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1447 fix: reconcile templates_generated.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#1448 chore: move azure stack example VM SKUs from Standard_D2_v2 to Standard_D2_v3
  examples/azure-stack/kubernetes-azurestack.json
Labels: size/XS

#1439 feat: add support for Kubernetes 1.14.3
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1450 chore: enable 2019.06.08 VHD
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.08.txt
Labels: approved, lgtm, size/L

#1451 chore: update etcd default to 3.2.26
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#1429 refactor: run full validation for aks-engine deploy
  cmd/deploy.go
  cmd/deploy_test.go
Labels: approved, lgtm, size/M

#1434 chore: enable only strong TLS cipher suites for kubelet by default
  pkg/api/const.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#1449 test: getTemplateFuncMap unit tests part 5
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XL

#1452 test: Switch Windows test passes to VMSS by default to match AKS
  examples/e2e-tests/kubernetes/windows/hybrid/definition.json
Labels: approved, lgtm, size/XS

#1416 chore(CIS): generate kubelet server cert in aks-engine
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#1457 chore: reconcile generated files
  pkg/engine/templates_generated.go
Labels: approved, size/L

#1460 fix: fix missing variable in CSE
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
Labels: approved, lgtm, size/XS

#1459 test: enable DNS liveness test for calico-enabled clusters
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#1454 feat: enable PSP w/ privileged ClusterRoleBinding for 1.15
  parts/k8s/addons/1.15/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#1463 chore: delete obsolete calico spec
  parts/k8s/addons/1.6/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/XL

#1469 feat: add support for Kubernetes 1.15.0-rc.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#1471 fix: fix race condition between cloud init walinuxagent hold and CSE
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1473 fix: remove walinuxagent version pin
  parts/k8s/cloud-init/artifacts/apt-preferences
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1470 test: add subnets to route table in E2E for custom vnet + kubenet
  test/e2e/azure/cli.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#1362 fix: start Docker service before the Kubelet service on Windows node
  docs/community/developer-guide.md
  examples/windows/kubernetes.json
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/scripts/simulate-dockerd-crash.cmd
Labels: approved, lgtm, size/L

#1476 revert: remove k8s 1.12.9 support
  docs/topics/azure-stack.md
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1478 chore: add note about apimodel in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, size/XS

#1481 chore: update VHD to 2019.06.12
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.12.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.12.txt
Labels: approved, lgtm, size/L

#1480 test: HPA scale down config only works if k8s >= 1.12
  test/e2e/engine/template.go
Labels: approved, size/S

#1474 fix(auth): Explicitly import the AAD library to allow cluster upgrades
  Gopkg.lock
  pkg/engine/engine.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go
Labels: approved, lgtm, size/L

#1482 docs: list pre-pulled versions for Azure Stack
  docs/topics/azure-stack.md
Labels: approved, azurestack, lgtm, size/S

#1483 chore: add k8s 1.14.1 for Azure Stack to VHD script
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#1484 fix: vhd pre-pulls expected flannel images tag
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#1486 chore: remove support for Kubernetes 1.9.x
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/agentPoolOnly/v20170831/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfile.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfileV2.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithOnlyNetworkPlugin.json
  pkg/engine/testdata/kubernetesversions/kubernetes1.9.11.json
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: approved, lgtm, size/L

#1487 chore: update go toolchain to 1.12.6
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#1424 feat: IPv6dualStack feature flag
  parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/dhcpv6.service
  parts/k8s/cloud-init/artifacts/enable-dhcpv6.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/kubernetesparams.t
  parts/masterparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/ipaddresses.go
  pkg/engine/ipaddresses_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualnetworks.go
  pkg/engine/virtualnetworks_test.go
Labels: approved, lgtm, size/XXL

#1493 chore: CoreDNS configmap is not updated during upgrades
  parts/k8s/addons/coredns.yaml
Labels: approved, lgtm, size/XS

#1497 security: new VHD images with kernel patch
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.18.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.17.txt
Labels: approved, lgtm, size/L

#1500 chore: update templates_generated.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1489 chore: Change Windows default image to Jun 2019
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
Labels: approved, lgtm, size/S

#1464 feat: Adding Windows Server version 1903 support
  docs/topics/clusterdefinitions.md
  examples/windows/kubernetes-windows-1903.json
  parts/k8s/windowsinstallopensshfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/validate-dns-windows.yaml
Labels: approved, do-not-merge/hold, lgtm, size/L, windows

#1501 ci: swap ensure-generated and test-style tasks
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/XS

#1502 feat: add support for Kubernetes 1.15.0
  examples/kubernetes-releases/kubernetes1.14.json
  examples/kubernetes-releases/kubernetes1.15.json
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#1506 docs: Link to more details on Windows images
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/XS

#1499 docs: add marketplace prerequisites for Azure Stack
  docs/topics/azure-stack.md
Labels: approved, azurestack, lgtm, size/M

#1509 fix: check for nil masterProfile when setting FD count
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/S

#1508 fix: --pod-max-pids upgrade to 1.14 scenarios
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L

#1510 fix: ensure calico is properly enabled during upgrade
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/L

#1511 chore: update addon-resizer to 1.8.5 for k8s 1.15
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: lgtm, size/S

#1513 chore: enable VHD 2019.06.20
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.20.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.20.txt
Labels: approved, lgtm, size/L

#1514 fix: Set encoding:gzip on cilium BPFFS mount unit
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1523 fix: download aks-engine in Azure Cloud Shell
  scripts/get-akse.sh
Labels: approved, lgtm, size/S

#1456 feat: enable deployment of windows nodes on Azure Stack
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, azurestack, lgtm, size/L

#1525 chore: Add support for Kubernetes 1.13.7 and 1.14.3 on Azure Stack
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#1524 test: validate expected nodes version during E2E
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, do-not-merge/hold, size/S

#1535 fix: Ensure etcd starts after disk is mounted (#1515)
  parts/k8s/cloud-init/artifacts/etcd.service
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1538 fix: wait_for_apt_locks before GPU driver install
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1537 chore: Update to MS Moby 3.0.6
  packer/install-dependencies.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/S

#1526 feat: Add vscode containerized development config
  .devcontainer.json
Labels: approved, lgtm, size/S

#1540 chore: enable VHD 2019.06.26 for 16.04-LTS
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.26.txt
Labels: approved, size/L

#1533 fix: --anonymous-auth and --client-ca-file in insecure kubelet config
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, bug, lgtm, size/L

#1544 chore: include https://fqdn:443 for AKS upgrade
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/S

#1545 docs: make build before make clean in release docs
  docs/community/release-checklist.md
Labels: approved, lgtm, size/XS

#1529 feat: Set PlatformFaultDomainCount value as 3 for Azure Stack
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, azurestack, lgtm, size/L

#1547 test: update e2e api model definition
  examples/e2e-tests/kubernetes/release/default/definition.json
Labels: approved, lgtm, size/M
