Repository Azure/aks-engine, pull requests merged in 2019-08, with the labels that each got.

#1698 chore: use ACR URI to validate outbound connectivity
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: do-not-merge/hold, lgtm

#1693 feat: enable smart cloudprovider rate limiting
  pkg/api/common/const.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm

#643 fix: Change win-cni to win-bridge binaries and config
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  scripts/build-windows-k8s.sh
Labels: approved, awaiting review, lgtm, size/M

#1679 chore: fix error message not displayed when binary not found
  test/e2e/kubernetes/node/node.go
Labels: approved, lgtm

#1727 chore: configure docker ExecStartPost config in file
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm

#1724 Fix 'dpkg --configure -a' interactive config update issue
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm

#1730 feat: add support for Kubernetes 1.15.2
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1732 feat: add support for Kubernetes 1.13.9
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1731 feat: add support for Kubernetes 1.14.5
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1636 chore: Update calico to v3.8.0
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1740 feat: add support for Kubernetes 1.13.9, 1.14.5, 1.15.2 on Azure Stack
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, azurestack, lgtm, size/S

#1745 feat: add support for Kubernetes 1.16.0-alpha.3
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#1746 chore: update kube-addon-manager to v9.0.2 and v8.9.1
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1750 chore: Update to Docker EE 18.09.7 by default
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#1757 chore: rev VHD versions to 2019.08.09
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.09.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.09.txt
Labels: approved, size/L

#1756 chore: update go-dev image to v1.23.0
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, area/ci, lgtm, size/XS

#1752 fix: re-add Promo SKUs to Azure constants
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/armvariables_test.go
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/generate_azure_constants.py
Labels: approved, lgtm, size/XL

#1767 docs: increase master node count in Azure Stack template
  examples/azure-stack/kubernetes-azurestack.json
Labels: approved, azurestack, lgtm, size/XS

#1774 chore: update Azure CNI and NetworkPolicy to v1.0.25
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/S

#1770 feat: enable AKS VHD image in Fairfax
  docs/topics/clusterdefinitions.md
  pkg/api/azenvtypes.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/S

#1719 fix: address all cloud-init file waits
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/docker-monitor.service
  parts/k8s/cloud-init/artifacts/docker-monitor.timer
  parts/k8s/cloud-init/artifacts/docker_clear_mount_propagation_flags.conf
  parts/k8s/cloud-init/artifacts/enable-dhcpv6.sh
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/artifacts/label-nodes.service
  parts/k8s/cloud-init/artifacts/label-nodes.sh
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/api/azenvtypes.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/templates_generated.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#1755 fix: label scheduled-maintenance manifests for addon-manager
  parts/k8s/addons/kubernetesmasteraddons-scheduled-maintenance-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1781 docs: supported versions for disconnected Azure Stacks using VHD 2019.07.30
  docs/topics/azure-stack.md
Labels: lgtm, size/XS

#1772 chore: rev etcd to v3.3.13
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#1775 test: improve kubectl port-forward tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#1769 chore: use numeric address to avoid DNS reverse lookup
  parts/k8s/cloud-init/artifacts/kubelet.service
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1784 docs: Add devigned as owner
  OWNERS
Labels: approved, lgtm, size/XS

#1790 style: read without -r will mangle backslashes
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  pkg/engine/templates_generated.go
  scripts/validate-shell.sh
  test/shunit/validate_deployment.sh
Labels: approved, area/ci, lgtm, size/XS

#1788 feat: Added unit test for NormalizeMasterResourcesForScaling function
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/master_resources_scale_temaplate.json
Labels: area/test, do-not-merge/hold, size/XXL

#1789 chore: update go toolchain to 1.12.8
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, area/ci, lgtm, size/XS

#1783 feat: enable configurable cloudprovider ratelimits for write
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#1791 fix: race condition which causes concurrent map writes during tests
  pkg/api/defaults-scheduler.go
Labels: approved, lgtm, size/S

#1722 chore: Change Windows default to Windows Server 2019 LTSC, July patch
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
Labels: approved, lgtm, size/S

#1785 fix: set kubelet config for containerd in templates
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1796 docs: fix the feature table
  docs/topics/features.md
Labels: lgtm, size/XS

#1807 chore: add k8s 1.13.10, 1.14.6, 1.15.3 to VHD script
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#1813 docs: Move master and agent node OS vhd size to default value i.e 30GB
  examples/azure-stack/kubernetes-azurestack.json
Labels: azurestack, lgtm, size/XS

#1762 feat: Windows VHD build pipeline
  .pipelines/vhd-builder-windows.yaml
  packer.mk
  packer/configure-windows-vhd.ps1
  packer/windows-vhd-builder.json
  packer/write-release-notes-windows.ps1
Labels: approved, lgtm, size/L

#1802 fix: Remove public access from vhd storage container
  packer/init-variables.sh
Labels: approved, lgtm, size/XS

#1803 feat: add support for Kubernetes 1.13.10
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1804 feat: add support for Kubernetes 1.14.6
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1805 feat: add support for Kubernetes 1.15.3
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1766 feat: autofill client Id and client secret for generate command
  cmd/deploy_test.go
  cmd/generate.go
  cmd/generate_test.go
Labels: lgtm, size/L

#1814 fix: kube-proxy addon not critical, doesn't reconcile
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1820 chore: rev VHD references to 2019.08.15
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.15.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.15.txt
Labels: approved, lgtm, size/L

#1818 docs: gofish updates are automated now for AKS Engine releases
  docs/community/release-checklist.md
Labels: approved, area/docs, lgtm, size/S

#1714 fix: metrics server cluster role
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1821 fix: use azcopy-preview in VHD pipeline
  .pipelines/vhd-builder.yaml
  packer.mk
Labels: approved, lgtm, size/S

#1808 feat: update cloud provider rate limit for vmas.
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, azure, azurestack, lgtm, size/L

#1827 feat: add support for Kubernetes 1.13.10, 1.14.6, 1.15.3 on Azure Stack
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#1823 fix: networkplugin conversion only if networkpolicy is empty
  cmd/generate_test.go
  examples/azure-cni/k8s-scale.sh
  examples/azure-cni/k8s-scaledown.json
  examples/azure-cni/k8s-scaledown.json.env
  examples/azure-cni/k8s-scaleup.json
  examples/azure-cni/k8s-scaleup.json.env
  examples/azure-cni/k8s-vnet-scaledown.json
  examples/azure-cni/k8s-vnet-scaledown.json.env
  examples/azure-cni/k8s-vnet-scaleup.json
  examples/azure-cni/k8s-vnet-scaleup.json.env
  examples/disks-storageaccount/kubernetes.json.env
  examples/e2e-tests/kubernetes/coreos/coreos.json
  examples/extensions/kubernetes.json
  examples/extensions/kubernetes.oms.json
  examples/extensions/kubernetes.preprovision.json
  examples/ipvs/kubernetes-msi.json
  examples/k8s-upgrade/k8s-upgrade.sh
  examples/k8s-upgrade/v1.7.7.json
  examples/k8s-upgrade/v1.7.7.json.env
  examples/k8s-upgrade/v1.7.9-hybrid.json
  examples/k8s-upgrade/v1.7.9-hybrid.json.env
  examples/k8s-upgrade/v1.7.9-win.json
  examples/k8s-upgrade/v1.7.9-win.json.env
  examples/k8s-upgrade/v1.7.9.json
  examples/k8s-upgrade/v1.7.9.json.env
  examples/k8s-upgrade/v1.8.4.json
  examples/k8s-upgrade/v1.8.4.json.env
  examples/kubernetes-config/kubernetes-no-dashboard.json.env
  examples/kubernetes-config/kubernetes-rescheduler.json.env
  examples/kubernetes-releases/kubernetes1.6.json
  examples/kubernetes-releases/kubernetes1.7.json
  examples/kubernetes-releases/kubernetes1.8.json
  examples/kubernetes-releases/kubernetes1.9.json
  examples/managed-identity/kubernetes-msi.json.env
  examples/vnet/README.md
  examples/vnet/dual-subnet-vnet-predeploy.sh
  examples/vnet/k8s-vnet-azure-cni-predeploy.sh
  examples/vnet/k8s-vnet-postdeploy.sh
  examples/vnet/k8s-vnet-predeploy.sh
  examples/vnet/kubernetesvnet-azure-cni.json.env
  examples/vnet/kubernetesvnet.json.env
  examples/vnet/kubernetesvnet1.5.json
  examples/vnet/kubernetesvnet1.5.json.env
  examples/vnet/kubernetesvnet1.6.json
  examples/vnet/kubernetesvnet1.6.json.env
  examples/windows/kubernetes-hybrid.json.env
  examples/windows/kubernetes.json.env
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
Labels: approved, lgtm, size/XXL

#1819 feat: add support for Kubernetes 1.16.0-beta.1
  parts/k8s/addons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/1.16/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  pkg/api/common/versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1826 chore: update go toolchain to 1.12.9 (#1789)
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  makedev.ps1
Labels: approved, area/ci, lgtm, size/S

#1835 fix: skip creating slb for hostedmaster
  pkg/engine/armresources.go
Labels: approved, lgtm, size/XS

#1825 test: retry all ssh-dependent E2E tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/remote/ssh.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, do-not-merge/hold, size/L

#1840 ci: Windows VHD winrm delay start
  packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/S, windows

#1831 chore: bump keyvault-flexvol to v0.0.12
  examples/addons/keyvault-flexvolume/README.md
  packer/install-dependencies.sh
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1838 chore: tolerate lowercase LB SKU vals
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/networkinterfaces_test.go
Labels: approved, size/L

#1844 test: only check for static n node count if not using low pri VMSS
  pkg/api/types.go
  pkg/api/types_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, lgtm, size/L

#1845 chore: wait for pod readiness in port forward test
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#1849 chore: rev VHD image references to 2019.08.21
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.21.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.21.txt
Labels: approved, lgtm, size/L

#1841 feat: Allow customization of coredns (#1541)
  docs/topics/coredns.md
  parts/k8s/addons/coredns.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1843 test: add retries to host OS DNS E2E tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/host-os-dns-validate.sh
Labels: approved, lgtm, size/XS

#1850 feat: update default Kubernetes version to 1.13
  pkg/api/common/const.go
Labels: approved, size/XS

#1852 test: allow 20 retries for ssh-dependent tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/remote/ssh.go
Labels: approved, size/XS

#1853 test: improve dashboard e2e tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#1855 fix: restore working calico networkPolicy vlabs conversion logic
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
Labels: approved, size/L

#1846 chore: Targeting August updates for Windows VHD
  packer/configure-windows-vhd.ps1
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS, windows

#1854 test: e2e accommodations for low-pri vmss configurations
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/XL

#1857 test: check DNS before scp’ing
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, size/L

#1874 fix: more aks guarding against agentLbID template var
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/L

#1876 docs: fix invalid link
  examples/addons/cluster-autoscaler/README.md
Labels: lgtm, size/XS

#1870 fix: set streaming-connection-idle-timeout as 4h
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: aks, lgtm, size/XS

#1822 chore: add apache2-utils as an apt dependency
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1865 fix: add deprovision step to packer script
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#1878 feat: Windows VHD update defender signatures
  packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#1879 test: retry pod get
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/M

#1875 chore: create parallel Jenkins pipeline for e2e tests
  Jenkinsfile
  test.mk
  test/e2e/build.sh
  test/e2e/cluster.sh
  test/e2e/jenkins_reown.sh
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/availabilityset.json
  test/e2e/test_cluster_configs/base.json
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/flannel/docker.json
  test/e2e/test_cluster_configs/gpu.json
  test/e2e/test_cluster_configs/kubnet.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/rbac_disabled.json
Labels: approved, lgtm, size/XL

#1880 chore: update CoreDNS to 1.6.2
  packer/install-dependencies.sh
  parts/k8s/addons/coredns.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, azure, lgtm, size/M

#1881 test: printing wrong err
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/XS

#1884 chore: disable tiller addon by default
  docs/topics/clusterdefinitions.md
  pkg/api/addons_test.go
  pkg/api/const.go
Labels: approved, lgtm, size/L

#1886 chore: update Azure CNI and Azure-NPM to v1.0.27
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/S
