Repository Azure/aks-engine, pull requests merged in 2019-12, with the labels that each got.

#2380 chore: clean up unused addons artifacts
  parts/k8s/addons/1.10/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.6/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-elb-svc.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2381 refactor: remove unnecessary enabled addon config state representation
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/engine.go
Labels: approved, size/L

#2384 feat: support using existing identity for addons (#2238)
  pkg/api/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: size/L

#2382 fix: install tools bins locally and add to PATH
  Makefile
  hack/tools/Makefile
Labels: approved, lgtm, size/M

#2371 feat: node-problem-detector addon
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  examples/addons/node-problem-detector/README.md
  examples/addons/node-problem-detector/node-problem-detector.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-disabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  packer/install-dependencies.sh
  parts/k8s/containeraddons/node-problem-detector.yaml
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#2361 style: remove dead code from Windows build script
  scripts/build-windows-k8s.sh
Labels: approved, lgtm, size/L

#2387 feat: Updating Windows VHD build def to container Nov patches
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS, windows

#2388 feat: Adding a unique id to Windows VHDs for telemtry correlation
  packer/configure-windows-vhd.ps1
  packer/write-release-notes-windows.ps1
Labels: approved, lgtm, size/XS

#2386 feat: add support for Kubernetes 1.17.0-rc.2
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2383 refactor: move addons consts to pkg/api/common
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/applicationgateway.go
  pkg/engine/applicationgateway_test.go
  pkg/engine/armoutputs.go
  pkg/engine/armoutputs_test.go
  pkg/engine/armresources.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualnetworks.go
  pkg/engine/virtualnetworks_test.go
Labels: approved, size/XXL

#2372 fix: default useCloudControllerManager to false for 1.17
  parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml
  pkg/api/addons_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#2390 chore: update cluster-autoscaler to 1.17.0
  packer/install-dependencies.sh
  parts/k8s/addons/1.17/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/1.17/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/1.17/ip-masq-agent.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/containeraddons/node-problem-detector.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#2399 test: add UT for kubernetesContainerAddonSettingsInit
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
Labels: approved, lgtm, size/XL

#2405 chore: update go toolchain to 1.13.5
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#2393 refactor: make kube-dns addon user-configurable
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2408 docs: configurable component images design doc
  docs/design/custom-container-images.md
Labels: approved, size/L

#2414 feat: support transparent mode for Azure CNI (#2259)
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/L

#2413 feat: add support for Kubernetes 1.17.0
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/common/versions.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#2416 refactor: make coredns addon user-configurable
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/containeraddons/coredns.yaml
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
  test/e2e/go.sum
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/kube-dns.json
Labels: approved, lgtm, size/XXL

#2417 feat: Adding some settings for telemetry collection to api model
  docs/topics/telemetry.md
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  test/e2e/engine/template.go
Labels: approved, lgtm, size/L

#2402 docs: clarify Key Vault as secrets documentation
  docs/topics/README.md
  docs/topics/keyvault-secrets.md
  examples/keyvault-params/README.md
Labels: approved, size/L

#2423 fix: Rotate app insights key
  pkg/api/const.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/XS

#2409 feat: caching application insights bins in windows vhd
  packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS

#2418 chore: Add new VM skus (Ev4, ND40, ...)
  pkg/api/common/helper.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator_test.go
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/L

#2428 revert: Revert "feat: support transparent mode for Azure CNI (#2259) (#2414)"
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2429 chore: Add new VM skus (Ev4, ND40, ...) (#2418) - cherry pick
  pkg/api/common/helper.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator_test.go
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/L

#2427 chore: rev Linux VHDs to 2019.12.09
  pkg/api/azenvtypes.go
  pkg/engine/template_generator_test.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201912_2019.12.09.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201912_2019.12.09.txt
Labels: approved, lgtm, size/L

#2430 test: stop testing 1.12
  Jenkinsfile
Labels: approved, size/XS

#2435 feat: add support for Kubernetes 1.15.7
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2434 feat: add support for Kubernetes 1.14.10
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2436 feat: add support for Kubernetes 1.16.4
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2433 fix: kube-dns and coredns addons UT, back-compat
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/XL

#2437 chore: update VHDs for Kubernetes patch releases
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, lgtm, size/S

#2439 fix: restore VHD CI spec to match versions support
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
Labels: approved, size/S

#2440 chore: remove 1.14.10 support
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2375 fix: change kernel settings based on number of cores
  parts/k8s/cloud-init/artifacts/kubelet.service
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/net-config-validate.sh
  test/e2e/kubernetes/util/util.go
  test/e2e/test_cluster_configs/large-vm-sku.json
Labels: approved, lgtm, size/L

#2438 ci: use Jenkins Azure Service Principal instead of hardcoding default client ID/Secret variables in pipelines
  Jenkinsfile
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/windows/cse_benchmark_aks_vhds.json
  test/e2e/test_cluster_configs/windows/cse_benchmark_win_vhds.json
Labels: approved, lgtm, size/M

#2426 refactor: make kube-proxy addon user-configurable
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/addons/kubernetes-kube-proxy.json
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#2445 test: include node-problem-detector in addons config test
  pkg/api/addons_test.go
Labels: approved, lgtm, size/L

#2449 ci: fix some Jenkins variables
  test/e2e/cluster.sh
Labels: approved, lgtm, size/M

#2447 chore: releasing Windows VHD with 1.16.4, 1.15.7 k8s packages
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.864.191211.txt
Labels: approved, lgtm, size/L

#2451 chore: rev Linux VHDs to 2019.12.11
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201912_2019.12.11.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201912_2019.12.11.txt
Labels: approved, lgtm, size/L

#2452 chore: update cluster-autoscaler for k8s <= 1.16
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#2453 fix: disable accelerated networking for Windows due to instability
  docs/topics/clusterdefinitions.md
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/test_cluster_configs/windows/accelerated_networking.json
Labels: approved, lgtm, size/L, windows

#2444 test: check k8s events to see if node-problem-detector works
  test/e2e/kubernetes/event/event.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#2458 test: ensure clean local git before switching branches
  test/e2e/cluster.sh
Labels: size/XS

#2456 test: improve resiliency of addons UT implementations
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/XXL

#2459 feat: enable user-configurable platformUpdateDomainCount
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/armresources_test.go
  pkg/engine/armtype_test.go
  pkg/engine/availabilitysets.go
  pkg/engine/availabilitysets_test.go
  pkg/engine/masterarmresources_test.go
Labels: approved, lgtm, size/L

#2442 chore: Updating Azure CNI to v1.0.30
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
Labels: approved, lgtm, size/S

#2462 chore: rev etcd to 3.3.18
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#2412 feat: BYOK support on os disk
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/byok.json
Labels: approved, lgtm, size/L

#2465 Byok osdisk cherry pick to 0.45.0
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/byok.json
Labels: approved, lgtm, size/L

#2468 test: use uksouth instead of westus2 for AZ tests
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/XS

#2466 test: restore Windows node labels spec
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, area/e2e, lgtm, size/XS, windows

#2463 refactor: make pod-security-policy addon user-configurable
  docs/topics/clusterdefinitions.md
  examples/addons/custom-manifests/kubernetes-custom-psp.json
  parts/k8s/containeraddons/1.15/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-pod-security-policy.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2450 feat: Move creation of 'ext' HNS network into cse for Windows
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L, windows

#2472 chore: update azure-npm-daemonset addon to v1.0.30
  packer/install-dependencies.sh
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network_policy/azure.json
Labels: approved, size/L

#2469 docs: Issue 2464 improve agentpool extensions docs
  docs/topics/clusterdefinitions.md
  docs/topics/extensions.md
Labels: approved, area/docs, lgtm, size/M

#2336 chore: use go template comments for generate proxy certs script
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
Labels: approved, size/M

#2398 fix: fix ARM dependency issues with vm user-specified extensions on node pools
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/M

#2483 fix: Check microsoft-aks based os publisher for windows in scale scenario.
  cmd/scale.go
Labels: approved, lgtm, size/XS

#2480 refactor: make cilium addon user-configurable
  docs/topics/clusterdefinitions.md
  examples/networkpolicy/kubernetes-cilium.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cilium-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/network/cilium.json
  test/e2e/test_cluster_configs/network/kubenet_containerd.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
Labels: approved, lgtm, size/XXL

#2484 chore: upgrade cni-plugins to v0.7.6
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#2487 fix: hard-coding hyper-v generation when using VHD URls as a quick unblock
  pkg/engine/images.go
  pkg/engine/images_test.go
Labels: approved, do-not-merge/hold, size/XS

#2478 feat: Configuring docker log rotation for Windows nodes
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsconfigfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#2407 feat: Antrea plugin support in AKS Engine
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
  examples/kubernetes.json
  examples/networkplugin/README.md
  examples/networkpolicy/README.md
  examples/networkpolicy/kubernetes-antrea.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/containeraddons/antrea.yaml
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sAgentUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sMasterUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/engine/transform/transformtestfiles/master_resources_scale_temaplate.json
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/network_policy/antrea.json
Labels: approved, lgtm, size/XXL

#2493 chore: lint
  pkg/api/types.go
Labels: size/XS

#2494 test: revert change to default kubernetes.json api model example
  examples/kubernetes.json
Labels: size/XS

#2473 chore: update cloud-provider-azure components to v0.4.0
  packer/install-dependencies.sh
  pkg/api/azenvtypes.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types_test.go
  pkg/engine/template_generator_test.go
Labels: approved, lgtm, size/M

#2496 refactor: make audit-policy and azure-cloud-provider addons user-conf…
  docs/topics/clusterdefinitions.md
  parts/k8s/containeraddons/1.15/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmaster-audit-policy.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmaster-audit-policy.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/kubernetesmaster-audit-policy.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/defaults-apiserver.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2490 chore: support v1.15.7 on Azure Stack
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2488 fix: Fix some path handling in collect-windows-logs script
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/S

#2501 docs: remove mentions of old orchestrators
  docs/community/developer-guide.md
  docs/topics/architecture.md
  docs/topics/extensions.md
  docs/tutorials/custom-vnet.md
  examples/disks-storageaccount/README.md
  examples/keyvaultcerts/README.md
  examples/kubernetes-config/README.md
  examples/networkpolicy/README.md
  examples/vnet/vnetarmtemplate/deploy.ps1
  extensions/hello-world/README.md
  extensions/hello-world/v1/supported-orchestrators.json
  releases/README.Dockerfile.md
Labels: approved, area/docs, lgtm, size/M

#2505 chore: Targeting dec patches for windows VHD
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS

#2506 chore: add the 1.13.12/1.14.8/1.15.5 back.
  pkg/api/common/versions.go
Labels: size/XS

#2497 refactor: move StorageClass into azure-cloud-provider addon
  docs/topics/clusterdefinitions.md
  parts/k8s/addons/kubernetesmasteraddons-azure-csi-storage-classes.yaml
  parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes-custom.yaml
  parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes.yaml
  parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes-custom.yaml
  parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml
  parts/k8s/containeraddons/1.15/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  pkg/engine/artifacts.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL
