Repository Azure/aks-engine, pull requests merged in 2019-10, with the labels that each got.

#2048 feat: use aks windows vhds by default
  docs/topics/clusterdefinitions.md
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.737.190923.txt
Labels: approved, lgtm, size/L, windows

#2001 feat: enable azurestack telemetry for scale and upgrade scenarios
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/azenvtypes.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/azenvtypes.go
  pkg/engine/armresources.go
  pkg/engine/deployment.go
  pkg/engine/deployment_test.go
Labels: approved, lgtm, size/L

#2063 test: don’t timeout k8s resource deletes in E2E
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
Labels: approved, lgtm, size/S

#2061 fix: updating windows release notes script to set a file encoding
  packer/write-release-notes-windows.ps1
Labels: approved, lgtm, size/XS, windows

#1801 fix: Increasing inotify limit to 1048576 from the default 8192
  parts/k8s/cloud-init/artifacts/sysctl-d-60-CIS.conf
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: aks, lgtm, size/XS

#2073 chore: Updating Azure CNI and Azure NPM to v1.0.28
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/S

#2075 chore: update default tiller version to v2.13.1
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, size/S

#1984 docs: supported versions for disconnected Azure Stacks using VHD 2019.09.19
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack.json
Labels: area/docs, lgtm, size/S

#1929 IPv6 dualstack phase2
  examples/dualstack/kubernetes.json
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/defaults.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/ipaddresses.go
  pkg/engine/ipaddresses_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: lgtm, size/L

#2065 test: disable 1.16 tests for various cluster configs
  pkg/api/addons.go
  pkg/api/addons_test.go
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/flannel/docker.json
  test/e2e/test_cluster_configs/network/cilium.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
Labels: approved, lgtm, size/L

#2081 test: don’t test for iis pod restart
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#2087 fix: correcting spelling in documentation
  docs/topics/features.md
Labels: approved, lgtm, size/XS

#2083 test: retry “get pods by prefix substring match”
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#2090 fix: cleaning up features.md
  docs/topics/features.md
Labels: area/docs, lgtm, size/XS

#2085 test: retry “kubectl get config”
  test/e2e/kubernetes/config.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#2089 test: retry az commands in E2E tests
  test/e2e/azure/cli.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/L

#2031 feat: container monitoring addon supports other Azure clouds
  cmd/deploy.go
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/armhelpers/azurestack/loganalytics.go
  pkg/armhelpers/loganalytics.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/L

#2070 docs: Windows vhd doc
  docs/topics/windows-vhd.md
Labels: approved, area/docs, lgtm, size/M, windows

#2088 fix: remove Azure agent specific artifacts from windows vhd
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS, windows

#2092 feat: add support for Kubernetes v1.16.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/S

#2071 chore: Windows update to docker 19.03.2
  packer/configure-windows-vhd.ps1
  parts/k8s/windowsconfigfunc.ps1
  pkg/api/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S, windows

#2097 test: retry establishing ssh connection for e2e
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/remote/ssh.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/M

#2095 chore: update default IPv6 subnet for dual stack, update docs
  examples/dualstack/README.md
  examples/dualstack/kubernetes.json
  pkg/api/const.go
Labels: area/docs, size/M

#2096 fix: add read perms for CSINodes to cluster-autoscaler role
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2093 chore: add legal notice to vhd
  packer/packer_source.sh
  packer/vhd-image-builder.json
  releases/notice/notice.txt
Labels: approved, lgtm, size/XXL

#2108 feat: use aks windows vhds by default for Azure Stack
  pkg/api/azenvtypes.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#2109 fix: container monitoring add-on failure in the generate path
  pkg/api/addons.go
Labels: approved, lgtm, size/S

#2115 chore: move cloud-init's apt commands to cse script
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2119 fix: correcting documentation
  docs/community/README.md
Labels: lgtm, size/XS

#2104 test: get Running pods by prefix in most cases
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/L

#2116 chore: rev VHD images to 2019.10.03
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.10.03.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.10.03.txt
Labels: approved, lgtm, size/L

#2114 chore: update to MS Moby 3.0.7
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2120 test: retry "get nodes that match regex" test
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, size/M

#2078 fix: auditd improvements
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/L

#2122 [wip] docs: correcting grammatical mistakes
  docs/tutorials/containermonitoringaddon.md
Labels: lgtm, size/M

#2121 fix: restore original moby apt prod.list URL
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2126 docs: tidying up
  docs/topics/aad.md
  docs/topics/architecture.md
  docs/topics/clusterdefinitions.md
  docs/topics/extensions.md
  docs/topics/features.md
  docs/topics/gpu.md
  docs/topics/kubernetes-developers.md
  docs/topics/kubernetes-walkthrough.md
  docs/topics/monitoring.md
  docs/topics/upgrade.md
  docs/topics/windows-and-kubernetes.md
  docs/tutorials/quickstart.md
Labels: approved, lgtm, size/L

#2112 feat: add support for Kubernetes 1.17.0-alpha.1
  .pipelines/pr-e2e.yaml
  examples/kubernetes-releases/kubernetes1.17.json
  packer/install-dependencies.sh
  parts/k8s/addons/1.17/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/containeraddons/1.17/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/1.17/ip-masq-agent.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2128 test: faster fail during soak test re-build
  test/e2e/runner.go
Labels: approved, size/S

#2055 fix: don’t assign distro if image ref is provided
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/XL

#2132 fix: fix deployment cleanup in cleanup script
  packer/vhd-rg-cleanup.sh
Labels: approved, lgtm, size/XS

#2105 test: Add api model entry for sgx
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/api/common/helper.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/sgx-test.yaml
  test/e2e/test_cluster_configs/sgx.json
Labels: approved, lgtm, size/L

#2130 feat: enable re-use of VHD
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2131 test: print logs after E2E tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#2137 test: skip time sync for 18.04-backed sgx test
  test/e2e/test_cluster_configs/sgx.json
Labels: size/XS

#2136 chore: rev AKS VHDs to 2019.10.09
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.09.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201910_2019.10.09.txt
Labels: approved, lgtm, size/L

#2135 fix: revert 'trust Azure Stack's CA cert before pre-provision extensions'
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2050 feat: add linux support for kubenet + containerd
  examples/kubernetes-kubenet-containerd.json
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/azenvtypes.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network/kubenet_containerd.json
Labels: approved, lgtm, size/XL

#2133 test: Add 'latestReleasedVersion' target to Jenkins jobs
  Jenkinsfile
  test/e2e/test_cluster_configs/windows/cse_benchmark_aks_vhds.json
  test/e2e/test_cluster_configs/windows/cse_benchmark_win_vhds.json
  test/e2e/test_cluster_configs/windows/custom_image.json
  test/e2e/test_cluster_configs/windows/image_reference.json
  test/e2e/test_cluster_configs/windows/shared_image_gallery.json
  test/e2e/test_cluster_configs/windows/vhd_url.json
Labels: approved, lgtm, size/M

#2143 feat: Support 1.16.1 version on Azure Stack
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2144 test: minimal Windows custom VNET cluster config
  test/e2e/test_cluster_configs/windows/custom_vnet.json
Labels: approved, size/S

#2139 test: make AfterSuite log output optional
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#2147 fix: pass 'cacert' option to curl pre-provision scripts on Azure Stack
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
Labels: lgtm, size/M

#2155 chore: Use WindowsServer VHDs with Oct patches
  packer/windows-vhd-builder.json
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS, windows

#2157 fix: fix cni conf json for single exception address
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2159 feat: add support for Kubernetes v1.14.8
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2160 feat: add support for Kubernetes 1.13.12
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2164 feat: add support for Kubernetes v1.15.5
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2163 feat: add support for Kubernetes v1.16.2
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2162 chore: add Kubernetes patch releases to VHD
  packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#2169 chore: Add Azure Stack Windows api model example file
  examples/azure-stack/kubernetes-windows.json
Labels: azurestack, size/M

#2156 chore: Adding collectlogs.ps1 to windows AKS VHD
  packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#1892 fix: Update mirror probe port
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/S

#2172 chore: rev VHD images to 2019.10.15
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.15.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201910_2019.10.15.txt
Labels: approved, lgtm, size/L

#2176 chore: Updating aks-engine to use oct windows aks vhd
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.805.191016.txt
Labels: approved, lgtm, size/L, windows

#2103 chore: document some bug workarounds
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2179 test: build larger subnets for E2E custom VNET scenario
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/XS

#2184 fix: actually use cloudprovider write rate limits
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2185 chore: update cluster-autoscaler to latest patch releases
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#2100 chore: enable cloudproviderBackoff v2 for k8s >= 1.14
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/cloudprovider-config-validate.sh
Labels: approved, lgtm, size/L

#2187 test: add e2e test parameter for skipping all ssh tests
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#2049 fix: Wait for management IP after creating ext network.
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M, windows

#2189 fix: don't run CSE apt purge operations on coreos
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2127 feat: expose PlatformFaultDomainCount in the apimodel
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/availabilitysets.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#2192 fix: CSE file wait is idempotent
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2166 fix: deploy CSI drivers for Azure Disk & Azure File when cloud-controller-manager is enabled
  docs/topics/clusterdefinitions.md
  parts/k8s/addons/kubernetesmasteraddons-azure-csi-storage-classes.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azuredisk-csi-driver-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azurefile-csi-driver-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/XXL

#2188 chore: default to ubuntu distro for customHyperkubeImage
  docs/topics/kubernetes-developers.md
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/L

#2196 fix: run all CSE apt-get purge operations in background
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2170 feat: Adding steps to get log collection scripts for windows nodes
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S, windows

#2194 fix: move CSE endcustomscript log to very end of CSE
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, size/S

#2197 test: enable convenient customHyperkubeImage E2E tests
  Jenkinsfile
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, size/S

#2198 test: cluster configs that don't work in 1.17
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/sgx.json
Labels: approved, size/S

#2193 chore: update go toolchain to 1.12.12
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#2199 Revert "feat: expose PlatformFaultDomainCount in the apimodel"
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/availabilitysets.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/M

#2148 refactor: Windows node restart cleanup script
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodecleanup.ps1
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL, windows

#2153 feat: enable containermonitoring addon support for Azurestack and also update the agent to latest version
  cmd/deploy.go
  cmd/deploy_test.go
  docs/topics/azure-stack.md
  docs/topics/monitoring.md
  docs/tutorials/containermonitoringaddon.md
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: size/XXL

#2211 fix: default Translator if not specified to not panic
  pkg/api/types.go
  pkg/engine/armresources_test.go
  pkg/engine/template_generator.go
Labels: approved, size/M

#2200 chore: add Kubernetes patch releases to VHD
  docs/topics/azure-stack.md
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
Labels: size/XS

#2213 test: skip tests when block ssh port enabled
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#2214 Revert "test: retry az commands in E2E tests (#2089)"
  test/e2e/azure/cli.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#2217 fix: go template and does not short circuit causing nil ptr
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armresources_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2201 fix: Resolve incorrect Windows extension params
  pkg/engine/engine.go
  pkg/engine/engine_test.go
Labels: approved, lgtm, size/XS, windows

#2219 revert: Revert "refactor: Windows node restart cleanup script (#2148)"
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodecleanup.ps1
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2204 feat: blang/semver and gofrs/uuid does not match module compatibility
  Gopkg.lock
  Gopkg.toml
  cmd/deploy_test.go
  cmd/generate.go
  cmd/generate_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/rotate_certs_test.go
  pkg/api/mocks.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/graph.go
  pkg/operations/dcosupgrade/upgradecluster.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/gofrs/uuid/LICENSE
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/fuzz.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/sql.go
  vendor/github.com/gofrs/uuid/uuid.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: approved, lgtm, size/XXL

#2210 chore: enable CSE ACR connectivity check only for AKS
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, size/L

#2226 Remove desktop/mobile from policy issue template
  .github/ISSUE_TEMPLATE/azure-policy-for-aks-engine-issue.md
Labels: lgtm, size/S

#2173 feat: Azure policy add-on
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  examples/addons/azure-policy/README.md
  examples/addons/azure-policy/azure-policy.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-disabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/containeraddons/azure-policy-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: lgtm, size/XXL

#2230 test: remove soak test log statements with connection string
  test/e2e/azure/cli.go
Labels: approved, lgtm, size/S

#2231 fix: Ensured identity system passed from cli is propagated to api model
  cmd/deploy.go
  cmd/deploy_test.go
Labels: approved, lgtm, size/M

#2234 chore: remove support for Kubernetes 1.10.x
  cmd/generate_test.go
  cmd/rotate_certs_test.go
  examples/addons/cluster-autoscaler/kubernetes-cluster-autoscaler.json
  examples/addons/nvidia-device-plugin/nvidia-device-plugin.json
  examples/kubernetes-releases/kubernetes1.10.json
  examples/windows/kubernetes-hyperv.json
  pkg/api/common/versions.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/mockclients.go
  pkg/engine/testdata/addons/kubernetes-custom-psp.json
  pkg/engine/testdata/addons/kubernetes-kube-proxy.json
  pkg/engine/testdata/addons/kubernetes.json
  pkg/engine/testdata/agentPoolOnly/v20170831/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfile.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfileV2.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithOnlyNetworkPlugin.json
  pkg/engine/testdata/disks-managed/kubernetes-vmss.json
  pkg/engine/testdata/kubernetesversions/kubernetes1.11.json
  pkg/engine/testdata/largeclusters/kubernetes-vmss.json
  pkg/engine/testdata/windows/kubernetes-kubernetesconfig.json
  pkg/engine/testdata/windows/kubernetes-vmss.json
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: approved, lgtm, size/L

#2239 chore: update to MS Moby 3.0.8
  packer/install-dependencies.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2241 test: skip cloudprovider config test in no ssh scenario
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#2236 chore: Adding a log collection script for Windows
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/S

#2244 chore: remove k8s 1.10 from VHD
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2060 fix: retain nsg rules during upgrade
  pkg/engine/transform/transform.go
  pkg/engine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sAgentUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sMasterUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
Labels: approved, lgtm, size/XXL

#2246 chore: log collection bugfix around some nonexistant paths
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/XS
