Repository Azure/aks-engine, pull requests merged in 2019-09, with the labels that each got.

#1582 fix: Update rbac settings for cluster autoscaler
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1877 ci: Running e2e tests as part of windows VHD build
  .pipelines/vhd-builder-windows.yaml
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/M, windows

#1896 feat: add new Azure VM SKUs
  pkg/engine/armvariables_test.go
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/L

#1897 feat: add germanynorth and germanywestcentral regions
  pkg/api/types_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/S

#1900 chore: remove oms extension docs since they are obsolete
  extensions/microsoft-oms-agent-k8s/README.md
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  extensions/microsoft-oms-agent-k8s/v1/supported-orchestrators.json
  extensions/microsoft-oms-agent-k8s/v1/template-link.json
  extensions/microsoft-oms-agent-k8s/v1/template.json
Labels: approved, lgtm, size/L

#1909 fix: add #EOF for dhcpv6 service
  parts/k8s/cloud-init/artifacts/dhcpv6.service
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1907 docs: supported versions for disconnected Azure Stacks using VHD 2019.08.09 & 2019.08.21
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack.json
Labels: approved, azurestack, lgtm, size/S

#1889 fix: Remove the blind mkdir when writing outputs (#1048)
  pkg/helpers/filesaver.go
Labels: approved, lgtm, size/XS

#1904 feat: add new Azure Switzerland regions
  pkg/api/types_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/S

#1891 chore: make the pki key size settable.
  cmd/deploy.go
  cmd/generate.go
  cmd/root_test.go
  cmd/rotate_certs.go
  cmd/rotate_certs_test.go
  cmd/scale.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine_test.go
  pkg/engine/output_test.go
  pkg/engine/params_k8s_test.go
  pkg/engine/params_test.go
  pkg/helpers/pki.go
  pkg/helpers/pki_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XL

#1888 feat: add build and deploy windows zip file support on Azure Stack
  Makefile
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/testdata/azurestack/kubernetes.json
  scripts/build-windows-k8s.sh
Labels: approved, size/L

#1906 feat: add support for Kubernetes 1.16.0-beta.2
  pkg/api/common/versions.go
  test/e2e/kubernetes/service/service.go
Labels: approved, lgtm, size/XS

#1922 chore: add job exclusion regex to jenkinsfile
  Jenkinsfile
Labels: approved, lgtm, size/S

#1924 chore: bump keyvault-flexvol to v0.0.13
  examples/addons/keyvault-flexvolume/README.md
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#1933 chore: Update Windows to version 17763.678.1908092216
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#1934 chore: inject log analytics workspace key into test env config
  Jenkinsfile
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/container_monitoring.json
Labels: approved, size/S

#1938 feat: add support for Kubernetes 1.16.0-rc.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#1931 chore: rev etcd to v3.3.15
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#1847 feat: enable deployment telemetry for generate command on Azure Stack
  examples/azure-stack/kubernetes-azurestack.json
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources.go
  pkg/engine/deployment.go
  pkg/engine/deployment_test.go
Labels: approved, lgtm, size/L

#1940 chore: rev VHD image references to 2019.09.10
  docs/topics/azure-stack.md
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.10.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.10.txt
Labels: approved, lgtm, size/L

#1939 feat: add new Norway regions
  pkg/api/types_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/S

#1941 chore: add upgrade and scale parallel jobs
  Jenkinsfile
Labels: approved, size/L

#1925 test: E2E: goroutine and err response cleanup
  test/e2e/engine/template.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/persistentvolume/persistentvolume.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/kubernetes/storageclass/storageclass.go
Labels: approved, size/XXL

#1921 fix: add hostname to CSE command so it shows in ARM deployment errors
  docs/howto/troubleshooting.md
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/M

#1946 test: crash docker and validate against common node count
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#1947 test: az storage file download-batch --destination must exist
  test/e2e/azure/cli.go
Labels: approved, size/XS

#1944 fix: update the location of the VHD footprint file on VMs
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#1948 test: more resilience when k get deployment
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#1949 test: s/southcentralus/uksouth
  test/e2e/config/config.go
  test/e2e/config/config_test.go
Labels: approved, size/XS

#1950 test: pod WaitOnSucceeded against distinct pod
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#1953 chore: fix closure capture for UPGRADE_VERSIONS
  Jenkinsfile
Labels: approved, lgtm, size/XS

#1954 chore: Updating windows image references to target Sept updates
  docs/topics/clusterdefinitions.md
  packer/windows-vhd-builder.json
  pkg/api/const.go
Labels: approved, lgtm, size/XS, windows

#1955 chore: rev vhd to 2019.09.13
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/azenvtypes.go
  pkg/engine/templates_generated.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.13.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.13.txt
Labels: approved, do-not-merge/hold, lgtm, size/L

#1959 chore: install metrics-server v0.3.4 via VHD
  packer/install-dependencies.sh
Labels: approved, size/XS

#1956 test: fix "run multiple commands in succession" implementation
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/L

#1935 fix: not overwrite service principal profile for hosted master
  parts/k8s/kubernetesparams.t
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: aks, approved, lgtm, size/M

#1961 doc: Clarify defaults for enablePodSecurityPolicy
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/XS

#1965 test: run gpu tests in westus2
  test/e2e/test_cluster_configs/gpu.json
Labels: approved, size/XS

#1963 docs: add 1.16 api model example
  examples/kubernetes-releases/kubernetes1.16.json
Labels: approved, size/M

#1962 chore: rev VHD images to 2019.09.16
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.16.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.16.txt
Labels: approved, size/L

#1908 chore: update ip-masq-agent to v2.5.0
  packer/install-dependencies.sh
  parts/k8s/containeraddons/1.16/ip-masq-agent.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1816 fix: delete hyperkube images before starting kubelet
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#1973 feat: add support for Kubernetes 1.14.7
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1974 feat: add support for Kubernetes 1.15.4
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1975 feat: add support for Kubernetes 1.13.11
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1972 feat: add support for Kubernetes 1.16.0
  examples/dualstack/kubernetes.json
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1977 fix: correct scale message after scale operations
  cmd/scale.go
Labels: approved, lgtm, size/XS

#1983 test: run DNS validation against more than one query
  test/e2e/kubernetes/workloads/validate-dns-linux.yaml
Labels: approved, lgtm, size/XS

#1976 chore: add new k8s releases to VHD CI spec
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, size/M

#1986 chore: update network plugin value to kubenet in Azure Stack example file
  examples/azure-stack/kubernetes-azurestack.json
Labels: lgtm, size/XS

#1985 test: update Jenkins test configs for k8s versions
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/network/cilium.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/rbac_disabled.json
  test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json
Labels: approved, size/XS

#1893 fix: check the nodes of all agentpools during upgrade
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: aks, approved, lgtm, size/XS

#1987 test: retry’able node get
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/L

#1991 test: because where would we be without standardized orthography
  test/e2e/test_cluster_configs/windows/accelerated_networking.json
Labels: approved, lgtm, size/XS

#1992 ci: consistent whitespace
  packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#1988 test: skip time sync test for 18.04
  .pipelines/e2e-job-template.yaml
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/XS

#1990 ci: Adding provenance info in Windows VHD release notes
  .pipelines/vhd-builder-windows.yaml
  packer/windows-vhd-builder.json
  packer/write-release-notes-windows.ps1
Labels: approved, lgtm, size/S, windows

#1993 test: retry remote ssh commands
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/remote/ssh.go
Labels: approved, size/M

#1998 chore: rev VHD images to 2019.09.19
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.19.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.19.txt
Labels: approved, lgtm, size/L

#2000 test: Use Standard_D2_v3 and low pri VMSS in E2E test configs
  test/e2e/test_cluster_configs/base.json
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/flannel/docker.json
  test/e2e/test_cluster_configs/gpu.json
  test/e2e/test_cluster_configs/kubenet.json
  test/e2e/test_cluster_configs/network/cilium.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/no_outbound.json
  test/e2e/test_cluster_configs/not_in_vhd.json
  test/e2e/test_cluster_configs/rbac_disabled.json
  test/e2e/test_cluster_configs/storage_profile.json
  test/e2e/test_cluster_configs/vmss_master.json
  test/e2e/test_cluster_configs/windows/accelerated_networking.json
  test/e2e/test_cluster_configs/windows/custom_image.json
  test/e2e/test_cluster_configs/windows/custom_vnet.json
  test/e2e/test_cluster_configs/windows/image_reference.json
  test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json
  test/e2e/test_cluster_configs/windows/shared_image_gallery.json
  test/e2e/test_cluster_configs/windows/vhd_url.json
Labels: approved, size/L

#1967 fix: Updating CSE behavior for windows nodes to fail ARM deployment on error
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/M, windows

#1997 test: address 4 E2E test flakes
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/persistentvolume/persistentvolume.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/kubernetes/storageclass/storageclass.go
  test/e2e/kubernetes/util/util.go
Labels: approved, size/L

#1943 feat: Windows vhd artifact caching
  packer/configure-windows-vhd.ps1
  packer/write-release-notes-windows.ps1
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L, windows

#2005 test: s/Standard_D2_3/Standard_D2_v3
  test/e2e/test_cluster_configs/windows/accelerated_networking.json
Labels: approved, size/XS

#2004 test: enable stability tests for PR E2E
  .pipelines/e2e-job-template.yaml
  .pipelines/pr-e2e.yaml
Labels: approved, size/XS

#2006 fix: cleanup apt artifacts before running apt
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, size/S

#975 [CIS conformance] fix: disable ReadOnlyPort since it's only for heapster
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, size/M

#2008 chore: RBAC is required for Kubernetes >= 1.15.0
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/test_cluster_configs/rbac_disabled.json
Labels: approved, lgtm, size/L

#2013 fix: continue upgrading after node drain error
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#2011 fix: lowercase vm name before calling drain node
  pkg/operations/cordondrainvm.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#2014 Revert "fix: retain custom nsg rules during upgrade"
  pkg/engine/transform/transform.go
  pkg/engine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUp.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sAgentUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/TestNormalizeResourcesForK8sMasterUpgrade.failure.json
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
Labels: approved, size/XXL

#2016 test: dns-liveness against more than one URL
  test/e2e/kubernetes/workloads/dns-liveness.yaml
Labels: approved, size/XS

#2021 test: ensure we don’t dereference nil node List
  test/e2e/kubernetes/node/node.go
Labels: approved, size/XS

#2015 test: more resilient “wait for successful pod readiness checks”
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#2023 ci: Win CSE benchmark tests
  Jenkinsfile
  test/e2e/test_cluster_configs/windows/cse_benchmark_aks_vhds.json
  test/e2e/test_cluster_configs/windows/cse_benchmark_win_vhds.json
Labels: approved, lgtm, size/L

#2029 feat: add support for Kubernetes 1.16.0 on Azure Stack
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2024 fix: nil pointer check for data disks in transform
  pkg/engine/transform/transform.go
Labels: approved, lgtm, size/S

#2035 chore: rev VHD to 2019.09.24
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.24.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.24.txt
Labels: approved, size/L

#2034 chore: update go toolchain to 1.12.10
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#2017 docs: changing example to use the aks base image and eliminate entry for k8s version
  examples/azure-stack/kubernetes-azurestack.json
Labels: approved, azurestack, lgtm, size/XS

#2043 e2e: fix missing null coalescing operator
  Jenkinsfile
Labels: approved, size/XS

#2037 fix: verify LCOW in makedev.ps1
  docs/community/developer-guide.md
  makedev.ps1
Labels: approved, lgtm, size/S, windows

#2038 chore: update cluster-autoscaler to latest patch releases
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#2047 test: availability zones not available in all regions
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/XS

#2040 feat: Skip downloading of pause image if image already present in windows vhd
  packer/configure-windows-vhd.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#2052 feat: Skip installing docker if already installed on windows vhd
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L, windows
