Repository Azure/aks-engine, pull requests merged in 2019-11, with the labels that each got.

#2250 docs: update azure-policy add-on README doc
  examples/addons/azure-policy/README.md
Labels: size/S

#2252 feat: Copy linux release notes out of VHD instead of parsing console output
  .pipelines/vhd-builder.yaml
  packer.mk
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
Labels: approved, lgtm, size/S

#2255 fix: add go module export
  Makefile
Labels: lgtm, size/XS

#2271 fix: Change Azure CNI default version to match latest windows vhd
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#2268 fix: Add 1.0.28 Azure CNI zip file into windows vhd
  packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#2258 ci: ignore generated file in codecov
  .codecov/codecov.yml
Labels: approved, lgtm, size/XS

#2279 chore: lock the golangci-lint to 1.21.0 and use vendored modules
  hack/tools/Makefile
  scripts/validate-go.sh
Labels: approved, lgtm, size/XS

#2207 feat: expose PlatformFaultDomainCount in the apimodel
  cmd/scale.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/L

#2284 fix: bumping timeout for getting management ip on windows nodes
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  pkg/i18n/translations_generated.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#2253 feat: Adding more debug files to windows VHD
  packer/configure-windows-vhd.ps1
  packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS, windows

#2282 fix: addons "update config" is upgrade-only
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults.go
Labels: approved, size/M

#2275 refactor: recreate missing masters before upgrading
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/M

#2289 fix: make ensure-generated should call make generate
  pkg/engine/templates_generated.go
  pkg/i18n/translations_generated.go
  scripts/ensure-generated.sh
Labels: approved, lgtm, size/M

#2257 fix: add retry/logging/validation around docker command for windows
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L, windows

#2293 chore: improve build through parallel tests and stable tools
  Makefile
  cmd/cmd_suite_test.go
  cmd/deploy_test.go
  cmd/generate_test.go
  cmd/get_versions_test.go
  cmd/orchestrators_test.go
  cmd/root_test.go
  cmd/rotate_certs.go
  cmd/rotate_certs_test.go
  cmd/scale_test.go
  cmd/upgrade_test.go
  cmd/version_test.go
  hack/tools/Makefile
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults_test.go
  pkg/armhelpers/azureclient_test.go
  pkg/armhelpers/deploymentError_test.go
  pkg/armhelpers/storage_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine_test.go
  pkg/engine/params_k8s_test.go
  pkg/engine/params_test.go
  pkg/helpers/default_helpers.go
  pkg/helpers/fast_helpers.go
  pkg/helpers/helpers.go
  pkg/helpers/pki.go
  pkg/operations/k8sapi_ops_test.go
  scripts/ginkgo.coverage.sh
Labels: approved, size/XXL

#2238 feat: support using existing identity for addons
  pkg/api/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/L

#2288 fix: Modified coredns.yaml to include import parameters
  parts/k8s/addons/coredns.yaml
Labels: approved, lgtm, size/XS

#2298 fix: extract kubelet and kubectl binaries from hyperkube's binary folder when possible
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2161 chore: use Azure CCM for k8s 1.16 and later
  packer/install-dependencies.sh
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/defaults-cloud-controller-manager.go
  pkg/api/defaults-cloud-controller-manager_test.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/storageclass-azurefile-external.yaml
Labels: approved, lgtm, size/XXL

#1708 feat: add DisableOutboundSNAT feature
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: size/L

#2310 test: ensure manifests aren't change by go template processing
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
Labels: approved, size/S

#2291 docs: Working way to use SGX
  docs/topics/sgx.md
  test/e2e/kubernetes/workloads/sgx-test.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#2191 refactor: install kube- components without hyperkube for k8s 1.17+
  packer/install-dependencies.sh
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/kubernetesparams.t
  parts/k8s/manifests/1.17/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-scheduler.yaml
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2158 feat: add support for Kubernetes v1.17.0-beta.1
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2314 fix: remove support for v1.13.12, v1.14.8, v1.15.5, v1.16.2
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
  pkg/api/addons_test.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/defaults-cloud-controller-manager_test.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/engine_test.go
Labels: approved, lgtm, size/L

#2237 docs: supported versions for disconnected Azure Stacks using VHD 2019.10.24
  docs/topics/azure-stack.md
Labels: approved, area/docs, lgtm, size/M

#2313 refactor: render manifest specs at template generation time
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/kubernetesparams.t
  parts/k8s/manifests/1.17/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-scheduler.yaml
  parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/engine/engine_test.go
  pkg/engine/params.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#2274 refactor: rationalize defaults enforcement order
  pkg/api/defaults-kubelet.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, size/L

#2319 fix: lint errors
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/template_generator_test.go
Labels: approved, size/S

#2259 feat: support transparent mode for Azure CNI
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2321 (docs/sgx): Add SGX Device plugin installation details
  docs/topics/sgx.md
Labels: lgtm, size/L

#2322 fix: lint
  pkg/engine/template_generator_test.go
Labels: approved, size/XS

#2325 docs: Update sgx device plugin image name
  docs/topics/sgx.md
Labels: lgtm, size/XS

#2331 (docs/sgx): Add TOC and update device plugin docs
  docs/topics/sgx.md
Labels: lgtm, size/S

#2327 fix: userAssignedIdentityId in windows azure.json missing quotes
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2330 fix: support cloud-node-manager in k8s 1.16
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cloud-node-manager.yaml
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#2323 chore: Updating Azure CNI and Azure NPM to v1.0.29
  packer/configure-windows-vhd.ps1
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#2320 refactor: use go template for kubelet systemd config
  parts/k8s/cloud-init/artifacts/kubelet.service
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2326 chore: use go template comments for addons yaml specs
  docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml
  parts/k8s/addons/1.10/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.15/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/containeraddons/azure-policy-deployment.yaml
  parts/k8s/containeraddons/dns-autoscaler.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-azuredisk-csi-driver-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2332 chore: add CSI components to VHD
  packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2335 test: enable "everything" cluster config test for 1.17
  test/e2e/test_cluster_configs/everything.json
Labels: lgtm, size/XS

#2334 feat: add support for Kubernetes 1.17.0-beta.2
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2333 feat: Support custom k8s components in v1.17
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2338 fix: VHD release notes should output the kernel version at end
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2318 fix: update Container monitoring add-on with 11012019 agent image changes
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/M

#2340 chore: rev Linux VHD images to 2019.11.18
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201911_2019.11.18.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201911_2019.11.18.txt
Labels: approved, size/L

#2341 docs: fix bad Linux kernel info on 16.04 vhd 2019.10.24
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.24.txt
Labels: approved, size/XS

#2339 refactor: optimize CSE main script for go template
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/dhcpv6.service
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  parts/k8s/cloud-init/jumpboxcustomdata.yml
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#2346 test: add RunWithRetry to E2E, use for curl tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/M

#2345 fix: enable cloud-node-manager addon on upgrade when appropriate
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/L

#2303 ci: stop testing k8s 1.11 and 1.12 on PRs
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/S

#2349 test: remove windows-specific tests, use windows node pools
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/release/default/definition.json
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#2354 test: add k8s 1.16 and 1.17 to TestExampleAPIModel unit test
  cmd/generate_test.go
Labels: approved, lgtm, size/S

#2353 docs: update kubernetes-developers.md
  docs/topics/kubernetes-developers.md
Labels: approved, area/docs, lgtm, size/L

#2352 test: resilient print pod logs during E2E, print more pod logs
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/S

#2357 chore: update CoreDNS to 1.6.5
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#2356 feat: add support for Kubernetes 1.17.0-rc.1
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2351 test: re-enable E2E test for inotify max_user_watches
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, lgtm, size/XS

#2358 fix: correct defaults order for setting IPAddressCount
  pkg/api/defaults-kubelet.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L

#2359 test: resilient az group create during E2E provisioning
  test/e2e/azure/cli.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/M

#2355 test: more resilient kubectl run interfaces
  test/e2e/kubernetes/config.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/persistentvolume/persistentvolume.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/kubernetes/storageclass/storageclass.go
Labels: approved, do-not-merge/hold, size/L

#2360 test: use SLB in E2E cluster configs
  examples/e2e-tests/kubernetes/release/default/definition.json
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/nginx-master.yaml
  test/e2e/kubernetes/workloads/pod-pvc.yaml
Labels: approved, lgtm, size/L

#2347 fix: enable CSI addons on upgrade when appropriate
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/L

#2368 test: ensure cluster-autoscaler tests don't run if min-nodes is > nodes in pool
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS
