Repository Azure/aks-engine, pull requests merged in 2019-03, with the labels that each got.

#615 chore: add support for k8s version 1.11.8
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#525 feat: add force parameter to the upgrade command
  cmd/upgrade.go
  cmd/upgrade_test.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: approved, area/cli, feature/upgrade, lgtm, size/XL

#621 chore: update VHD reference to 2019.02.28
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#599 feat: Azure #402 - Disable windows auto update
  docs/topics/windows-and-kubernetes.md
  examples/windows/kubernetes-windows-automatic-update.json
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#625 feat: default to Kubernetes 1.11
  pkg/api/common/const.go
Labels: approved, lgtm, size/XS

#627 test: add unit tests for azureconst.go
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/XL

#629 fix: simplify comparison to satisfy linter
  pkg/api/types_test.go
Labels: approved, area/test, lgtm, size/XS

#631 chore: update the deis docker go-dev image to v1.19.1
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#636 chore: remove some invalid acs-engine references in aks-engine
  docs/faq.md
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#570 feat: Copy custom annotations, labels, taints from old to new nodes during upgrade
  docs/topics/upgrade.md
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/L

#634 chore: rev the nvidia driver version for the newer driver
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, do-not-merge/hold, size/XS

#640 chore: add serbrech to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#623 chore: update hybrid api model to "enableAutomaticUpdates": false
  examples/e2e-tests/kubernetes/windows/hybrid/definition.json
Labels: approved, lgtm, size/XS

#641 ci: add E2E pipeline status to README
  README.md
Labels: approved, lgtm, size/XS

#639 docs: upgrade --force
  docs/topics/upgrade.md
Labels: approved, lgtm, size/S

#644 docs: add more package documentation for aks-engine's godoc
  pkg/armhelpers/utils/util.go
  pkg/engine/doc.go
  pkg/engine/transform/doc.go
  pkg/helpers/doc.go
  pkg/operations/doc.go
  pkg/test/util.go
Labels: approved, lgtm, size/S

#646 fix: address govet and gosimple issues
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#630 chore: install -proposed systemd package
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, lgtm, size/S

#649 fix: Remove retaining custom properties logic for master nodes
  docs/topics/upgrade.md
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/S

#450 ci: generate release notes for component versions installed in VHD build
  .pipelines/vhd-builder.yaml
  packer.mk
  packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#642 docs: update E2E pipeline process in developer docs
  docs/community/developer-guide.md
Labels: approved, lgtm, size/XS

#650 fix: always assign target version on upgrade
  cmd/upgrade.go
  cmd/upgrade_test.go
Labels: approved, lgtm, size/M

#655 chore: add systemd/xenial-proposed to list of installed packages in VHD notes
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#658 chore: add go report card badge to README
  README.md
Labels: approved, lgtm, size/XS

#663 test: pass in skip_test env variable down to the test container
  test.mk
Labels: approved, size/XS

#656 ci: update build status badge to ci pipeline
  README.md
Labels: approved, lgtm, size/XS

#662 test: increase e2e pod delete timeout tolerance to 5 mins
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/XS

#654 chore: update VHD to 2019.03.05
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604-201903_2019.03.05.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine_2019.03.05.txt
Labels: approved, lgtm, size/L

#668 fix: enable systemd proposed implementation for non-VHD scenario
  parts/k8s/kubernetesinstalls.sh
Labels: approved, size/XS

#670 test: check error returned when checking outbound connection of pod
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#677 fix: enable no_template with Azure Stack
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/customscripts.go
  pkg/engine/networksecuritygroups.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#684 fix: master vmss cluster configuration errors in template refactor
  pkg/engine/armvariables.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/XS

#687 test: fix template refactor unit tests
  pkg/engine/virtualmachinescalesets_test.go
Labels: size/XS

#688 fix: 2 Azure Stack vars are obligatory
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, size/XS

#690 fix: update apiVersionCompute to 2018-10-01 in armvariables
  pkg/armhelpers/test.json
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/L

#692 fix: missing variable declarations for masters-only scenario
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, size/L

#701 fix: agentpools have their own “is custom vnet” logic
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
Labels: approved, lgtm, size/XS

#699 fix: remove obsolete allocateNodeCidrs ARM variable
  parts/k8s/kubernetesmastervars.t
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/S

#703 fix: implement cosmosEtcd no_template
  pkg/engine/armvariables.go
  pkg/engine/cosmosdb.go
  pkg/engine/cosmosdb_test.go
  pkg/engine/masterarmresources.go
Labels: approved, size/L

#706 test: remove obsolete allocateNodeCidrs var
  pkg/engine/armvariables_test.go
Labels: size/XS

#702 test: don't hardcode base 64 encoded script values in template tests
  pkg/engine/armvariables_test.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/M

#708 fix: primaryScaleSetName and primaryAvailabilitySetName var logic is …
  pkg/engine/armvariables.go
Labels: approved, size/XS

#705 fix: add err != nil checks for json Unmarshal in scale and upgrade ops
  cmd/scale.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/S

#698 build: add "build-container" target
  Makefile
  releases/Dockerfile.linux
  releases/README.Dockerfile.md
Labels: approved, lgtm, size/M

#733 ci: run dep check before linting in the pr-e2e pipeline
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/XS

#732 fix: use the correct go sdk import for system assigned role assignments
  Gopkg.lock
  pkg/engine/armtype.go
  pkg/engine/systemroleassignments.go
  pkg/engine/systemroleassignments_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/version.go
Labels: approved, size/XXL

#700 build: compress aks-engine binaries
  Makefile
Labels: approved, lgtm, size/XS

#734 fix: add err check while JSON marshalling the ARM template
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/XS

#710 fix: Allow masters with custom images to use data disks for etcd
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: size/M

#735 fix: add the system role assignment object as the resource instead of the function pointer
  pkg/engine/armresources.go
Labels: approved, size/XS

#672 feat: add selective agentpool upgrade support - VMSS
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, lgtm, size/XS

#715 style: enable vet shadow and remove the shadowed declaration go anti-pattern
  .golangci.yml
  cmd/deploy.go
  pkg/api/apiloader.go
  pkg/api/orchestrators.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azureclient.go
  pkg/engine/output_test.go
  pkg/engine/transform/transform.go
  pkg/helpers/pki_test.go
  pkg/operations/deletevm.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgrader.go
  test/aks-engine-test/main.go
  test/aks-engine-test/promote/promote.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#691 test: describe pod object in error scenario
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/S

#693 fix: commands return errors rather than exit
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/generate.go
  cmd/generate_test.go
  cmd/get_versions_test.go
  cmd/orchestrators_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/scale.go
  cmd/scale_test.go
  cmd/upgrade.go
  cmd/upgrade_test.go
  cmd/version.go
  cmd/version_test.go
  main.go
Labels: approved, lgtm, size/L

#675 fix: always configure the container runtime for GPU in an N series context
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesbase.t
  pkg/engine/armvariables.go
Labels: approved, lgtm, size/S

#739 test: don't hardcode base 64 encoded script values part 2
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
Labels: approved, size/M

#740 style: enable unnecessary type conversion linter
  .golangci.yml
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/apiloader_test.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/engine.go
  pkg/engine/template_generator.go
  pkg/helpers/filesaver.go
  test/aks-engine-test/main.go
Labels: approved, lgtm, size/M

#743 test: add unit tests for pkg/api/LoadDefaultContainerServiceProperties()
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
Labels: approved, lgtm, size/M

#742 fix: bug fix for master VMSS scenario in no_template flows
  pkg/engine/armresources_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/L

#744 fix: add err!=nil check when loading an ARM template during scale ops
  cmd/scale.go
Labels: approved, lgtm, size/XS

#745 fix: correct typo in err message in scale when unmarshaling ARM params
  cmd/scale.go
Labels: approved, lgtm, size/XS

#714 feat: windows agentpool support for AKS
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/L

#752 docs: update docs for NVIDIA driver version
  docs/topics/gpu.md
Labels: size/XS

#628 test: add node label and annotation validation
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/workloads/nginx-master.yaml
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/L

#660 docs: add how to install aks-engine with Chocolatey
  docs/tutorials/quickstart.md
Labels: approved, area/docs, lgtm, size/XS

#757 fix: fix the typo in the scale cmd logs
  cmd/scale.go
Labels: approved, lgtm, size/XS

#759 style: add some golint style simplications to validate.go
  pkg/api/vlabs/validate.go
Labels: approved, lgtm, size/S

#751 test: more apiloader unit tests
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/M

#747 fix: removed unnecessary elb artifacts when PrivateCluster is enabled
  pkg/engine/artifacts.go
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/XS

#681 feat: only allow “strong” TLS cipher suites by default
  pkg/api/const.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
Labels: approved, size/M

#749 chore: update cluster-autoscaler versions
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#763 revert: remove systemd/xenial-proposed install
  packer/install-dependencies.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
Labels: approved, lgtm, size/S

#669 docs: updating instructions on how to use Azure Cosmos DB etcd API
  docs/static/img/cosmos-etcd-account.png
  examples/cosmos-etcd/readme.md
Labels: lgtm, size/M

#756 chore: enable Kubernetes v1.14.0-beta.2
  pkg/api/common/versions.go
Labels: approved, size/XS

#769 fix: add changes to allow for scaling of VMSS nodes in no_template refactor
  cmd/scale.go
Labels: approved, lgtm, size/S

#770 Revert "fix: set nodes to panic and reboot on oom (#503)"
  parts/k8s/kubernetesagentcustomdata.yml
Labels: lgtm, size/S

#772 style: add godoc to the armtype structs used in the template refactor
  pkg/engine/armtype.go
Labels: approved, size/S

#771 fix: actually apt-mark hold walinuxagent during all CSE runs
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
Labels: approved, size/M

#778 fix: mark walinux for hold in cloud-init
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, lgtm, size/M

#779 test: add more unit tests for no_template refactor
  pkg/engine/armresources.go
  pkg/engine/armresources_test.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/XL

#782 fix: fix bugs in jumpbox custom data generations and add more unit tests to engine package
  pkg/engine/armresources_test.go
  pkg/engine/customfiles_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/XL

#787 test: add unit tests for engine.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
Labels: approved, lgtm, size/L

#780 chore: Include billing extensions for AzureUSGovernmentCloud
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#792 chore: update go toolchain to 1.12.1
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#223 feat: add support for Ubuntu 18.04-LTS
  .pipelines/vhd-builder.yaml
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/agentparams.t
  parts/k8s/kubernetesinstalls.sh
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  releases/vhd-notes/aks-ubuntu-1804-201901_2019.03.08.txt
Labels: approved, lgtm, size/L

#777 fix: move /var/log/ during VHD build to a vhd specific directory
  packer/cleanup-vhd.sh
Labels: approved, size/XS

#794 chore: update AKS distro version to 2019.03.15
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604-201903_2019.03.15.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine_2019.03.15.txt
Labels: approved, lgtm, size/L

#796 fix: Bug fixes for the HostedMasterProfile Scenario
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/virtualnetworks.go
  pkg/engine/virtualnetworks_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#800 fix: add missing parameter ComputerNamePrefix for VMSS agents using Windows
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/S

#801 test: add tests for pkg/engine/engine.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
Labels: approved, size/L

#638 feat: update Azure-NPM to support new network policy specifications
  packer/install-dependencies.sh
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/namespace/namespace.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/policies/backend-policy-allow-ingress-pod-label.yaml
  test/e2e/kubernetes/workloads/policies/backend-policy-allow-ingress-pod-namespace-label.yaml
  test/e2e/kubernetes/workloads/policies/backend-policy-deny-ingress.yaml
  test/e2e/kubernetes/workloads/policies/client-one-deny-egress-policy.yaml
  test/e2e/kubernetes/workloads/policies/client-one-deny-ingress-policy.yaml
Labels: approved, do-not-merge/hold, lgtm, size/L

#748 style: refactorings suggested by the gocritic linter
  cmd/get_versions.go
  cmd/orchestrators.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/orchestrators.go
  pkg/api/strictjson_test.go
  pkg/api/types.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/utils/util.go
  pkg/engine/armvariables.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/params.go
  test/e2e/config/config.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/metrics/metrics.go
Labels: approved, lgtm, size/L

#793 chore: enable Kubernetes v1.14.0-rc.1
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#810 docs: Fix language on upgrade.md
  docs/topics/upgrade.md
Labels: approved, lgtm, size/XS

#785 fix: rehabilitate constant generator script
  Makefile
  pkg/api/types_test.go
  pkg/engine/armvariables_test.go
  pkg/helpers/Get-AzureConstants.py
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/generate_azure_constants.py
  scripts/azure-const.sh
Labels: approved, lgtm, size/L

#814 fix: add nil checks for more resilience in template refactor
  pkg/engine/armresources.go
Labels: approved, lgtm, size/XS

#811 test: enforce --image-pull-policy=IfNotPresent for windows deployment…
  test/e2e/kubernetes/deployment/deployment.go
Labels: approved, size/XS

#816 fix: add more kubernetesConfig nil checks to account for more resilience
  pkg/engine/armvariables.go
  pkg/engine/masterarmresources.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/L

#812 fix: remove shell output from VHD release notes
  packer.mk
Labels: approved, lgtm, size/XS

#822 fix: add extra nil guard checks for LinuxProfiles
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/masterparams.t
  pkg/engine/networkinterfaces.go
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/M

#826 test: wait the regular, configurable time for dns-liveness pod readiness
  test/e2e/kubernetes/kubernetes_test.go
Labels: size/XS

#824 fix: add nil checks before accessing the service principal profile
  pkg/engine/params_k8s.go
Labels: approved, lgtm, size/M

#815 test: add test case for assignDefaultAddonVals to deal with nil Enabled property
  pkg/api/defaults_test.go
Labels: approved, size/M

#825 style: fix go_vet issues in the code
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/S

#828 fix: perform more nil guard checks against LinuxProfile
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/masterparams.t
  pkg/engine/template_generator.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, size/L

#821 test: fix NetworkPolicy tests for pre-1.11 cluster configurations
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/namespace/namespace.go
Labels: approved, size/M

#831 style: use errors.Errorf instead of fmt.Errorf as it's more idiomatic
  cmd/get_versions.go
  cmd/version.go
  pkg/api/vlabs/validate.go
  pkg/operations/kubernetesupgrade/upgrader.go
  test/e2e/kubernetes/util/util.go
Labels: approved, lgtm, size/S

#682 feat: enable new template generation implementation
  cmd/deploy.go
  cmd/generate.go
  cmd/scale.go
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, size/XXL

#857 fix: increase timeout tolerance for nvidia drivers installation
  parts/k8s/kubernetesconfigs.sh
Labels: approved, lgtm, size/XS

#859 style: fix some linting issues in api/validate
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#863 style: remove unused constants
  pkg/engine/const.go
  pkg/engine/engine.go
Labels: approved, lgtm, size/S

#860 fix: change blobfuse-flexvol-installer imagePullPolicy to IfNotPresent
  parts/k8s/containeraddons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
Labels: approved, lgtm, size/XS

#832 feat: AKS-Engine Install Script for Linux
  docs/tutorials/quickstart.md
  scripts/get-akse.sh
Labels: approved, lgtm, size/L

#865 style: use constants consistently in pkg/api
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults_test.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/L

#862 fix: fix sshd logging to auth.log for OMS
  parts/k8s/kubernetesconfigs.sh
Labels: approved, lgtm, size/XS

#871 fix: add missing right paren in ARM expression
  pkg/engine/systemroleassignments.go
  pkg/engine/systemroleassignments_test.go
Labels: approved, lgtm, size/XS

#872 feat: add support for Kubernetes 1.12.7
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#874 feat: add support for Kubernetes 1.13.5
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#873 feat: add support for Kubernetes 1.11.9
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/S

#829 docs: how to create a new aks-engine release
  docs/community/release-checklist.md
  docs/static/img/attach_archives.png
  docs/static/img/draft_new_release.png
  docs/static/img/release_notes.png
Labels: approved, area/docs, lgtm, size/L

#876 feat: add support for Kubernetes 1.14.0
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#830 fix: restore back-compat for clusters that have an older --audit-poli…
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
Labels: approved, size/S

#864 test: add unit tests to the api package
  pkg/api/apiloader_test.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
Labels: approved, lgtm, size/XXL

#885 fix: use our own hpa-example image
  examples/hpa-example/Dockerfile
  examples/hpa-example/index.php
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#882 fix: address regressions from v2 template refactor
  pkg/engine/keyvaults.go
  pkg/engine/keyvaults_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/S

#884 chore: enable 2019.03.25 VHD image
  parts/k8s/kubernetescustomscript.sh
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604-201903_2019.03.25.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine_2019.03.25.txt
  releases/vhd-notes/aks-ubuntu-1804-201901_2019.03.25.txt
Labels: approved, lgtm, size/L

#886 fix: user contributor role for Master VMAS role assignments
  pkg/engine/systemroleassignments.go
  pkg/engine/systemroleassignments_test.go
Labels: approved, lgtm, size/XS

#880 fix: use --dns-prefix for output directory when running deploy command
  cmd/deploy.go
  cmd/deploy_test.go
Labels: approved, lgtm, size/M

#893 refactor: put each version on its own line in VHD script
  packer/install-dependencies.sh
Labels: approved, lgtm, size/L, ¯\_(ツ)_/¯

#894 chore: update CNI plugin to v0.7.5
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, size/XS

#895 chore: remove Kubernetes 1.10 from e2e testing
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/S

#898 ci: remove CircleCI end-to-end test support
  .circleci/config.yml
  test/e2e/metrics/metrics.go
Labels: approved, lgtm, size/L

#888 chore: remove tariq1890 from the OWNERS list
  OWNERS
Labels: approved, lgtm, size/XS

#890 feat: remove dependency on deployment-dir for scale/upgrade
  cmd/scale.go
  cmd/scale_test.go
  cmd/upgrade.go
  cmd/upgrade_test.go
  docs/topics/scale.md
  docs/topics/upgrade.md
  docs/tutorials/day2-operations.md
  examples/azure-cni/k8s-scale.sh
  examples/k8s-upgrade/k8s-upgrade.sh
  examples/multiple-nodepools/README.md
Labels: lgtm, size/L

#903 chore: update VHD image to 2019.03.27
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604-docker-engine/aks-ubuntu-1604-docker-engine_2019.03.05.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine/aks-ubuntu-1604-docker-engine_2019.03.15.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine/aks-ubuntu-1604-docker-engine_2019.03.25.txt
  releases/vhd-notes/aks-ubuntu-1604-docker-engine/aks-ubuntu-1604-docker-engine_2019.03.27.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201903_2019.03.05.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201903_2019.03.15.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201903_2019.03.25.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201903_2019.03.27.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201901_2019.03.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201901_2019.03.25.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201901_2019.03.27.txt
Labels: approved, lgtm, size/L

#909 fix: remove packer user
  parts/k8s/kubernetescustomscript.sh
Labels: approved, lgtm, size/XS

#914 fixed typo
  docs/tutorials/quickstart.md
Labels: size/XS

#915 docs: Cleaned up examples
  docs/topics/windows.md
Labels: lgtm, size/XS

#917 docs: rename local download script name to match remote
  docs/tutorials/quickstart.md
Labels: approved, area/docs, lgtm

#916 chore: use V1beta1 Policy client, not the deprecated default
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/kubeclient.go
Labels: approved, lgtm, size/XS

#870 perf: improve CSE script
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, lgtm, size/L

#911 fix: ip-masq-agent container image has a different repo base in VHD
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS
