Repository Azure/aks-engine, pull requests merged in 2019-04, with the labels that each got.

#921 Added Kubernetes 1.13
  examples/kubernetes-releases/kubernetes1.13.json
Labels: lgtm, size/M

#922 fix : prometheus-grafana extension : cAdvisor deployment is not namespaced
  extensions/prometheus-grafana-k8s/v1/prometheus-grafana-k8s.sh
Labels: lgtm, size/XS

#924 chore: ensure AKS gets proper Windows billing extension
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#912 perf: Network Monitor v0.0.6 integration
  packer/install-dependencies.sh
  parts/k8s/containeraddons/azure-cni-networkmonitor.yaml
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/M

#454 chore: Update calico to 3.5 and allow calico to work with azure CNI
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/api/addons.go
  pkg/engine/const.go
Labels: do-not-merge/hold, lgtm, size/XXL

#918 feat: default to k8s 1.14 for Windows and 1.12 for Linux
  .pipelines/pr-e2e.yaml
  pkg/api/common/const.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/S

#929 Removed dead links
  examples/windows/README.md
Labels: lgtm, size/XS

#925 docs: generate all shasum strings with a one-liner
  docs/community/release-checklist.md
Labels: approved, lgtm, size/XS

#900 fix: AKS VMSS windows agent pool upgrade
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/engine/transform/transform.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/L

#928 chore: update Azure CNI version to v1.0.18
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#931 test: skip dns-liveness restarts check for k8s 1.14
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#901 fix: include vnet CIDR in windows node CNI outbound NAT exception list
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
Labels: approved, lgtm, size/XS

#927 fix: #926 Escape servicePrincipalClientSecret in Windows custom script block
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/XS

#936 docs: fix reference to large cluster api model
  examples/largeclusters/README.md
Labels: approved, area/docs, lgtm, size/S

#937 revert: improve CSE script
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, do-not-merge/hold, lgtm, size/L

#939 test: remove hard-coded k8s version from armvars tests
  pkg/engine/armvariables_test.go
Labels: approved, area/test, lgtm, size/S

#942 docs: re-add windows binaries doc link
  examples/windows/README.md
Labels: approved, lgtm, size/XS

#938 fix: increase cordon/drain timeout to 20 mins during upgrade
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#897 feat: enable nvidia drivers on moby-backed VMs, deprecate docker-engine entirely
  docs/topics/clusterdefinitions.md
  docs/topics/gpu.md
  packer/install-dependencies.sh
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  test/e2e/kubernetes/workloads/nvidia-smi.yaml
Labels: approved, gpu, lgtm, size/XL

#943 fix: zones values for VMAS masters is an array of a single string
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
Labels: approved, lgtm, size/XS

#945 test: use managed-standard storage class for pvc test
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/pvc-standard.yaml
Labels: approved, size/XS

#934 test: unit test for azure stack AzureClient
  Gopkg.lock
  Gopkg.toml
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/azurestack/converter_test.go
  pkg/armhelpers/azurestack/deployment_test.go
  pkg/armhelpers/azurestack/disk_test.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/armhelpers/azurestack/httpMockClientData/deploymentVMError.json
  pkg/armhelpers/azurestack/httpMockClientData/getVirtualMachine.json
  pkg/armhelpers/azurestack/httpMockClientData/listVirtualMachineScaleSetVMs.json
  pkg/armhelpers/azurestack/httpMockClientData/listVirtualMachineScaleSets.json
  pkg/armhelpers/azurestack/httpMockClientData/listVirtualMachines.json
  pkg/armhelpers/azurestack/httpMockClientData/tokenResponse.json
  pkg/armhelpers/azurestack/network_test.go
  vendor/gopkg.in/jarcoal/httpmock.v1/LICENSE
  vendor/gopkg.in/jarcoal/httpmock.v1/doc.go
  vendor/gopkg.in/jarcoal/httpmock.v1/env.go
  vendor/gopkg.in/jarcoal/httpmock.v1/response.go
  vendor/gopkg.in/jarcoal/httpmock.v1/transport.go
Labels: approved, size/XXL

#946 fix: fix disable rbac + enable aggregated API upgrade bug
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#948 chore: enable 2019.04.03 VHD versions
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.03.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.03.txt
Labels: approved, lgtm, size/L

#941 ci: add timestamp to artifact names
  .pipelines/e2e-step-template.yaml
Labels: approved, lgtm, size/XS

#949 fix: mount tmp emptyDir to stop CoreDNS restarts
  parts/k8s/addons/coredns.yaml
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, area/test, do-not-merge/hold, size/XS

#952 chore: only use new calico CSE config for AKS Engine
  parts/k8s/kubernetesconfigs.sh
Labels: approved, size/S

#954 style: remove extra pullContainerImage command
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#955 refactor: avoid shell globbing
  scripts/azure-const.sh
Labels: approved, lgtm, size/XS

#951 fix: handle uppercase letters in VM names in upgrade
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrademasternode.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/M

#957 style: use shellcheck to validate some scripts
  Makefile
  scripts/azure-const.sh
  scripts/build-windows-k8s.sh
  scripts/convert-lcg-lcl.sh
  scripts/copyright-header.sh
  scripts/coverage.sh
  scripts/devenv.ps1
  scripts/ensure-generated.sh
  scripts/get-akse.sh
  scripts/get-kubectl.sh
  scripts/ginkgo.coverage.sh
  scripts/update-enus-po.sh
  scripts/update-translation.sh
  scripts/validate-commit-msg.sh
  scripts/validate-copyright-header.sh
  scripts/validate-dependencies.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/L

#958 feat: add support for Kubernetes 1.14.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#959 chore: update go toolchain to 1.12.2
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#960 chore: combine all cloud-init vars into one
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/XL

#969 docs: use "make info" as preflight release check
  docs/community/release-checklist.md
Labels: approved, area/docs, lgtm, size/XS

#920 chore: rev the nvidia driver version for the newer driver
  docs/topics/gpu.md
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, do-not-merge/hold, gpu, lgtm, size/XS

#947 feat: retrieve endpoints from metadata endpoint for Azure Stack
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: approved, lgtm, size/XXL

#966 test: add ubuntu 18.04 job to pr-e2e
  .pipelines/pr-e2e.yaml
  examples/ubuntu-1804/kubernetes.json
Labels: approved, lgtm, size/M

#972 chore: add CIS script interface
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cis.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/customscripts.go
Labels: approved, lgtm, size/M

#989 chore: enable 2019.04.08 VHD versions
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.08.txt
Labels: approved, lgtm, size/L

#995 feat: enable calico 3.5 for AKS
  parts/k8s/kubernetesconfigs.sh
Labels: approved, lgtm, size/S

#1000 docs: fix a command
  examples/kubernetes-zones/README.md
Labels: lgtm, size/XS

#998 refactor: move isPrivateCluster to types.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armoutputs.go
  pkg/engine/armvariables.go
  pkg/engine/masterarmresources.go
  pkg/engine/storageaccounts.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#1003 docs: add documentation for ACC agent pools running Ubuntu 18.04
  docs/topics/sgx.md
  parts/k8s/kubernetescustomscript.sh
Labels: approved, lgtm, size/S

#997 refactor: return error instead of invoking log.Fatal
  cmd/root.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/azurestack/compute.go
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/azurestack/deployment_test.go
  pkg/armhelpers/azurestack/disk_test.go
  pkg/armhelpers/azurestack/graph.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/msi.go
  pkg/armhelpers/azurestack/network_test.go
  pkg/armhelpers/azurestack/resultPageClient.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#996 refactor: re-organize cloud-init files and implementation
  docs/howto/troubleshooting.md
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/apt-preferences
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/docker-monitor.service
  parts/k8s/cloud-init/artifacts/docker-monitor.timer
  parts/k8s/cloud-init/artifacts/docker_clear_mount_propagation_flags.conf
  parts/k8s/cloud-init/artifacts/etcd.service
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  parts/k8s/cloud-init/artifacts/kms.service
  parts/k8s/cloud-init/artifacts/kubelet-monitor.service
  parts/k8s/cloud-init/artifacts/kubelet-monitor.timer
  parts/k8s/cloud-init/artifacts/kubelet.service
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  parts/k8s/cloud-init/artifacts/sshd_config
  parts/k8s/cloud-init/artifacts/sys-fs-bpf.mount
  parts/k8s/cloud-init/artifacts/system.conf
  parts/k8s/cloud-init/jumpboxcustomdata.yml
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/customfiles.go
  pkg/engine/customscripts.go
  pkg/engine/engine.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/XL

#1006 fix: GetKubernetesB64ConfigsCustomCloud rebase errata
  pkg/engine/armvariables.go
Labels: approved, size/XS

#1005 test: add --feature-gates tests
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/mocks.go
Labels: approved, lgtm, size/M

#977 chore(CIS): add streaming-connection-idle-timeout
  pkg/api/defaults-kubelet.go
Labels: approved, lgtm, size/M

#1024 chore(CIS): ensure local login warning banner is configured properly
  parts/k8s/cloud-init/artifacts/etc-issue
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/customscripts.go
Labels: approved, size/S

#892 feat: revive CoreOS support
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/coreos/coreos.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/addons.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
Labels: approved, lgtm, size/L

#1007 chore: run apt-get dist-upgrade during VHD or for base OS image distro
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
Labels: approved, size/S

#1013 chore(CIS): assign root pw
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/types.go
  pkg/api/types_test.go
  test.mk
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/util/util.go
Labels: approved, cis-benchmark, size/XL

#1036 refactor: remove engine pkg custom script unnecessary functions
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/customscripts.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#1038 fix: fix generate command for Azure Stack
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#678 feat: TLS certificate rotation
  cmd/deploy_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/rotate_certs.go
  cmd/rotate_certs_test.go
  cmd/scale.go
  cmd/upgrade.go
  docs/design/cert-rotation.md
  docs/topics/certificaterotation.md
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/armhelpers/azurestack/compute.go
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/compute.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, awaiting review, lgtm, size/XXL

#1031 chore(CIS): Ensure permissions on all log files are configured
  packer/cleanup-vhd.sh
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cis.sh
Labels: approved, awaiting review, cis-benchmark, lgtm, size/M

#1043 fix: only run installDeps in non-VHD scenarios
  parts/k8s/cloud-init/artifacts/cse_main.sh
Labels: approved, lgtm, size/XS

#1039 chore(CIS): CIS network configuration enforcement
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/sysctl-d-60-CIS.conf
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/net-config-validate.sh
  test/e2e/remote/ssh.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#1053 fix: handle multiple masters for Azure Stack
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/S

#1045 test: ensure node is ready before running validations
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, lgtm, size/L

#1057 chore: backport tests + cloud-init usage for CIS changes
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/M

#1042 chore: remove comments from cilium addons spec
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
Labels: approved, size/L

#1059 fix: fix parameter name for ScaleSetEvictionPolicy
  pkg/engine/armvariables.go
Labels: approved, lgtm, size/XS

#1028 fix: Windows + VMSS external svc routing broken
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/M

#1037 chore(CIS): Ensure remote login warning banner is configured properly
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/etc-issue.net
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/M

#1062 fix: error handling in CIS bash script
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
Labels: approved, lgtm, size/S

#1069 fix: no longer need 1.12 kubelet start workaround
  parts/k8s/cloud-init/artifacts/cse_config.sh
Labels: approved, lgtm, size/XS

#1061 chore(CIS): enforce CIS modprobe recommendations
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/modprobe-CIS.conf
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/modprobe-config-validate.sh
Labels: approved, lgtm, size/M

#1073 fix: make conntrack more liberal on packets
  parts/k8s/cloud-init/artifacts/kubelet.service
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, lgtm, size/S

#1063 chore(CIS): add apt package validation, ensure postfix is not present
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
Labels: approved, lgtm, size/M

#1071 docs: clarify help for --api-model arguments
  cmd/deploy.go
  cmd/generate.go
  cmd/rotate_certs.go
  cmd/scale.go
  cmd/upgrade.go
  docs/topics/scale.md
  docs/topics/upgrade.md
Labels: approved, area/docs, lgtm, size/S

#1082 test: add nodes.GetReady() method for E2E tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, lgtm, size/L

#1030 chore(CIS): ensure /etc/ssh/sshd_config is configured
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/sshd_config
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/sshd-config-validate.sh
Labels: approved, cis-benchmark, lgtm, size/L

#1093 revert: "fix: make conntrack more liberal on packets"
  parts/k8s/cloud-init/artifacts/kubelet.service
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, lgtm, size/S

#1081 chore(CIS): Ensure logging is configured
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/rsyslog-d-60-CIS.conf
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/M

#1095 revert: JoinControllers system.conf configuration
  parts/k8s/cloud-init/artifacts/system.conf
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
Labels: approved, size/S

#1080 test: add ubuntu time sync E2E validation
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/time-sync-validate.sh
Labels: approved, lgtm, size/M

#1035 chore(CIS): Ensure password creation requirements are configured
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/pwquality-CIS.conf
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
  test/e2e/kubernetes/scripts/pwquality-validate.sh
Labels: approved, cis-benchmark, lgtm, size/L

#1087 feat: support VMSS agent nodes with public IP.
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#1083 test: single host OS DNS test script
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/host-os-dns-validate.sh
Labels: approved, lgtm, size/L

#1097 ci: Add alert on VHD space greater than 75%
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#1102 chore: always ensure apt runs non-interactively
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
Labels: approved, lgtm, size/XS

#1105 chore(CIS): kernel module hardening for non-essential filesystem types
  parts/k8s/cloud-init/artifacts/modprobe-CIS.conf
  test/e2e/kubernetes/scripts/modprobe-config-validate.sh
Labels: approved, size/S

#1106 chore(CIS): harden grub.cfg file permissions
  parts/k8s/cloud-init/artifacts/cis.sh
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/XS

#1107 test: disable coreos scenario as PR E2E gate
  .pipelines/pr-e2e.yaml
Labels: approved, size/XS

#1094 test: check net.ipv4.tcp_retries2 kernel parameter
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, area/test, do-not-merge/hold, lgtm, size/XS

#1040 feat: pre-pull Azure Stack's custom Hyperkube
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/M

#1098 fix: use the actual pool index in the VM prefix for windows scale operations
  cmd/scale.go
  docs/topics/scale.md
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/utils/util.go
  pkg/engine/armvariables.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/M

#1103 feat: enable WindowsProfile in defaults enforcement code flow
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L

#1110 style: remove unneeded nil check
  pkg/api/converterfromagentpoolonlyapi.go
Labels: approved, lgtm, size/XS

#1114 chore: add newlines to login banner message
  parts/k8s/cloud-init/artifacts/etc-issue
  parts/k8s/cloud-init/artifacts/etc-issue.net
Labels: approved, lgtm, size/XS

#1113 chore: add two missing /var/log files for 18.04 in CIS script
  parts/k8s/cloud-init/artifacts/cis.sh
Labels: approved, lgtm, size/XS

#1111 chore(CIS): grub configuration changes to accommodate CIS
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/default-grub
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, size/M

#1112 chore(CIS): ensure su is restricted
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/pam-d-su
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, size/M

#1121 test: only test Ready nodes for DNS
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#1117 test: fallback google.com check for Windows outbound test
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#1122 docs: add makedev.ps1 to doc
  docs/community/developer-guide.md
Labels: approved, area/docs, lgtm, size/XS

#1120 fix: restores cosmosDB etcd functionality after template generation r…
  pkg/engine/cosmosdb.go
  pkg/engine/cosmosdb_test.go
Labels: approved, lgtm, size/S

#1124 docs: fix IPs per vnet limit documented
  docs/topics/features.md
Labels: size/XS

#1126 chore: disable --pod-max-pids by default
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#1129 chore: clean up containerd and cc-runtime when unused
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
Labels: approved, lgtm, size/S

#1076 feat: grant user assigned identity 'Reader' role for hosted cluster
  pkg/engine/armresources.go
  pkg/engine/roleassignments.go
  pkg/engine/roleassignments_test.go
Labels: approved, size/M

#1127 chore: reduce cloud-init var overhead for VHD scenarios
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/XL

#1131 fix: /etc/default/grub VHD enforcement
  parts/k8s/cloud-init/artifacts/cis.sh
Labels: approved, lgtm, size/XS

#1130 fix: enable VHD enforcement of /etc/pam.d/su
  parts/k8s/cloud-init/artifacts/cis.sh
Labels: approved, size/XS

#1132 fix: set correct master FQDN for Azure Stack
  parts/k8s/cloud-init/nodecustomdata.yml
Labels: approved, lgtm, size/XS

#1128 chore(CIS): set umask to 027 for ubuntu
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/profile-d-cis.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/M

#1116 chore(CIS): pam.d password enforcement
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/pam-d-common-auth
  parts/k8s/cloud-init/artifacts/pam-d-common-password
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, size/L

#1136 fix: replace \t with nothing
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
Labels: size/XS

#1138 feat: add support for Kubernetes 1.12.8
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1141 chore: stop delivering unused kubelet systemd timer script via cloud-init
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
Labels: approved, size/S

#1147 style: comment out unused constant
  pkg/engine/const.go
Labels: approved, size/S

#1137 docs: Add guides for calico cleanup after upgrading to v3.5
  docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml
  docs/topics/features.md
Labels: size/XL

#1101 chore: update Azure VM sizes
  pkg/engine/armvariables_test.go
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#1133 fix: implement extensions with template refactor
  docs/topics/extensions.md
  extensions/choco/v1/template-link.json
  extensions/choco/v1/template.json
  extensions/hello-world-k8s/v1/template-link.json
  extensions/hello-world-k8s/v1/template.json
  extensions/microsoft-oms-agent-k8s/v1/template-link.json
  extensions/microsoft-oms-agent-k8s/v1/template.json
  extensions/prometheus-grafana-k8s/v1/template-link.json
  extensions/prometheus-grafana-k8s/v1/template.json
  extensions/windows-patches/v1/template-link.json
  extensions/windows-patches/v1/template.json
  extensions/winrm/v1/template-link.json
  extensions/winrm/v1/template.json
  pkg/engine/armtype.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine.go
  pkg/engine/masterarmresources.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#999 chore(CIS): add protect-kernel-defaults
  parts/k8s/cloud-init/artifacts/sysctl-d-60-CIS.conf
  pkg/api/const.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, lgtm, size/M

#1151 fix: clean generated and unit test helper files
  Makefile
Labels: approved, lgtm, size/XS

#1148 style: remove literal carriage returns and lint all shell scripts
  extensions/hello-world-k8s/v1/hello-world-k8s.sh
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  parts/k8s/cloud-init/artifacts/profile-d-cis.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/L

#1145 feat: Support existing load balancer backend address pool for agent nodes
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: size/L

#1142 feat: static pods use custom hyperkube on az stack
  packer/install-dependencies.sh
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
Labels: approved, azurestack, lgtm, size/S

#1154 style: use 'true' instead of '[ 1 ]' in shell loops
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  scripts/validate-shell.sh
Labels: approved, lgtm, size/XS

#1144 feat: pre-pull Pause from Azure Stack's docker repo
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/S

#1155 fix: add UDP Standard LB rule to enable outbound access
  parts/k8s/addons/kubernetesmasteraddons-elb-svc.yaml
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
Labels: approved, lgtm, size/L

#1160 ci: exclude some test files from coverage report
  .codecov/codecov.yml
Labels: approved, lgtm, size/XS

#1163 style: remove literal carriage returns and enable parser errors
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  scripts/validate-shell.sh
Labels: approved, lgtm, size/L

#1157 fix: use cordon/drain timeout for pod eviction timeout during upgrade
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#1159 style: add bash shebangs to scripts
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/profile-d-cis.sh
  scripts/validate-shell.sh
  test/cluster-tests/kubernetes/k8s-utils.sh
  test/cluster-tests/utils.sh
Labels: approved, lgtm, size/S

#1162 chore(CIS): password expiration, cron file mode enforcement
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
  test/e2e/kubernetes/scripts/pwquality-validate.sh
Labels: approved, lgtm, size/M

#1052 chore(CIS): add rotate kubelet certs flag
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/XS

#1165 chore: enable 2019.04.24 VHD images
  pkg/api/azenvtypes.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#1161 test: use master branch as root URL in extensions unit test
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/S

#1166 style: use "-n" instead of "! -z" in shell scripts
  examples/azure-cni/k8s-scale.sh
  examples/k8s-upgrade/k8s-upgrade.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  scripts/k
  scripts/validate-shell.sh
  test/cluster-tests/kubernetes/k8s-utils.sh
  test/cluster-tests/kubernetes/test.sh
  test/cluster-tests/utils.sh
  test/common.sh
  test/deploy.sh
  test/e2e.sh
  test/step.sh
Labels: approved, lgtm, size/L

#1171 style: the shebang must be on the first line
  extensions/hello-world-k8s/v1/hello-world-k8s.sh
  extensions/hello-world/v1/hello.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, awaiting review, lgtm, size/S

#1175 fix: --rotate-certificates failing in k8s versions prior to 1.11
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, size/M

#1170 style: use #!, not just #, for the shebang
  pkg/engine/testdata/rename.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, awaiting review, size/XS

#1174 fix: #926 - Base64 encode sp password
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: do-not-merge/hold, size/XS

#1173 fix: delete vm if node is not ready after upgrade.
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
Labels: approved, lgtm, size/XS

#1140 feat: add support for Kubernetes v1.15.0-alpha.1
  .pipelines/pr-e2e.yaml
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, awaiting review, lgtm, size/M

#1135 feat(aks): expose unversioned orchestrator version profile to better …
  pkg/api/converterfromapi.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
Labels: approved, lgtm, size/S

#1167 style: use { cmd1; cmd2 } >> file instead of individual redirects
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/M

#1150 ci: return error if Go linter can't compile source code
  .golangci.yml
  .pipelines/pr-e2e.yaml
  pkg/engine/loadbalancers.go
  scripts/validate-go.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/M

#1182 chore: add 2019.04.24 VHD release notes
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.24.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.24.txt
Labels: approved, size/L

#1176 ci: exclude a test mock file from coverage report
  .codecov/codecov.yml
Labels: approved, area/ci, lgtm, size/XS

#1178 feat: add support for Kubernetes v1.15.0-alpha.2
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1183 fix: kubeconfig enforcement via kubelet.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
Labels: approved, size/XS

#1180 style: use $(...) shell notation instead of legacy backticks
  examples/vnet/dual-subnet-vnet-predeploy.sh
  examples/vnet/k8s-vnet-azure-cni-predeploy.sh
  examples/vnet/k8s-vnet-predeploy.sh
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  packer/init-variables.sh
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  pkg/engine/armvariables_test.go
  scripts/validate-shell.sh
  test/common.sh
  test/e2e/cleanup.sh
  test/e2e/kubernetes/scripts/modprobe-config-validate.sh
Labels: approved, lgtm, size/L
