Repository Azure/aks-engine, pull requests merged in 2019-02, with the labels that each got.

#413 feat: add the aksEngineVersion tag
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, lgtm, size/XS

#421 chore: add commit message categories to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#410 revert: JoinControllers system.conf override
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/system.conf
  pkg/engine/const.go
  pkg/engine/template_generator.go
Labels: approved, size/S

#415 ci: always collect logs in pipeline
  .pipelines/e2e-step-template.yaml
Labels: approved, lgtm, size/XS

#396 chore: increase auto-generated cert expiration to 30 years
  pkg/helpers/pki.go
Labels: approved, size/XS

#428 refactor: Remove agentpool index usage from function which gets agent VM name
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/S

#423 chore: per-agent pool k8s versions and provisioning state
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/compute.go
Labels: approved, lgtm, size/M

#407 feat: make Moby version configurable
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/params_k8s.go
Labels: approved, awaiting review, lgtm, size/M

#436 docs: refer to the project as "AKS Engine" consistently
  .github/config.yml
  CONTRIBUTING.md
  README.md
  cmd/root.go
  docs/README.md
  docs/community/README.md
  docs/community/developer-guide.md
  docs/faq.md
  docs/howto/README.md
  docs/howto/kubernetes-large-clusters.md
  docs/howto/troubleshooting.md
  docs/topics/README.md
  docs/topics/architecture.md
  docs/topics/extensions.md
  docs/topics/monitoring.md
  docs/topics/upgrade.md
  docs/tutorials/README.md
  docs/tutorials/containermonitoringaddon.md
  docs/tutorials/custom-vnet.md
  docs/tutorials/quickstart.md
  examples/README.md
  examples/addons/container-monitoring/README.md
  examples/customfiles/README.md
  examples/disks-managed/README.md
  examples/disks-storageaccount/README.md
  examples/keyvault-params/README.md
  examples/keyvaultcerts/README.md
  examples/kubernetes-config/README.md
  examples/largeclusters/README.md
  examples/multiple-nodepools/README.md
  examples/networkplugin/README.md
  examples/networkpolicy/README.md
  examples/vnet/README.md
  examples/windows/README.md
Labels: approved, lgtm, size/L

#438 docs: SGX support with Kubernetes
  docs/topics/README.md
  docs/topics/sgx.md
Labels: lgtm, size/M

#437 fix: reduce etcd download retries to avoid timeouts
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/XS

#441 docs: Fix CLI parameters
  docs/tutorials/deploy.md
Labels: lgtm, size/XS

#439 chore: Add agentpool resource(used for agentpool level operations) and UT
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm, size/M

#416 feat: update Azure CNI version to 1.0.17
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#447 fix: prevent race condition with docker/moby install
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/XS

#433 feat: Add ability to enable windows ssh with open ssh install on node
  docs/topics/clusterdefinitions.md
  examples/e2e-tests/kubernetes/windows/hybrid/definition.json
  examples/windows/kubernetes.json
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
Labels: lgtm, size/M

#301 docs: new quickstart guide
  docs/community/developer-guide.md
  docs/tutorials/README.md
  docs/tutorials/quickstart.md
Labels: approved, area/docs, lgtm, size/L

#456 feat: update VHD image to 2019.02.06
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#458 fix: containerd downloads every time
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/S

#460 feat: updated network monitor version to newer release v0.0.5
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#462 fix: Initialize data disks on Windows nodes
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsconfigfunc.ps1
Labels: size/XS

#464 fix: update kms container image
  packer/install-dependencies.sh
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: lgtm, size/XS

#449 build: commit generated code files
  .codecov/codecov.yml
  .gitignore
  .pipelines/pr-e2e.yaml
  Makefile
  pkg/engine/fileloader.go
  pkg/engine/templates_generated.go
  pkg/i18n/resourceloader.go
  pkg/i18n/translations_generated.go
  scripts/convert-lcg-lcl.sh
  scripts/update-enus-po.sh
Labels: approved, size/M

#465 fix: bump version for keyvault-flexvolume
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/defaults_test.go
Labels: lgtm, size/XS

#470 ci: keep static assets and generated in sync for PR #464
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#480 chore: update Moby version to 3.0.4
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#355 fix: Fail deployCmd when orchestrator version is invalid
  pkg/api/apiloader.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: lgtm, size/M

#482 feat: update VHD image to 2019.02.12
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#386 feat: Support dynamic AzureEnvironmentSpecConfig
  pkg/api/azenvtypes.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/engine.go
  pkg/engine/params.go
  pkg/engine/testdata/azurestack/kubernetes.json
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, lgtm, size/XXL

#476 set caching mode of data disks as ReadOnly by default
  pkg/engine/engine.go
Labels: size/XS

#485 ci: fix failing unit test in master
  pkg/api/convertertoapi_test.go
Labels: approved, lgtm, size/XS

#473 fix: specify "shared" for unmanaged disk class
  parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml
Labels: approved, lgtm, size/XS

#491 ci: use diff instead of git diff for the CI validation checks of the generated files
  Makefile
  pkg/engine/templates_generated.go
  scripts/validate-generated.sh
Labels: approved, size/M

#466 refactor: swap satori's uuid package to gofrs
  Gopkg.lock
  Gopkg.toml
  cmd/deploy_test.go
  cmd/root.go
  cmd/root_test.go
  pkg/api/mocks.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/graph.go
  pkg/operations/dcosupgrade/upgradecluster.go
  vendor/github.com/gofrs/uuid/LICENSE
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/fuzz.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/sql.go
  vendor/github.com/gofrs/uuid/uuid.go
Labels: approved, lgtm, size/XL

#492 fix: remove repair-malformed-updates deprecated flag
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
Labels: approved, lgtm, size/S

#497 feat: add support for Kubernetes 1.10.13
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#500 fix: remove the use of deprecated Next() method
  cmd/scale.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, lgtm, size/XS

#493 fix: upgrade blobfuse version for bug fix
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/defaults_test.go
Labels: lgtm, size/XS

#503 fix: set nodes to panic and reboot on oom
  parts/k8s/kubernetesagentcustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#448 feat: add "get-versions" command to replace "orchestrators"
  cmd/get_versions.go
  cmd/get_versions_test.go
  cmd/orchestrators.go
  cmd/root.go
  cmd/root_test.go
  cmd/upgrade.go
  docs/topics/clusterdefinitions.md
  docs/topics/upgrade.md
  docs/tutorials/quickstart.zh-CN.md
Labels: approved, lgtm, size/M

#510 docs: add a "code of conduct" file where GitHub can see it
  CODE_OF_CONDUCT.md
Labels: approved, area/docs, lgtm, size/M

#136 chore: deprecate kubernetes versions 1.8 and 1.7
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/mockclients.go
  pkg/engine/testdata/agentPoolOnly/v20170831/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agents.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfile.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfileV2.json
  pkg/engine/testdata/agentPoolOnly/v20180331/agentsWithOnlyNetworkPlugin.json
  pkg/engine/testdata/kubernetesversions/kubernetes1.10.9.json
  pkg/engine/testdata/kubernetesversions/kubernetes1.9.11.json
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  repro.json
Labels: approved, lgtm, size/M

#513 docs: clarify that `make ensure-generated` is a PR requirement
  .pipelines/pr-e2e.yaml
  CONTRIBUTING.md
  Makefile
  docs/community/developer-guide.md
  scripts/ensure-generated.sh
Labels: approved, area/ci, area/docs, lgtm, size/M

#505 feat: support dynamic region for azurestack
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/output_test.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: lgtm, size/XXL

#514 chore: update AKS VHD images to 2019.02.13
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#487 fix: do not create ELB for private clusters
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#524 fix: updated acs to aks
  docs/tutorials/custom-vnet.md
Labels: lgtm, size/S

#516 chore: install specific containerd version, make version configurable
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#523 feat: add support for private registry
  docs/topics/kubernetes-developers.md
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#521 doc: document storageProfile option for masterProfile
  docs/topics/clusterdefinitions.md
Labels: approved, size/XS

#486 fix: do not create route table when using flannel
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#526 fix: added defaultValue to accommodate missing privateAzureRegistryServer
  parts/k8s/kubernetesparams.t
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#508 feat(cilium) Add Cilium 1.4 support and improve deployment process
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/XXL

#535 feat: enable configurable --enforce-node-allocatable
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/S

#539 fix: add comma separation to bash variables in provisionScriptParametersCommon
  parts/k8s/kubernetesmastervars.t
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#529 fix: Allow to create only masters so that agents can be created at a later…
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmastervars.t
  pkg/engine/artifacts.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/mastersonly/mastersonly.json
Labels: size/L

#540 chore: fix HasZonesForAllAgentPools() for masters-only scenarios
  pkg/api/types.go
Labels: approved, size/S

#531 feat: support ADFS for azurestack
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastervars.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: approved, lgtm, size/L

#527 feat: add human-readable output option to "get-versions" command
  cmd/get_versions.go
  cmd/get_versions_test.go
  cmd/orchestrators.go
  cmd/orchestrators_test.go
  cmd/version.go
Labels: approved, area/cli, do-not-merge/hold, size/L

#543 test: wait longer between kubectl top nodes retries
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#538 fix: move the definition of inboundNatRules inside the loadbalancer specification
  parts/k8s/kubernetesmasterresources.t
  pkg/engine/templates_generated.go
Labels: approved, size/M

#550 fix: Updating Windows default Docker version from 18.09.0 to 18.09.2.
  examples/windows/kubernetes-windows-docker-version.json
  parts/windowsparams.t
  pkg/api/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#367 feat: enable vmss overprovision, do not run extensions on overprovisioned VMs
  docs/topics/clusterdefinitions.md
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#546 revert: commit generated code files
  .gitignore
  .pipelines/pr-e2e.yaml
  CONTRIBUTING.md
  docs/community/developer-guide.md
  pkg/engine/templates_generated.go
  pkg/i18n/translations_generated.go
Labels: approved, lgtm, size/XXL

#556 chore: ignore artifacts that may be present from prior commits
  .gitignore
Labels: approved, size/XS

#559 ci: ignore test files in code coverage
  .codecov/codecov.yml
Labels: approved, area/ci, lgtm, size/XS

#558 test: use "k" script to fetch the right kubectl just-in-time
  docs/community/developer-guide.md
  test/cluster-tests/kubernetes/k8s-utils.sh
  test/cluster-tests/kubernetes/test.sh
  test/common.sh
  test/e2e/kubernetes/config.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/namespace/namespace.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/persistentvolume/persistentvolume.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/kubernetes/storageclass/storageclass.go
  test/e2e/runner/cli_provisioner.go
  test/e2e/runner/ginkgo.go
Labels: approved, lgtm, size/L

#554 chore: add administration tools
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/XS

#560 test: wait longer when incrementing error count waiting for pod Ready
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#435 feat: enable 1.14.0-alpha.2 support
  pkg/api/common/versions.go
  pkg/api/defaults-apiserver.go
  test/e2e/kubernetes/workloads/dns-liveness.yaml
Labels: approved, lgtm, size/XS

#562 docs: add how to install aks-engine with Homebrew
  docs/tutorials/quickstart.md
Labels: approved, area/docs, lgtm, size/XS

#564 chore: apiserverCertificate should be apiServerCertificate
  parts/k8s/kubernetesmastervars.t
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
Labels: approved, size/S

#571 fix: silence `k` script
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  docs/community/developer-guide.md
  makedev.ps1
  scripts/k
Labels: approved, lgtm, size/M

#569 Fix: To enable downgrading Moby version from what has been pre-provisioned in the VHD Image
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/XS

#553 feat: Support ARM endpoint with non-trusted certificate
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesconfigscustomcloud.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  pkg/api/defaults.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: lgtm, size/L

#565 fix: allow for gzip and b64 encoding of the raw Addon data by decoding the input beforehand
  docs/topics/clusterdefinitions.md
  pkg/engine/artifacts.go
  pkg/engine/engine.go
Labels: approved, lgtm, size/M

#551 chore: disable ip-masq-agent when using cilium networkPlugin
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
Labels: approved, size/M

#578 chore: update the compute apiversion to 2018-10-01 to support new vmss features
  Gopkg.lock
  parts/k8s/kubernetesmastervars.t
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/compute.go
  pkg/armhelpers/disk.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/engine/transform/transform.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/containerservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinesizes.go
Labels: approved, lgtm, size/XXL

#582 feat: Multiple SSH keys for Linux & Windows nodes
  docs/topics/clusterdefinitions.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#581 fix: remove extra \n in log messages
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrademasternode.go
Labels: approved, lgtm, size/S

#586 Revert "feat: Multiple SSH keys for Linux & Windows nodes"
  docs/topics/clusterdefinitions.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
Labels: size/L

#583 fix: CONTAINERD_VERSION unbound variable in VHD build script
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, size/S

#574 fix: Explicitly use overlay2 storage driver while creation of vhd, by defa…
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
Labels: do-not-merge/hold, lgtm, size/S

#580 fix: eviction-hard is not implemented in windows
  pkg/api/defaults-kubelet.go
Labels: approved, lgtm, size/XS

#587 chore: enable Kubernetes v1.12.6
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#592 feat: Multiple SSH keys for Linux & Windows nodes
  docs/topics/clusterdefinitions.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#589 ci: add storage account cleanup to VHD pipeline
  .pipelines/vhd-builder.yaml
  packer.mk
Labels: approved, lgtm, size/S

#588 chore: enable Kubernetes v1.14.0-beta.1
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#590 test: add VMSS client interfaces and mocks to make upgrade testable
  pkg/armhelpers/compute.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: lgtm, size/L

#602 chore: align vmss casing to VMSS
  cmd/scale.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/compute.go
  pkg/armhelpers/utils/util_test.go
Labels: lgtm, size/M

#600 chore: update VHD reference to 2019.02.26
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#555 chore: add priorityClassName: system-node-critical to kube-system,…
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.10/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/ip-masq-agent.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
Labels: approved, lgtm, size/L

#601 ci: DRY_RUN variable is a string not a bool
  .pipelines/vhd-builder.yaml
  packer.mk
Labels: approved, lgtm, size/XS

#604 chore: modify eviction to memory.available.750Mi
  pkg/api/const.go
Labels: approved, do-not-merge/hold, lgtm, size/XS

#606 chore: update go-dev image
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, area/ci, lgtm, size/XS

#563 test: enable timeouts for running E2E commands
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/kubernetes/util/util.go
Labels: approved, lgtm, size/M

#605 chore: add system.conf with static JoinControllers configuration
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/system.conf
  pkg/engine/const.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/S

#607 fix: Fix the CNI lock file names
  parts/k8s/windowskubeletfunc.ps1
Labels: approved, lgtm, size/M

#611 chore: add support for k8s version 1.13.4
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#614 chore: enable 1.11.8 in VHD, deprecate 1.11.6
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS
