Repository Azure/aks-engine, pull requests merged in 2019-01, with the labels that each got.

#198 fix: protect the slice for append operation in multi-thread scenario
  pkg/helpers/pki.go
Labels: approved, lgtm, size/XS

#105 fix: increase vm upgrade timeout to 20 mins
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#185 fix: update MSI
  packer/install-dependencies.sh
  parts/k8s/artifacts/kubernetesazurekms.service
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, lgtm, size/L

#135 feat: Azure DevOps PR E2E pipeline
  .circleci/config.yml
  .pipelines/e2e-job-template.yaml
  .pipelines/e2e-step-template.yaml
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/L

#217 docs: update some docs with the right information
  docs/clusterdefinition.md
  docs/custom-vnet.md
  examples/addons/cluster-autoscaler/kubernetes-cluster-autoscaler.json
  pkg/engine/testdata/addons/kubernetes.json
  repro.json
Labels: approved, lgtm, size/S

#225 docs: remove obsolete "known issue"
  docs/kubernetes.md
Labels: approved, lgtm, size/XS

#216 fix: specify the vm size in error message during acc. networking valid…
  pkg/api/vlabs/validate.go
Labels: approved, lgtm, size/XS

#220 test: more tolerance for kube-system pod startup in E2E
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/M

#219 feat: support `make build` on Windows
  Makefile
Labels: approved, lgtm, size/M

#230 fix: add codecov token env var to Azure pipeline
  .pipelines/pr-e2e.yaml
Labels: approved, size/XS

#221 test: only check top nodes if RBAC is enabled
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#233 chore: remove Kubernetes 1.6 heapster version from VHD script
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#228 test: pre-delete ILB stuffs before running
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#212 fix: use kube-system namespace instead of flex, kv
  parts/k8s/containeraddons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#218 feat: add pod disruption budgets
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
Labels: approved, lgtm, size/M

#232 chore: update kubernetes-dashboard to v1.10.1
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#224 chore: remove stale scripts
  .dockerignore
  Dockerfile
  Dockerfile.k8swin
  scripts/build-windows-k8s.sh
  scripts/devenv-k8swin.ps1
  scripts/devenv.sh
  windows/Dockerfile
Labels: approved, lgtm, size/L

#231 fix: change default auth method for deploy,scale and upgrade
  cmd/deploy_test.go
  cmd/root.go
  docs/kubernetes/deploy.md
  docs/kubernetes/scale.md
  examples/k8s-upgrade/README.md
Labels: approved, lgtm, size/S

#236 fix: remove VM upgrade version check for AKS
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, lgtm, size/XS

#206 fix: do not check agent & master pool size when using availability zones
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: size/M

#241 feat: make maximumLoadBalancerRuleCount configurable
  docs/clusterdefinition.md
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastervars.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/M

#244 feat: add stale app yaml
  .github/stale.yml
Labels: approved, lgtm, size/M

#246 test: NetworkPolicy E2E tests cleanup for soak
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/namespace/namespace.go
Labels: approved, lgtm, size/S

#249 feat: add anti affinity to coredns deployment
  parts/k8s/addons/coredns.yaml
Labels: approved, lgtm, size/S

#260 docs: Fix Kubernetes release notes broken link
  docs/kubernetes/windows.md
Labels: lgtm, size/XS

#250 chore: remove commit check from Azure DevOps pipeline
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/XS

#256 feat: update addon-resizer to v1.8.4
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, needs-rebase, size/S

#254 feat: add new etcd versions, 3.2.25 is default
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, needs-rebase, size/XS

#258 feat: update kube-dns to v1.15.0
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, needs-rebase, size/S

#263 fix: Give cluster-autoscaler permission to list replicasets.apps
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
Labels: approved, lgtm, size/XS

#264 fix: Rename acsengineVersion tag to aksEngineVersion
  docs/kubernetes/deploy.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/masterparams.t
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/M

#267 docs: fix link to Azure Active Directory integration
  docs/clusterdefinition.md
Labels: lgtm, size/XS

#259 feat: update img binary to v0.5.6
  parts/k8s/kubernetesinstalls.sh
Labels: approved, lgtm, needs-rebase, size/XS

#243 feat: add localhost and 127.0.0.1 to certificates
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/helpers/pki.go
Labels: approved, lgtm, size/S

#266 fix: addon manager pod discruption budgets
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
Labels: approved, lgtm, size/S

#204 fix: address goimports checks
  cmd/deploy_test.go
  main.go
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/mocks.go
  pkg/api/orchestrators.go
  pkg/api/strictjson_test.go
  pkg/api/types.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/graph.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/engine/engine_test.go
  pkg/engine/types.go
  pkg/i18n/i18n.go
  pkg/operations/cordondrainvm.go
  pkg/operations/cordondrainvm_test.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: size/L

#262 test: enable multiple subnets per agent pool
  test/e2e/azure/cli.go
  test/e2e/engine/template.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/M

#252 chore: update go-dev image for newer golangci-lint
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#257 feat: update heapster to 1.5.4
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#292 chore: add support for Kubernetes 1.13.2
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#284 fix: add missing container images in VHD
  packer/install-dependencies.sh
Labels: approved, size/XS

#293 docs: add note on AKS-Engine and AKS relationship
  README.md
Labels: approved, lgtm, size/XS

#268 fix: replace some leftover acsengine by aksengine
  docs/tutorials/custom-vnet.md
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
  examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas-multimaster.json
  examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas.json
  examples/e2e-tests/userassignedidentity/vmss/kubernetes-vmss.json
  examples/kubernetes-msi-userassigned/kube-vma.json
  examples/kubernetes-msi-userassigned/kube-vmss.json
  packer/vhd-image-builder.json
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/mockclients.go
  pkg/engine/const.go
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
Labels: approved, lgtm, size/M

#295 fix: set heapster Deployment to EnsureExists to prevent heapster-nann…
  parts/k8s/containeraddons/kubernetesmasteraddons-heapster-deployment.yaml
Labels: approved, lgtm, size/XS

#296 chore: add config for welcome bot
  .github/config.yml
Labels: approved, lgtm, size/S

#279 test: print all pods at beginning of E2E test run
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#300 fix: revert PodDisruptionBudget definitions
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
Labels: approved, lgtm, size/M

#274 test: print pod logs when errors occur
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/S

#309 docs: Fix docs link to howto/README.md
  docs/README.md
Labels: lgtm, size/XS

#308 feat: update VHD version to 2019.01.11
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#314 chore: update git-chglog configuration for releases
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
Labels: approved, lgtm, size/M

#290 chore: update Azure CNI to v1.0.16
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#325 Updating containermonitoring addon to use the latest agent
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/L

#334 docs: update default value of smb-flexvolume in clusterdefinitions.md
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/XS

#331 chore: add support for Kubernetes 1.12.5
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#323 fix: use correct OS Type in description text
  parts/agentparams.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  parts/windowsparams.t
Labels: approved, lgtm, size/S

#299 feat: pre-pull flannel images
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#319 fix: Add ILB for vmss masters
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  pkg/api/common/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/L

#338 docs: fix broken link in clusterdefinitions.md
  docs/topics/clusterdefinitions.md
Labels: size/XS

#347 fix: Fix the incorrect computername parameter
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
Labels: approved, lgtm, size/XS

#318 feat: add SGX driver installation on C-series VMs
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
  pkg/api/azenvtypes.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/const.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#287 refactor: upgrade code refactor part 1
  cmd/upgrade.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/v16upgrader.go
  pkg/operations/kubernetesupgrade/v17upgrader.go
  pkg/operations/kubernetesupgrade/v18upgrader.go
Labels: approved, awaiting review, size/L

#358 fix: the number of probes is of type int32 and not string
  parts/k8s/kubernetesmasterresources.t
Labels: approved, lgtm, size/XS

#348 docs: fix a broken link and rename ACS to AKS
  docs/tutorials/quickstart.md
  docs/tutorials/quickstart.zh-CN.md
Labels: approved, lgtm, size/S

#343 enable ipvs + samples
  docs/topics/clusterdefinitions.md
  examples/ipvs/kubernetes-msi.json
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/L

#291 set publicIPAllocationMethod as static for master node
  parts/k8s/kubernetesmasterresourcesvmss.t
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
Labels: lgtm, size/S

#360 fix: ServiceCidr + DNSServiceIP validation error message
  pkg/api/vlabs/validate.go
Labels: approved, lgtm, size/XS

#330 chore: add support for Kubernetes 1.14.0-alpha.1
  .pipelines/pr-e2e.yaml
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
Labels: approved, size/L

#359 fix: add getter methods for managed identity
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/L

#356 docs: rewrite upgrade documentation
  docs/howto/troubleshooting.md
  docs/topics/README.md
  docs/topics/scale.md
  docs/topics/scaling.md
  docs/topics/upgrade.md
  examples/k8s-upgrade/README.md
Labels: approved, area/docs, lgtm, size/L

#365 fix: remove invalid parameter location from vmss extension profiles
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, lgtm, size/XS

#375 update cosmos link
  examples/cosmos-etcd/readme.md
Labels: lgtm, size/XS

#374 chore: use the latest docker go dev image
  .circleci/config.yml
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#297 feat: Support customized environments in apimodel.json (#276) and Support customized API version in ARM template (#283)
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: approved, do-not-merge/hold, lgtm, size/XL

#378 fix: Add support for low pri scalesets in windows agents
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, lgtm, size/XS

#369 fix: Enable billing extension for AzureChinaCloud
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/XS

#370 docs: Update kubernetes-developers.md
  docs/topics/kubernetes-developers.md
Labels: area/docs, lgtm, size/S

#383 test: add k8s components versions test 1.13
  pkg/api/k8s_versions_test.go
Labels: size/M

#368 Update documentation for container monitoring addon
  docs/topics/monitoring.md
  docs/tutorials/containermonitoringaddon.md
  examples/addons/container-monitoring/README.md
  examples/addons/container-monitoring/kubernetes-container-monitoring.json
Labels: approved, do-not-merge/hold, size/L

#387 docs: don’t use upgrade if IaaS has been changed
  docs/topics/upgrade.md
Labels: approved, lgtm, size/XS

#395 docs: fix all broken links
  docs/community/planning-process.md
  docs/community/release-checklist.md
  docs/howto/building-windows-kubernetes-binaries.md
  docs/howto/mixed-cluster-ingress.md
  docs/topics/aad.md
  docs/topics/clusterdefinitions.md
  docs/topics/extensions.md
  docs/topics/features.md
  docs/topics/hybrid-environment.md
  docs/topics/kubernetes-developers.md
  docs/topics/kubernetes-walkthrough.md
  docs/topics/monitoring.md
  docs/topics/windows-and-kubernetes.md
  docs/topics/windows.md
  docs/tutorials/custom-vnet.md
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
  examples/addons/container-monitoring/README.md
Labels: approved, lgtm, size/XL

#313 fix: add toleration to run flannel on not-yet-ready nodes.
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
Labels: lgtm, size/XS

#381 docs: upgrade + cluster-autoscaler notes
  docs/topics/upgrade.md
  examples/addons/cluster-autoscaler/README.md
Labels: approved, lgtm, size/S

#405 fix(cilium): Allow the daemonset to deploy regardless of node status.
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
Labels: approved, lgtm, size/XS

#409 doc: fix broken links in examples README
  examples/README.md
Labels: approved, lgtm, size/S
