Repository Azure/aks-engine, pull requests merged in 2019-05, with the labels that each got.

#1186 style: use 'grep -E' instead of deprecated 'egrep'
  scripts/validate-shell.sh
  test/e2e/kubernetes/scripts/modprobe-config-validate.sh
  test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
Labels: approved, area/ci, lgtm, size/S

#1185 style: use builtin 'command -v' instead of nonstandard 'which'
  scripts/validate-shell.sh
  test/common.sh
Labels: approved, area/ci, lgtm, size/S

#1089 fix: add Azure China support for Calico DaemonSet
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/api/addons.go
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/azenvtypes.go
  pkg/engine/artifacts.go
Labels: approved, lgtm, size/XXL

#1187 style: fix suspicious unquoted literal strings
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/armvariables_test.go
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1188 test: can’t ssh into master vmss master vms
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XL

#1153 chore: onboard Azure CNI images to MCR
  packer/install-dependencies.sh
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  pkg/api/azenvtypes.go
  pkg/api/defaults_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/S

#1156 chore: update omsagent addon to use the latest version
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/L

#1195 test: hasSSHAbleMaster returns false if master vmss
  test/e2e/kubernetes/kubernetes_test.go
Labels: size/XS

#1191 style: use 'grep -c' instead of 'grep|wc'
  scripts/validate-shell.sh
  test/cluster-tests/kubernetes/k8s-utils.sh
  test/cluster-tests/kubernetes/test.sh
Labels: approved, area/ci, lgtm, size/XS

#1194 fix: enableEncryptionWithExternalKms with master VMSS missing objectID
  pkg/engine/keyvaults.go
  pkg/engine/keyvaults_test.go
Labels: approved, lgtm, size/XS

#1198 test: enable all ssh to master tests for vmss masters
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XL

#1196 ci: permit optional scope field when generating changelog
  .chglog/config.yml
Labels: approved, lgtm, size/XS

#1197 style: don't use shell variables in printf format string
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1200 style: remove quotes that accidentally unquote
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1199 chore: deprecate unused CSE func installDockerEngine
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
Labels: approved, lgtm, size/S

#1201 style: expressions don't expand in single quotes
  parts/k8s/cloud-init/artifacts/cse_install.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1184 chore: update VHD version to 04.30.2019
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.30.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.30.txt
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#1205 feat: add two US DoD Azure locations
  pkg/api/types_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/generate_azure_constants.py
Labels: approved, lgtm, size/S

#1202 style: replace unneeded 'cat' commands
  packer/init-variables.sh
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/armvariables_test.go
  scripts/validate-shell.sh
  test/e2e/kubernetes/scripts/net-config-validate.sh
  test/e2e/kubernetes/scripts/time-sync-validate.sh
Labels: approved, area/ci, lgtm, size/M

#1193 feat: add support for Kubernetes 1.11.10
  packer/install-dependencies.sh
  pkg/api/apiloader_test.go
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1192 chore: update Azure CNI version to v1.0.22
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
Labels: approved, lgtm, size/XS

#1213 style: sudo doesn't affect redirects
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1211 docs: improve developer debugging instructions
  docs/community/developer-guide.md
  docs/static/img/debug-code.png
  docs/static/img/debug-test.png
  docs/static/img/install-go-extension.png
Labels: approved, area/docs, size/L

#1143 feat: add auditd as an ubuntu option
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/auditd-rules
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/scripts/auditd-validate.sh
Labels: approved, size/XL

#1230 style: remove unneeded 'echo' commands
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/armvariables_test.go
  scripts/validate-shell.sh
Labels: approved, lgtm, size/S

#1222 feat: remove azurefile storage class for Azure Stack
  parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes-custom.yaml
  parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes-custom.yaml
  pkg/engine/artifacts.go
Labels: azurestack, size/L

#1226 fix: private cluster with VMSS masters, jumpbox
  pkg/engine/masterarmresources.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/networksecuritygroups.go
  pkg/engine/networksecuritygroups_test.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/L

#1234 style: bash parameter expansion replaces "echo | sed"
  parts/k8s/cloud-init/artifacts/cse_config.sh
  scripts/validate-shell.sh
  test/cluster-tests/kubernetes/test.sh
Labels: approved, lgtm, size/XS

#1237 revert: /etc/default/grub changes aren't reconcilable over time
  packer/vhd-image-builder.json
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/default-grub
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Labels: approved, lgtm, size/M

#1242 style: use single quotes in trapping exit codes
  examples/vnet/dual-subnet-vnet-predeploy.sh
  examples/vnet/k8s-vnet-azure-cni-predeploy.sh
  examples/vnet/k8s-vnet-predeploy.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1233 feat: disable unsupported addons on Azure Stack deployments
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/artifacts.go
  pkg/engine/params_k8s.go
Labels: approved, azurestack, lgtm, size/L

#1240 fix: Windows Kubelet issues error due to unsupported config
  pkg/api/defaults-kubelet.go
Labels: approved, lgtm, size/XS

#1236 chore: enable moby 3.0.5, and set 3.0.5 to default
  docs/topics/clusterdefinitions.md
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/S

#1243 chore: remove support for Kubernetes 1.11.8
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1241 style: declare and assign separately to avoid masking return values
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  scripts/validate-shell.sh
  test/cluster-tests/utils.sh
  test/common.sh
  test/deploy.sh
  test/shunit/validate_deployment.sh
Labels: approved, area/ci, lgtm, size/M

#1244 fix: default kubelet flags windows/linux reconciliation w/ unit tests
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/L

#1250 fix: remove outbound connectivity check on disconnected Azure Stacks
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
Labels: approved, azurestack, lgtm, size/XS

#1248 fix: Proper permission on the HOME dir for user on jumpbox VM
  parts/k8s/cloud-init/jumpboxcustomdata.yml
Labels: approved, lgtm, size/XS

#1252 test: test for missing kubelet configs as well
  pkg/api/defaults-kubelet_test.go
Labels: approved, size/M

#1247 feat: add support for Kubernetes 1.15.0-alpha.3
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
Labels: approved, lgtm, size/M

#1254 test: add no outbound CSE unit test
  pkg/engine/vmextensions_test.go
Labels: approved, size/M

#1227 chore(CIS):enable protect-kernel-defaults
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#1263 docs: aks-engine deploy tutorial errors out for auth method as CLI for linux container on windows
  docs/tutorials/quickstart.md
Labels: lgtm, size/XS

#1262 feat: add support for Kubernetes 1.13.6
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#1266 style: standardize makefile syntax
  Makefile
Labels: approved, lgtm, size/S

#1251 chore: deprecate CIS files cloud-init paving for non-VHD distros
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/types_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/CIS-files-validate.sh
Labels: approved, awaiting review, lgtm, size/XL

#1257 fix: removing PodSecurityPolicy files from manifests folders
  parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/artifacts.go
Labels: approved, lgtm, size/M

#1272 docs: correct "--auth-method" arguments in help
  cmd/root.go
  docs/topics/scale.md
Labels: approved, area/docs, lgtm, size/XS

#1264 docs: Update k8s version references in docs/samples
  .gitignore
  docs/howto/kubernetes-large-clusters.md
  docs/topics/features.md
  docs/topics/upgrade.md
  docs/tutorials/deploy.md
  examples/addons/cluster-autoscaler/README.md
  examples/addons/nvidia-device-plugin/README.md
  examples/customfiles/kubernetes-customfiles-podnodeselector.json
  examples/e2e-tests/kubernetes/gpu-enabled/definition.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/clear-containers.json
  examples/e2e-tests/kubernetes/node-count/50-nodes/definition.json
  examples/feature-gates/kubernetes-featuresgates.json
  examples/ipvs/kubernetes-msi.json
  examples/kubernetes-clear-containers.json
  examples/kubernetes-config/kubernetes-cloud-controller-manager.json
  examples/kubernetes-config/kubernetes-keyvault-encryption.json
  examples/kubernetes-config/kubernetes-standardlb.json
  examples/kubernetes-containerd.json
  examples/kubernetes-kata-containers.json
  examples/kubernetes-labels/kubernetes.json
  examples/kubernetes-vmss-low-priority/kubernetes.json
  examples/kubernetes-vmss-master/kubernetes.json
  examples/kubernetes-vmss-master/windows.json
  examples/kubernetes-vmss/kubernetes.json
  examples/largeclusters/kubernetes.json
  examples/managed-identity/kubernetes-msi.json
  examples/multiple-nodepools/multipool.json
  examples/networkpolicy/kubernetes-cilium.json
  examples/service-mesh/istio.json
Labels: approved, area/docs, lgtm, size/M

#1271 build: validate deps before 'make build', and some cleanup
  .pipelines/pr-e2e.yaml
  Makefile
  scripts/validate-commit-msg.sh
Labels: approved, lgtm, size/M

#1265 chore: rename addons-related types and consts
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/params_k8s.go
Labels: approved, do-not-merge/hold, size/XXL

#1274 test: reduced name for ilb curl deployment
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#1275 docs: add a more complete VS Code debug configuration
  docs/community/developer-guide.md
  docs/community/example-launch.json
Labels: approved, area/docs, lgtm, size/L

#1279 Update hyperkube command in manifests for k8s components.
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
Labels: size/S

#1259 fix: add validation for non-support of prometheus extension for Windows
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/M

#1276 feat: Make cordon drain timeout configurable with --upgrade
  cmd/upgrade.go
  cmd/upgrade_test.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: size/L

#1285 test: add storage + Azure Stack addons unit tests
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
Labels: approved, lgtm, size/L

#1286 chore: enable VHD 2019.05.08, disable auditd for non-VHD
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/azenvtypes.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.05.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.05.08.txt
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, lgtm, size/L

#1044 fix: Ensure pods scheduled onto new nodes during upgrade respect the original node's labels/taints
  docs/topics/upgrade.md
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#1088 fix: commit generated go-bindata files with "--no-compress" option
  .gitignore
  .pipelines/pr-e2e.yaml
  Makefile
  docs/community/developer-guide.md
  pkg/engine/fileloader.go
  pkg/engine/templates_generated.go
  pkg/i18n/resourceloader.go
  pkg/i18n/translations_generated.go
Labels: approved, lgtm, size/XXL

#1294 docs: fix typos in launch.json debug example
  docs/community/example-launch.json
Labels: approved, area/docs, lgtm, size/XS

#1295 chore: update templates_generated.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#1300 fix: increase upgrade timeout to 180 minutes
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XS

#1297 test: fix auditd E2E for master VMSS
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#1308 fix: remove grub file permissions enforcement
  parts/k8s/cloud-init/artifacts/cis.sh
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/scripts/CIS-files-validate.sh
Labels: approved, lgtm, size/XS

#1309 docs: Clarify terminology around patches and use of windows-patches extension
  extensions/windows-patches/README.md
Labels: approved, lgtm, size/S

#1307 test: add masterSSHPort to auditd E2E SCP
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#1310 fix: don’t add etcd data disk in cosmos etcd scenario
  pkg/engine/masterarmresources.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
Labels: approved, size/M

#1283 fix: USER_ASSIGNED_IDENTITY_ID is empty in azure.json
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: lgtm, size/L

#1312 test: unit tests for kubernetesManifestSettingsInit
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
Labels: approved, lgtm, size/L

#1277 feat: custom tags on VMs and scale sets
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#1315 feat: add support for Kubernetes 1.14.2
  packer/install-dependencies.sh
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1314 fix: enable Windows plus custom VNET
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/XS

#1256 style: check exit code directly, not indirectly with $?
  extensions/hello-world-k8s/v1/hello-world-k8s.sh
  extensions/microsoft-oms-agent-k8s/v1/microsoft-oms-agent-k8s.sh
  extensions/prometheus-grafana-k8s/v1/prometheus-grafana-k8s.sh
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  pkg/engine/templates_generated.go
  scripts/validate-go.sh
  scripts/validate-shell.sh
  test/e2e/kubernetes/scripts/host-os-dns-validate.sh
Labels: approved, area/ci, lgtm, size/L

#1299 fix: Get VMSS node version from K8s API instead of tags for old instances
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/M

#1316 style: don't use `tr` to replace words
  scripts/validate-shell.sh
  test/e2e/kubernetes/scripts/time-sync-validate.sh
Labels: approved, area/ci, lgtm, size/XS

#1317 chore: update templates_generated.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1321 style: use 'cmd foo' instead of 'cmd $(echo foo)'
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/S

#1323 style: check for unused parameters
  .golangci.yml
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/generate.go
  cmd/generate_test.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/convertertoapi_test.go
  pkg/api/orchestrators.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/azurestack/converter.go
  pkg/engine/engine.go
  pkg/engine/params.go
  pkg/engine/params_test.go
  pkg/engine/template_generator.go
  pkg/engine/vmextensions.go
  test/aks-engine-test/promote/promote.go
Labels: approved, lgtm, size/L

#1293 chore: Update calico to v3.7.2
  docs/topics/features.md
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/api/addons.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/XL

#1319 chore: update VHD image to 2019.05.16
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.05.16.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.05.16.txt
Labels: approved, lgtm, size/L

#1326 chore: fix templates_generated.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#1280 docs: update group name and corresponding output folder names
  docs/topics/windows.md
Labels: approved, area/docs, lgtm, size/S, windows

#1327 fix:Base64 encode sp password for windows vmss
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/L

#1304 chore: add example cluster definition for Azure Stack
  examples/azurestack/kubernetes-azurestack-adfs.json
  examples/azurestack/kubernetes-azurestack-azure-ad.json
Labels: approved, area/docs, azurestack, lgtm, size/L

#1329 style: don't loop over 'find' output
  pkg/engine/testdata/rename.sh
  scripts/validate-shell.sh
Labels: approved, area/ci, lgtm, size/XS

#1331 chore: remove unused go template funcs
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1332 docs: add customVMTags to clusterdefinitions
  docs/topics/clusterdefinitions.md
Labels: approved, area/docs, lgtm, size/XS

#1333 test: add prototype for getTemplateFuncMap unit tests
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/engine.go
  pkg/engine/masterarmresources.go
  pkg/engine/networkinterfaces.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/L

#1305 chore: update go toolchain to 1.12.5
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#1334 test: getTemplateFuncMap unit tests part 1
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#1216 refactor: remove _Promo from static SKU lists
  pkg/api/common/helper.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/armvariables_test.go
  pkg/engine/engine_test.go
  pkg/engine/transform/transformtestfiles/dcos_scale_template.json
  pkg/engine/transform/transformtestfiles/dcos_template.json
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/generate_azure_constants.py
  pkg/helpers/helpers.go
Labels: approved, lgtm, size/XL

#1337 docs: update tutorial docs to use kubernetes instead of swarm
  docs/tutorials/custom-vnet.md
Labels: size/M

#1340 test: sorted GetKubernetesLabels method for deterministic unit tests
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#1341 fix:Update quickstart.md
  docs/tutorials/quickstart.md
Labels: lgtm, size/XS

#1336 style: shell commands can only exit with status 0-255
  scripts/validate-shell.sh
  test/common.sh
  test/deploy.sh
  test/e2e.sh
Labels: approved, area/ci, lgtm, size/M

#1338 test: getTemplateFuncMap unit tests part 2
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/const.go
  pkg/api/defaults-apiserver.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/networkinterfaces.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/L

#1339 chore: bump cluster-autoscaler to latest patch versions
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1347 fix: revert previous load balancer changes for Azure Stack
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
Labels: approved, azurestack, lgtm, size/S

#1346 fix: decrease default host MTU for Azure Stack
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
Labels: approved, azurestack, lgtm, size/M

#1354 chore: ensure all Linux-bound files are LF (not CRLF)
  examples/kubernetes-config/kubernetes-rescheduler.json
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/cloud-init/artifacts/auditd-rules
  parts/k8s/cloud-init/artifacts/default-grub
  parts/k8s/cloud-init/artifacts/etc-issue
  parts/k8s/cloud-init/artifacts/etc-issue.net
  parts/k8s/cloud-init/artifacts/pam-d-common-auth
  parts/k8s/cloud-init/artifacts/pam-d-common-password
  parts/k8s/cloud-init/artifacts/pam-d-su
  parts/k8s/cloud-init/jumpboxcustomdata.yml
  parts/k8s/containeraddons/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
Labels: bug

#1359 fix: never use 3.0.4 for moby-cli and update moby on upgrade
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
Labels: lgtm

#1343 feat: allow "client_secret" auth method with ADFS identity provider
  cmd/root.go
  cmd/root_test.go
  examples/azurestack/kubernetes-azurestack-adfs-cert.json
  examples/azurestack/kubernetes-azurestack-adfs-secret.json
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
Labels: approved, azurestack, lgtm, size/M

#1344 test: getTemplateFuncMap unit tests part 3
  parts/dcos/bstrap/bootstrapparams.t
  parts/dcos/bstrap/bootstrapresources.t
  parts/dcos/bstrap/dcosmasterresources.t
  parts/dcos/dcosagentresourcesvmas.t
  parts/dcos/dcosagentresourcesvmss.t
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1367 fix: correction of file/path inversion args for custom yaml manifests
  pkg/engine/artifacts.go
Labels: approved, lgtm, size/XS

#1360 fix: update etcd and containerd versions during upgrade
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved

#709 feat: added support for direct array assignment using --set
  pkg/engine/transform/apimodel_merger.go
  pkg/engine/transform/apimodel_merger_test.go
Labels: approved, lgtm, size/M

#1364 docs: update prow docs
  .prowci/README.md
  .prowci/deck.yaml
  .prowci/hook.yaml
  .prowci/plugins.yaml
  .prowci/tide.yaml
Labels: approved, lgtm, size/S

#1383 feat: add support for Kubernetes 1.12.9
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1384 chore: add support for etcd 3.2.26
  packer/install-dependencies.sh
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#1369 fix: remove "allow-privileged" in kubelet 1.15.0
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/M

#1390 fix: Update Kata download URL
  parts/k8s/cloud-init/artifacts/cse_install.sh
Labels: approved, lgtm, size/XS

#1382 docs: update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, lgtm, size/M

#1394 feat: add support for Kubernetes 1.15.0-beta.1
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1385 fix: ensure cluster-autoscaler image gets updated during upgrades
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#1405 chore: update generated files
  pkg/engine/templates_generated.go
Labels: approved, size/S

#1403 fix: disable redundant cosmosdb regions
  pkg/engine/cosmosdb.go
  pkg/engine/cosmosdb_test.go
Labels: approved, lgtm, size/XS

#1402 fix: prune addon defaults if the addon is disabled
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/M

#1407 test: refactor addons default image test
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L

#1397 test: enable aks-engine e2e test on azurestack
  test/e2e/config/config.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_suite_test.go
  test/e2e/runner.go
Labels: approved, lgtm, size/L

#1399 docs: update custom vnet documentation
  docs/tutorials/custom-vnet.md
Labels: area/docs, lgtm, size/M

#1371 docs: Azure Stack doc page
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack-adfs.json
  examples/azure-stack/kubernetes-azurestack-azure-ad.json
  examples/azurestack/kubernetes-azurestack-azure-ad.json
Labels: approved, azurestack, lgtm, size/L

#1408 test: update unit test payload for Azure Stack
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
Labels: approved, lgtm, size/XS

#1415 chore: add security to changelog commit titles
  .chglog/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/XS

#1413 security: remove support for 1.13.6 and 1.14.2
  pkg/api/common/versions.go
Labels: approved, do-not-merge/hold, lgtm, size/XS

#1351 refactor: triage untestable DCOS code
  .codecov/codecov.yml
  pkg/engine/engine.go
  pkg/engine/engine_dcos.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
Labels: approved, lgtm, size/XL

#1417 chore: ignore junit.xml from e2e
  .gitignore
Labels: approved, lgtm, size/XS

#1410 docs: sample extensions workaround for Azure Stack
  docs/topics/azure-stack.md
Labels: approved, lgtm, size/S

#1420 revert: add support for Kubernetes 1.12.9
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS
