Repository Azure/aks-engine, pull requests merged in 2019-07, with the labels that each got.

#1527 chore: replace deprecated extensions/v1beta APIs for 1.16
  parts/k8s/addons/1.16/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/1.16/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/1.16/ip-masq-agent.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-tiller-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#1554 fix: UAE North and UAE Central regions are missing from certificate host names
  pkg/api/types_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  pkg/helpers/pki_test.go
Labels: approved, lgtm, size/S

#1549 feat: Add defaults for useInstanceMetadata and AcceleratedNetworkingEnabled on Azure Stack
  docs/topics/azure-stack.md
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/armvariables_test.go
Labels: approved, azurestack, lgtm, size/M

#1542 feat: set ipam environment to mas in Azure CNI config on Azure Stack
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, azurestack, lgtm, size/M

#1555 fix: use correct path for monitor script in monitor units
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1560 feat: support CoreOS-like Linux distributions
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1442 feat: support for Application Gateway Ingress Controller
  examples/addons/appgw-ingress/README.md
  examples/addons/appgw-ingress/kubernetes-appgw-ingress.json
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/applicationgateway.go
  pkg/engine/applicationgateway_test.go
  pkg/engine/armoutputs.go
  pkg/engine/armoutputs_test.go
  pkg/engine/armresources.go
  pkg/engine/armtype.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/ipaddresses.go
  pkg/engine/ipaddresses_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/params_k8s.go
  pkg/engine/roleassignments.go
  pkg/engine/roleassignments_test.go
  pkg/engine/templates_generated.go
  pkg/engine/userassignedidentities.go
  pkg/engine/userassignedidentities_test.go
  pkg/engine/virtualnetworks.go
  pkg/engine/virtualnetworks_test.go
Labels: approved, lgtm, size/XXL

#1569 docs: changed accelerated networking example VMs
  examples/kubernetes-config/kubernetes-accelerated-network.json
Labels: lgtm, size/XS

#1565 chore: update VHD to 2019.07.01
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201907_2019.07.01.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201907_2019.07.01.txt
Labels: approved, size/L

#1564 feat: Add checks for Metadata, AcceleratedNetworking and etcdDiskSizeGB on Azure Stack to fail fast.
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, azurestack, lgtm, size/L

#1558 feat: Set EtcdDiskSizeGB max default size to 1023 if target platform is Azure Stack
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, azurestack, lgtm, size/L

#1568 feat: default AcceleratedNetworkingEnabledWindows to false if target platform is Azure Stack
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/S

#1571 revert: Revert "feat: support CoreOS-like Linux distributions (#1560)"
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#913 feat: allow custom os images from external subs via Shared Image Galleries
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/custom-shared-image.json
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/XL

#1570 fix: do not override vnetCidr param when empty string
  pkg/engine/params.go
Labels: approved, lgtm, size/XS

#1572 feat: support CoreOS-like Linux distributions
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#1579 test: improve crashing kube-system pod check
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#1589 test: remove dependency on httpmock for Azure Stack unit tests
  .codecov/codecov.yml
  cmd/root_test.go
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/azurestack/deployment_test.go
  pkg/armhelpers/azurestack/disk_test.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/network_test.go
  pkg/armhelpers/azurestack/testserver/testServer.go
Labels: approved, lgtm, size/XL

#1575 feat: add scheduled maintenance addon, by default disabled
  docs/topics/clusterdefinitions.md
  parts/k8s/addons/kubernetesmasteraddons-scheduled-maintenance-deployment.yaml
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#1592 feat: change windows profile defaults for Azure Stack
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#1574 fix: kubeconfig incorrectly escape characters for azuredeploy.json
  pkg/engine/armvariables.go
Labels: approved, lgtm, size/XS

#1587 fix: do not install clear containers runtime on the VHD
  packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#1591 chore: update Azure constants with new VM sizes
  pkg/api/types_test.go
  pkg/engine/armvariables_test.go
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/M

#1595 feat: add support for Kubernetes 1.13.8
  packer/install-dependencies.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/versions.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#1598 test: temporarily allow 10 CA restarts
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#1600 fix: improve clear containers clean up
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#1603 chore: re-enable k8s 1.12.7
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1604 docs: fix typo in examples/addons/cluster-autoscaler
  examples/addons/cluster-autoscaler/README.md
Labels: lgtm, size/XS

#1599 fix: use explicit spec.Selector with apps/v1 api manifests
  parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/1.16/ip-masq-agent.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#1543 feat: Support kubectl port-forward with k8s 1.15 on Windows nodes
  .gitignore
  Makefile
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#1608 docs: rename vhd release notes files to match sku names
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201905_2019.05.08.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201905_2019.05.16.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201906_2019.06.08.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201906_2019.06.12.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201906_2019.06.18.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201906_2019.06.20.txt
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201906_2019.06.26.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201905_2019.05.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201905_2019.05.16.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201906_2019.06.08.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201906_2019.06.12.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201906_2019.06.17.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201906_2019.06.20.txt
Labels: approved, lgtm, size/XS

#1601 feat: re-enable VMSS overprovisioning for agents
  pkg/engine/armresources_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/S

#1561 fix: old VMSS AKS cluster cannot be upgraded after April 2
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/XS

#1619 chore: Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1614 feat: add support for Kubernetes 1.13.8 and 1.14.4 on Azure Stack.
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, azurestack, lgtm, size/S

#1578 fix: CoreOS improvements and fixes
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1629 chore: update kube-dns to v1.15.4
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1631 feat: pre-pull docker distribution for Azure Stack
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, azurestack, lgtm, size/XS

#1633 fix: Remove unnecessary transform on VMSS upgrade
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/dcos_scale_template.json
  pkg/engine/transform/transformtestfiles/dcos_template.json
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, size/XXL

#1639 chore: update dnsmasq-nanny to v1.15.4
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#1642 feat: add support for Kubernetes 1.15.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#1643 fix: update cluster-autoscaler role
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#1584 feat: generate network configuration file for Azure CNI on Azure Stack
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/XL

#1623 fix: extend default value -1 for PodMaxPids for master and agentpool profile …
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: size/XL

#1637 fix: update container monitoring add-on to use latest version of the containerized omsagent
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/L

#1649 chore: deprecate clear-containers runtime support
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/e2e-tests/kubernetes/kubernetes-config/clear-containers.json
  examples/kubernetes-clear-containers.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#1650 test: replace “vanilla” E2E cluster test with non-VHD cluster test
  .pipelines/pr-e2e.yaml
  examples/kubernetes-ubuntu-distro.json
Labels: approved, lgtm, size/M

#1653 feat: add support for Kubernetes 1.15.1 on Azure Stack.
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#1658 chore: update go toolchain to 1.12.7
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  Makefile
  makedev.ps1
Labels: approved, lgtm, size/XS

#1659 docs: use Azure's standard code of conduct for GitHub
  CODE_OF_CONDUCT.md
Labels: approved, lgtm, size/M

#1622 fix: clusters with SLB scale and upgrade
  cmd/scale.go
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/ipaddresses.go
  pkg/engine/ipaddresses_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XXL

#1626 feat: add support for Kubernetes 1.16.0-alpha.1
  .pipelines/pr-e2e.yaml
  parts/k8s/addons/1.16/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/label-nodes.service
  parts/k8s/cloud-init/artifacts/label-nodes.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.1.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.1.yaml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/k8s_versions.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XXL

#1665 feat: add support for Kubernetes 1.15.1 on Azure Stack
  docs/topics/azure-stack.md
  packer/install-dependencies.sh
Labels: approved, azurestack, lgtm

#1648 fix: add ipv6 nic config for vmss [IPv6DualStack]
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/armresources_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/L

#1667 test: don't check for kubernetes.azure.com/role label
  test/e2e/kubernetes/kubernetes_test.go
Labels: area/e2e

#1670 docs: add docs for dualstack
  examples/dualstack/README.md
  examples/dualstack/kubernetes.json
Labels: area/docs

#1646 fix: omit NSG rules created by LoadBalancer during upgrade
  pkg/engine/transform/transform.go
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
Labels: approved, lgtm, size/M

#1688 fix: lock docker distribution version for Azure Stack
  packer/install-dependencies.sh
Labels: azurestack

#1702 ci: fix VHD release notes Azure DevOps log parsing
  packer.mk
Labels: lgtm

#1345 refactor: simplify scale operation CLI output
  Gopkg.lock
  Gopkg.toml
  cmd/rotate_certs.go
  cmd/rotate_certs_test.go
  cmd/scale.go
  docs/community/example-launch.json
  docs/topics/certificaterotation.md
  docs/topics/scale.md
  docs/tutorials/day2-operations.md
  examples/azure-cni/k8s-scale.sh
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/deployments.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/engine/transform/transform.go
  pkg/operations/cordondrainvm.go
  pkg/operations/deletevm.go
  pkg/operations/k8sapi_ops.go
  pkg/operations/k8sapi_ops_test.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgrademasternode.go
  vendor/github.com/mgutz/ansi/LICENSE
  vendor/github.com/mgutz/ansi/ansi.go
  vendor/github.com/mgutz/ansi/doc.go
  vendor/github.com/mgutz/ansi/print.go
  vendor/github.com/x-cray/logrus-prefixed-formatter/LICENSE
  vendor/github.com/x-cray/logrus-prefixed-formatter/formatter.go
Labels: approved, lgtm, size/XXL

#1651 feat: Adding ephemeral disk support
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/disks-ephemeral/README.md
  examples/disks-ephemeral/ephemeral-disks.json
  examples/disks-ephemeral/kubernetes-vmas.json
  examples/e2e-tests/kubernetes/windows/hybrid/definition.json
  pkg/api/agentPoolOnlyApi/vlabs/const.go
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/common/const.go
  pkg/api/common/helper.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: approved, size/L
