Repository Azure/aks-engine, pull requests merged in 2020-11, with the labels that each got.

#3990 refactor: move ssh-related funcs to its own package
  cmd/get_logs.go
  cmd/get_logs_test.go
  cmd/root.go
  docs/topics/get-logs.md
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/helpers/ssh/scp.go
  pkg/helpers/ssh/ssh.go
  pkg/helpers/ssh/types.go
  pkg/kubernetes/interfaces.go
Labels: approved, lgtm, size/XXL

#3995 test: fix two UTs to work with "cli" auth
  cmd/get_locations_test.go
  cmd/get_skus_test.go
Labels: approved, lgtm, size/XS

#3996 chore: update cluster-autoscaler to v1.19.1
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3993 chore: set go sdk log level for Azure Stack clusters
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  pkg/engine/templates_generated.go
Labels: lgtm, size/XS

#3989 feat: set apiserver tokenRequest flags in 1.20+
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
Labels: approved, lgtm, size/M

#4001 fix: Mount /usr/local/share/ca-certificates folder into kube-controller-manager
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3999 feat: add support for Kubernetes v1.20.0-beta.1
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#4000 chore: update cluster-autoscalers to latest patches
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#4008 ci: Adding CI pipeline to verify windows provisioning script content BEFORE it gets check in
  .pipelines/pr-windows-signed-scripts.yaml
  scripts/build-windows-provisioning-scripts.sh
  test/e2e/engine/template.go
Labels: approved, lgtm, size/M

#4010 ci: remove node-problem-detector addon from PR E2E
  examples/e2e-tests/kubernetes/release/default/definition.json
Labels: approved, lgtm, size/XS

#4002 fix: Re-ordering HNS policy removal due to 10c change in behavior and consolidating logic in Windows cleanup scripts
  .pipelines/pr-windows-signed-scripts.yaml
  staging/provisioning/windows/cleanupnetwork.ps1
  staging/provisioning/windows/kubeletstart.ps1
  staging/provisioning/windows/windowsnodereset.ps1
Labels: approved, do-not-merge/hold, lgtm, size/L

#4004 chore: Adding csi-proxy-v0.2.2 to Windows VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#4012 chore: update powershell signed scripts
  pkg/api/const.go
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3956 chore: Install Windows Server 2019 10C updates in Windows VHD
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-2019-vars.json
Labels: VHD, approved, size/XS, windows

#4015 ci: Updating pr-windows-signed-scripts.yaml to allow for overriding cluster definition
  .pipelines/pr-windows-signed-scripts.yaml
  docs/topics/windows-provisioning-scripts.md
Labels: approved, lgtm, size/S

#4016 chore: rev Linux VHDs to 2020.10.30
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.10.30.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.10.30.txt
Labels: approved, lgtm, size/XXL

#4020 chore: Add Windows 10c image as default (August optional patches)
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1554.201109.txt
Labels: VHD, approved, lgtm, size/L, windows

#4017 fix: enable dhcpv6 only for ubuntu 16.04
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/dualstack.json
Labels: approved, lgtm, size/M

#4023 chore: Windows November Patches (11b)
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS

#4022 test: configurable stability iterations timeout
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, size/M

#4024 test: add dns-loop (actually curl) stress test
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/dns-loop.yaml
Labels: approved, size/S

#4028 update azenvtypes for 20201111 VHD release
  pkg/api/azenvtypes.go
Labels: size/XS

#4031 chore: Update Windows image version
  pkg/api/azenvtypes.go
  pkg/api/const.go
Labels: size/XS

#4029 fix: Adding csi-proxy logs locked file list to prevent access denied errors
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/XS

#4032 Update Windows image version to the latest.
  pkg/api/azenvtypes.go
Labels: aks, size/XS

#4034 test: re-engage cluster-autoscaler tests if no ssh
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#4033 chore: Use Windows November(11b) updates as default vhd
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1577.201112.txt
Labels: VHD, approved, lgtm, size/L, windows

#4036 chore: remove deprecated localizations
  README_zh-CN.md
  docs/topics/README.md
  docs/topics/clusterdefinitions.zh-CN.md
  docs/tutorials/README.md
  docs/tutorials/quickstart.zh-CN.md
  loc/cs-CZ/acsengine.po.lcl
  loc/de-DE/acsengine.po.lcl
  loc/es-ES/acsengine.po.lcl
  loc/fr-FR/acsengine.po.lcl
  loc/hu-HU/acsengine.po.lcl
  loc/it-IT/acsengine.po.lcl
  loc/ja-JP/acsengine.po.lcl
  loc/ko-KR/acsengine.po.lcl
  loc/nl-NL/acsengine.po.lcl
  loc/pl-PL/acsengine.po.lcl
  loc/pt-BR/acsengine.po.lcl
  loc/pt-PT/acsengine.po.lcl
  loc/ru-RU/acsengine.po.lcl
  loc/sv-SE/acsengine.po.lcl
  loc/tr-TR/acsengine.po.lcl
  loc/zh-CN/acsengine.po.lcl
  loc/zh-TW/acsengine.po.lcl
  scripts/convert-lcg-lcl.sh
Labels: approved, lgtm, size/XXL

#4039 fix: fixing an issue where windows cannot start kubelet to get podCID…
  staging/provisioning/windows/kubeletstart.ps1
Labels: approved, lgtm, size/XS

#4041 test: only test flannel + containerd thru k8s 1.19
  test/e2e/test_cluster_configs/flannel/containerd.json
Labels: size/XS

#4049 chore: format some json in addpool.md
  docs/topics/addpool.md
Labels: approved, lgtm, size/S

#4045 fix: always ensure etcd on control plane vms
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#4043 feat: add support for Kubernetes 1.18.12
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#4042 feat: add support for Kubernetes v1.19.4
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#4047 chore: Updating default csi-proxy version to v0.2.2
  pkg/api/azenvtypes.go
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#4011 feat: Enable chrony and host-based time sync by default on Ubuntu 18.04
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/scripts/time-sync-validate.sh
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#4030 fix: Windows and VMSS version validation for azs
  pkg/api/vlabs/validate.go
Labels: approved, lgtm, size/S

#4056 docs: fixed broken link in Azure Stack topic page
  docs/topics/azure-stack.md
Labels: approved, size/S

#4059 test: skip rotate docker log tests if omsagent
  test/e2e/test_cluster_configs/container_monitoring.json
Labels: size/XS

#4058 chore: Upgrade CNI to v1.2.0
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/const.go
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#4051 fix: persist VMSS name in API model
  cmd/addpool.go
  cmd/scale.go
  cmd/update.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/availabilityset.json
  test/e2e/test_cluster_configs/base.json
Labels: approved, lgtm, size/L

#4057 chore: only warn about master stuff during create
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#4053 chore: cleanup dead code
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/api/defaults.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/support_validator.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/kubernetes/scripts/time-sync-validate.sh
  test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
Labels: approved, lgtm, size/XXL

#4044 chore: mark Kubernetes 1.17.14 as disabled
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#4061 ci: use 3 replicas for no-vnet E2E jobs
  examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
Labels: approved, size/XS

#4060 fix: enforce Azure CNI config via jq instead of sed
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/dualstack.json
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/M
