Repository Azure/aks-engine, pull requests merged in 2020-09, with the labels that each got.

#3767 fix: availabilityZones value in template to read from parameter
  pkg/engine/virtualmachinescalesets.go
Labels: lgtm, size/XS

#3770 fix: update the flag due to using higher version of csi livenessprobe
  parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
  parts/k8s/addons/azurefile-csi-driver-deployment.yaml
  pkg/engine/templates_generated.go
Labels: lgtm, size/S

#3775 fix: update template for moby version validation
  parts/k8s/kubernetesparams.t
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
Labels: size/S

#3771 chore: update CNI plugins to v0.8.7
  pkg/api/const.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3773 chore: simplify addons config for calico and flannel
  parts/k8s/addons/1.15/calico.yaml
  parts/k8s/addons/calico.yaml
  parts/k8s/addons/flannel.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, lgtm, size/L

#3780 feat: add support for Kubernetes v1.16.15
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, lgtm, size/S

#3769 doc: update azure stack doc for aks-engine v0.55.0 (additional)
  docs/topics/azure-stack.md
Labels: lgtm, size/S

#3779 chore: update node-problem-detector addon to v0.8.4
  examples/addons/node-problem-detector/README.md
  examples/e2e-tests/kubernetes/release/default/definition.json
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/k8s_versions.go
  test/e2e/test_cluster_configs/everything.json
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3782 fix: mount certs directory in apiserver pod
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3794 test: remove tiller addon from PR E2E cluster configuration
  examples/e2e-tests/kubernetes/release/default/definition.json
Labels: approved, size/XS

#3790 chore: add keyVaultEndpoint to generated Azure Stack environment file
  pkg/api/apiloader_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/azurestack/kubernetes.json
  test/e2e/config/config.go
Labels: approved, azurestack, lgtm, size/S

#3800 fix: mount /etc/ssl/certs for apiserver
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3803 chore: get calico and v-k from mcr.microsoft.com
  docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml
  examples/addons/aci-connector/README.md
  pkg/api/azenvtypes.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3787 feat: secrets store addon can pull from custom env
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/engine/templates_generated.go
Labels: lgtm, size/S

#3811 chore: update Linux VHDs to 2020.09.08
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.09.08.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.09.08.txt
Labels: approved, size/XXL

#3774 fix: Enable Windows VHD version update in aks-engine upgrade scenario
  cmd/upgrade.go
Labels: approved, lgtm, size/S, windows

#3808 chore: remove apiserver /etc/kubernetes/certs mount
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3802 ci: updating pub to v0.2.6 to address publishing issues
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  vhd/publishing/add-image-version-to-sku.sh
Labels: VHD, approved, lgtm, size/S, windows

#3801 chore: targeting sept updates for Windows 2019 VHD
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: VHD, approved, size/XS, windows

#3793 chore: reduce customData payload
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/enable-dhcpv6.sh
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
  vhd/packer/packer_source.sh
  vhd/packer/vhd-image-builder-ubuntu-gen2.json
  vhd/packer/vhd-image-builder.json
Labels: approved, do-not-merge/hold, size/XL

#3809 fix: more resilient etcd systemd
  parts/k8s/cloud-init/artifacts/etcd.service
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3815 chore: pin virtual-kubelet to version 1.2.1.2
  examples/addons/aci-connector/README.md
  pkg/api/k8s_versions.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3795 chore: add K8s sept hotfix and 8b image
  pkg/api/azenvtypes.go
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: size/L

#3818 feat: Add T4 skus for samsung
  pkg/helpers/azureconst.go
Labels: size/S

#3747 test: add private key input to e2e suite + keep all junit result files
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/runner/cli_provisioner.go
Labels: lgtm, size/M

#3816 feat: add support for Kubernetes 1.19.1
  pkg/api/common/versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3805 fix: Allow to add more than one VNetCIDR to the exception list
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/templates_generated.go
Labels: aks, size/S, windows

#3804 feat: Add ACL rules for Windows
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/templates_generated.go
Labels: aks, size/M, windows

#3806 feat: Generate ARM template for Windows agent pool for different VHD images
  parts/windowsparams.t
  pkg/engine/params.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: aks, size/L, windows

#3821 fix: update GPU driver to 450.51.06 (#3814)
  docs/topics/gpu.md
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3820 fix: check if windows profile exists in upgrade
  cmd/upgrade.go
Labels: lgtm, size/XS, windows

#3813 docs: clarify project support policy in SUPPORT.md
  README.md
  SUPPORT.md
Labels: approved, area/docs, lgtm, size/S

#3824 test: set correct ssh private key for e2e get-logs
  test/e2e/cluster.sh
Labels: lgtm, size/XS

#3788 fix: working systemd monitor jobs
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/docker-monitor.service
  parts/k8s/cloud-init/artifacts/docker-monitor.timer
  parts/k8s/cloud-init/artifacts/etcd-monitor.service
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  parts/k8s/cloud-init/artifacts/kubelet-monitor.service
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/api/const.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/systemd-validate.sh
  vhd/packer/packer_source.sh
  vhd/packer/vhd-image-builder-ubuntu-gen2.json
  vhd/packer/vhd-image-builder.json
Labels: approved, lgtm, size/XL

#3667 feat: azure kms provider as static pod
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/kms.service
  parts/k8s/cloud-init/artifacts/kubelet.service
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/manifests/kubernetesmaster-azure-kubernetes-kms.yaml
  pkg/api/common/const.go
  pkg/api/components.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
  vhd/packer/packer_source.sh
  vhd/packer/vhd-image-builder-ubuntu-gen2.json
  vhd/packer/vhd-image-builder.json
Labels: lgtm, size/XL

#3822 fix: clean up stale CNI data regardless of HNS state
  staging/provisioning/windows/kubeletstart.ps1
Labels: approved, lgtm, size/M, windows

#3828 fix: update Azure Stack's Linux VHD to 2020.09.14
  pkg/api/defaults-custom-cloud-profile.go
Labels: size/XS

#3831 chore: validate Azure Stack's Linux VHD is in PIR
  pkg/api/azenvtypes.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/armhelpers/support_validator.go
Labels: lgtm, size/S

#3829 chore: update signed powershell script package to include azure CNI fixes
  pkg/api/const.go
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3827 chore: rev Linux VHDs to 2020.09.14
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.09.14.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.09.14.txt
Labels: approved, lgtm, size/XXL

#3826 docs: add required attribution reminder to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/docs, lgtm, size/S

#3792 fix: Azure Stack CNI network interfaces file creation fix
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/cse.go
  pkg/engine/templates_generated.go
  scripts/collect-logs.sh
  scripts/collect-windows-logs.ps1
Labels: lgtm, size/M

#3834 chore: adding 1.19.1 bits to Windows VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3836 revert: "chore: targeting sept updates for Windows 2019 VHD"
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS

#3835 docs: remove mention about library for AKS
  README.md
  docs/faq.md
Labels: approved, area/docs, lgtm, size/XS

#3830 feat: update VMSS node pools
  cmd/root.go
  cmd/root_test.go
  cmd/scale.go
  cmd/update.go
  cmd/updated_test.go
  docs/community/developer-guide.md
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/base.json
Labels: approved, lgtm, size/L

#3843 chore: updating Windows VHD with new cached artifacts
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.200917.txt
Labels: VHD, approved, lgtm, size/L, windows

#3840 feat: add support for Kubernetes v1.17.12
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3832 fix: Set all ip address ranges in vnetCidr
  pkg/engine/params.go
Labels: aks, size/XS

#3849 feat: update VHD version to 2020.09.17
  pkg/api/azenvtypes.go
Labels: size/XS

#3842 feat: add support for Kubernetes v1.19.2
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3846 docs: add v0.55.4 to supported Azure Stack versions
  docs/howto/troubleshooting.md
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack.json
  examples/azure-stack/kubernetes-windows.json
Labels: approved, area/docs, lgtm, size/S

#3850 test: add more E2E timeout tolerance
  .pipelines/e2e-job-template.yaml
Labels: approved, size/XS

#3841 feat: add support for Kubernetes v1.18.9
  pkg/api/common/versions.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/M

#3851 chore: remove no-op 1.15 version checks in templates
  parts/k8s/addons/azure-cloud-provider.yaml
  parts/k8s/addons/pod-security-policy.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#3852 fix: E2E scale scenario broken if update is false
  test/e2e/cluster.sh
Labels: approved, size/XS

#3853 ci: update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3799 chore: check VHD media name length before being published to Marketplace
  vhd/publishing/add-image-version-to-sku.sh
Labels: lgtm, size/XS

#3855 chore: update Dashboard addon to v2.0.4
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3862 fix: add #EOF sentinel chars to custom search file
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3864 chore: update azure cni to 1.1.7
  pkg/api/const.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3847 feat: Updating Windows VHD build files to support building for multiple OS versions
  .pipelines/vhd-builder-windows.yaml
  packer.mk
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-2004-vars.json
  vhd/packer/windows-2019-vars.json
  vhd/packer/windows-vhd-builder.json
Labels: VHD, approved, lgtm, size/L, windows

#3860 chore: distribute apiserver.crt to control plane nodes only
  cmd/rotate_certs.go
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3866 test: E2E optionally validates rotate-certs
  test/e2e/cluster.sh
Labels: approved, lgtm, size/M

#3869 docs: mark rotate-certs command as experimental
  cmd/rotate_certs.go
Labels: approved, size/XS

#3837 docs: CLI operations
  README.md
  cmd/addpool.go
  cmd/deploy.go
  cmd/scale.go
  docs/faq.md
  docs/topics/README.md
  docs/topics/aad.md
  docs/topics/addpool.md
  docs/topics/azure-stack.md
  docs/topics/creating_new_clusters.md
  docs/topics/get-logs.md
  docs/topics/kubernetes-developers.md
  docs/topics/scale.md
  docs/topics/update.md
  docs/topics/upgrade.md
  docs/tutorials/README.md
  docs/tutorials/cli-overview.md
  docs/tutorials/custom-vnet.md
  docs/tutorials/day2-operations.md
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
  examples/disks-storageaccount/README.md
  examples/keyvaultcerts/README.md
  examples/kubernetes-config/README.md
  examples/networkpolicy/README.md
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, area/docs, do-not-merge/hold, size/XXL

#3871 update vhd release
  pkg/api/azenvtypes.go
Labels: size/XS

#3877 docs: clarify that update is for node pools only
  docs/topics/update.md
  docs/tutorials/cli-overview.md
Labels: approved, size/XS

#3870 fix: Support ImageRef in WindowsProfile
  pkg/engine/params.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: aks, size/M

#3874 test: fix Azure Stack E2E cluster provisioner
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: area/e2e, azurestack, lgtm, size/S

#3857 fix: de-dup vnet roleAssignment deployments
  examples/e2e-tests/kubernetes/release/default/definition.json
  pkg/engine/armtype.go
  pkg/engine/masterarmresources.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/systemroleassignments.go
  pkg/engine/systemroleassignments_test.go
  test/e2e/azure/cli.go
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/everything.json
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/globaladministrator.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3876 chore: create azure.json via CSE
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3881 test: not nil defense broke logic
  test/e2e/engine/template.go
Labels: approved, size/XS
