Repository Azure/aks-engine, pull requests merged in 2020-04, with the labels that each got.

#2941 chore: return distinct CSE err for GPU drivers runtime configuration
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3002 fix: check dns status before connection
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/types.go
  pkg/engine/armresources_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: size/M

#2960 feat: add ability to use pre-existing user assigned MSI
  .pipelines/e2e-job-template.yaml
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/engine/armresources.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/keyvaults.go
  pkg/engine/masterarmresources.go
  pkg/engine/roleassignments.go
  pkg/engine/roleassignments_test.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/engine/template.go
Labels: size/L

#2967 feat: adding windows defender process exclusions
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S, windows

#2998 chore: use Standard LoadBalancer as default
  examples/dualstack/kubernetes.json
  examples/e2e-tests/kubernetes/release/default/definition.json
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/mocks.go
  pkg/engine/armvariables_test.go
  pkg/engine/testdata/mastersonly/mastersonly.json
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/zones.json
Labels: approved, size/M

#2970 feat: Updating Antrea version to v0.5.1
  parts/k8s/addons/antrea.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: size/L

#3019 docs: update `ask-engine deploy` example output
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
Labels: area/docs

#3000 feat: disable unneeded message-of-the-day sections
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#3020 style: format CSE scripts consistently
  parts/k8s/cloud-init/artifacts/cis.sh
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/enable-dhcpv6.sh
  parts/k8s/cloud-init/artifacts/generateproxycerts.sh
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  pkg/engine/templates_generated.go
Labels: size/XXL

#1681 fix: disable unattended upgrades during CSE execution
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: backlog, size/M

#3028 fix: make build with go 1.14 (#3005)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/curve25519/ladderstep_amd64.s
  vendor/golang.org/x/crypto/curve25519/mul_amd64.s
  vendor/golang.org/x/crypto/curve25519/square_amd64.s
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/internal/chacha20/asm_ppc64le.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/ssh_gss.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: aks

#2772 feat: "aks-engine get-skus" command
  Makefile
  cmd/get_locations.go
  cmd/get_skus.go
  cmd/get_skus_test.go
  cmd/root.go
  cmd/root_test.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/resourceskus.go
  pkg/armhelpers/azurestack/resourceskus_test.go
  pkg/armhelpers/httpMockClient.go
  pkg/armhelpers/httpMockClientData/listResourceSkus.json
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/resourceskus.go
  pkg/armhelpers/resourceskus_test.go
  pkg/helpers/azure_skus.go
  pkg/helpers/azure_skus_const.go
  pkg/helpers/generate_azure_constants.py
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  scripts/azure-const.sh
Labels: approved, size/XXL

#3011 fix: do some clean up before retry to install the gpu driver.
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: aks

#3036 bump the vhd version which contains the route table hotfix.
  pkg/api/azenvtypes.go
Labels: aks

#3041 feat: EncryptionAtHost support
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
Labels: do-not-merge/hold

#3060 feat: Updating AKS to use April 2020 Windows VHDs by default
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt
Labels: do-not-merge/hold

#3069 fix: disable unattended upgrades during CSE execution (#1681)
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: aks

#3064 feat: EncryptionAtHost support(cherry-pick to branch aks-release-v0.47.0-1)
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
Labels: aks

#2987 feat: "aks-engine get-logs" command
  cmd/get_logs.go
  cmd/get_logs_test.go
  cmd/root.go
  cmd/root_test.go
  docs/topics/get-logs.md
  go.sum
  pkg/helpers/ssh.go
  scripts/collect-logs.sh
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/base.json
  vhd/packer/packer_source.sh
  vhd/packer/vhd-image-builder.json
Labels: size/XL

#3078 fix: switch to use the 04.13 image which contains the cve patch.
  pkg/api/azenvtypes.go
Labels: aks

#2745 docs: get-logs proposal
  docs/design/get-logs.md
Labels: area/docs, size/M

#3099 docs: remove docker package and choco caveat from release docs
  docs/community/release-checklist.md
Labels: area/docs

#3103 docs: join the #aks-engine-users Slack channel (not #provider-azure)
  docs/community/README.md
Labels: area/docs

#2862 feat: Azure CNI dual stack support
  examples/dualstack/README.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/defaults-cloud-controller-manager.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources.go
  pkg/engine/masterarmresources.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualnetworks.go
  pkg/engine/virtualnetworks_test.go
Labels: do-not-merge/work-in-progress

#3109 fix: add nodeSelector for coredns-autoscaler
  parts/k8s/addons/coredns.yaml
  pkg/engine/templates_generated.go
Labels: needs-rebase

#2839 chore: update go compiler to 1.14.2
  .devcontainer.json
  .go-version
  .golangci.yml
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  docs/community/developer-guide.md
  go.mod
  go.sum
  hack/tools/Makefile
  makedev.ps1
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/transform/transform.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/helpers/pki.go
  test/e2e/go.mod
  test/e2e/go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/modules.txt
Labels: approved, size/XXL

#2759 feat: Enabling SSH on windows nodes by default
  cmd/get_logs.go
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M, windows

#3121 Upgrade Windows VHD image to April release 17763.1098.200409
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/engine/templates_generated.go
  scripts/collect-windows-logs.ps1
  test/e2e/test_cluster_configs/no_outbound.json
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt
Labels: aks

#3061 feat: add support for Kubernetes 1.18.1 (#3045)
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: aks

#3158 fix: don't hardcode pause image for containerD on Windows
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: windows

#3163 ci: disable artifact publishing
  .pipelines/e2e-step-template.yaml
Labels: approved, lgtm

#3164 chore: remove deprecated KUBELET_REGISTER_SCHEDULABLE
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm

#3165 chore: remove KUBELET_IMAGE kubelet systemd env var
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3166 chore: standardize to {{- for go template expressions
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#3169 chore: remove //+build !test pragma
  pkg/engine/engine_dcos.go
Labels: approved, lgtm, size/XS

#3161 chore: add support for K8s 1.17.4 & 1.17.5 on Azure Stack
  vhd/packer/install-dependencies.sh
Labels: size/XS

#3131 docs: document AKS Engine E2E
  README.md
  docs/community/developer-guide.md
  docs/community/e2e-output-example.log
  docs/community/running-tests.md
Labels: approved, lgtm, size/XXL

#3143 chore: aad-pod-identity taint
  parts/k8s/addons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/untaint-nodes.service
  parts/k8s/cloud-init/artifacts/untaint-nodes.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/common/const.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#2863 feat: configurable disk caching
  docs/topics/clusterdefinitions.md
  examples/e2e-tests/kubernetes/release/default/definition.json
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armresources_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/L
