Repository Azure/aks-engine, pull requests merged in 2020-10, with the labels that each got.

#3873 test: E2E fix scale test indexing out of bounds
  test/e2e/cluster.sh
Labels: approved, area/e2e, lgtm, size/XS

#3887 feat: Add Dv4 and DSv4 series SKU
  pkg/helpers/azureconst.go
Labels: size/M

#3888 feat: update vhd release to 2020.09.30
  pkg/api/azenvtypes.go
Labels: size/XS

#3884 docs: add notes about not upgrading LB config
  docs/topics/clusterdefinitions.md
  docs/topics/upgrade.md
Labels: approved, size/XS

#3886 docs: confirm flannel + docker is not supported
  docs/topics/clusterdefinitions.md
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, size/M

#3878 feat: allow custom containerd package for Linux nodes
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/cse.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/containerd.json
Labels: approved, do-not-merge/hold, lgtm, size/M

#3889 feat: add ScaleCPULimitsToSandbox for hyperv runtimeclasses
  parts/k8s/windowscontainerdfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3893 Revert "chore: update azure cni to 1.1.7"
  pkg/api/const.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: size/XS

#3891 chore: update csi-secrets-store addon manifest and images (v0.0.9)
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XL

#3892 ci: add containerd PR E2E tests
  .pipelines/e2e-job-template.yaml
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/release/default/definition.json
  test/e2e/engine/template.go
Labels: approved, size/M

#3894 fix: ensure addon hostNetwork ports don't conflict
  parts/k8s/addons/aad-pod-identity.yaml
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#3890 fix: don't warn about CRI update on cluster create
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, size/M

#3896 fix: fix jumpbox custom data
  parts/k8s/cloud-init/jumpboxcustomdata.yml
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3897 chore: enable VHD re-use in no outbound scenarios
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3903 ci: E2E fixes to allow more containerd tests
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
  test/e2e/engine/template.go
Labels: approved, size/L

#3905 feat: Target new windows VHD with new K8s binaries (1.19.2, 1.18.9, etc)
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.201006.txt
Labels: VHD, approved, lgtm, size/L, windows

#3904 ci: adding github actions to create nightly builds
  .github/workflows/nightly-build.yaml
Labels: approved, lgtm, size/M

#3906 chore: rev Linux VHDs to 2020.10.06
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.10.06.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.10.06.txt
Labels: approved, size/XXL

#3895 test: Add azure.json path for custom cloud k8s config & Update stability timeout for Azure CNI network policy
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: Azure Stack, lgtm, size/S

#3911 docs: adding instructions for how how to build the Windows VHD for di…
  .pipelines/vhd-builder-windows.yaml
  docs/howto/README.md
  docs/howto/building-vhds.md
  packer.mk
Labels: approved, lgtm, size/M

#3909 Set the csi-secrets-store to have a priority class
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/engine/templates_generated.go
Labels: lgtm, size/M

#3916 feat: 2020.10.08 vhd updates
  pkg/api/azenvtypes.go
Labels: size/XS

#3914 fix: remove NSG rules for AzureStack
  pkg/engine/networksecuritygroups.go
Labels: Azure Stack, lgtm, size/M

#3921 test: skip tests for flatcar cluster config
  test/e2e/test_cluster_configs/flatcar/flatcar.json
Labels: size/XS

#3922 fix: Azure Stack upgrade operations clear old MCR ImageBase
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#3923 ci: reduce addons area for containerd config tests
  examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
Labels: approved, size/S

#3924 bump calico to 3.8.9 to get latest patches
  pkg/api/k8s_versions.go
Labels: lgtm, size/XS

#3917 fix: VMSS control plane + availability zones
  pkg/engine/virtualmachinescalesets.go
  test/e2e/test_cluster_configs/vmss_master.json
Labels: approved, lgtm, size/S

#3907 chore: Upgrade CNI to v1.1.8
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#3932 test: CCM + azurefile + MSI test scenarios
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/cloud_controller_manager.json
Labels: approved, size/XS

#3931 remove static sku validation
  parts/agentparams.t
Labels: size/XS

#3936 fix generated template
  pkg/engine/templates_generated.go
Labels: size/L

#3938 chore: 2020.10.04 AKS Windows VHD update
  pkg/api/azenvtypes.go
Labels: aks, size/XS

#3943 chore: kubelet systemd job depends on CRI service
  parts/k8s/cloud-init/artifacts/kubelet.service
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3945 feat: Add VHD 2020.10.15
  pkg/api/azenvtypes.go
Labels: size/XS

#3929 fix: use InternalIP for metrics-server DNS resolution
  parts/k8s/addons/metrics-server.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3947 fix: sku for 2020.10.15 vhd
  pkg/api/azenvtypes.go
Labels: size/XS

#3918 feat: Support Windows 2004 with containerd + hyperv
  parts/k8s/containerdtemplate.toml
  parts/k8s/kubernetesparams.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/windowsparams.t
  pkg/api/const.go
  pkg/api/types.go
  pkg/engine/const.go
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: aks, size/XL

#3951 chore: Support 1.17.13 1.18.10 1.19.3 and add new k8s hotfix
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: aks, size/L

#3939 fix: get-logs command collects control plane logs even if apiserver is down
  cmd/get_logs.go
  cmd/get_logs_test.go
  scripts/collect-logs.sh
Labels: size/M

#3959 chore: update windows image version to 17763.1554.201021
  pkg/api/azenvtypes.go
Labels: size/XS

#3961 test: validate azure arc in everything config
  test/e2e/test_cluster_configs/arc/kubernetes-arc.json
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/M

#3963 chore: Add containerd support for Windows 2004
  parts/k8s/kubernetesparams.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscontainerdfunc.ps1
  pkg/engine/templates_generated.go
Labels: aks, size/L

#3957 refactor: delete Azure Stack's KubernetesClient implementation
  cmd/rotate_certs.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/azureclient.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/kubernetes/client.go
  pkg/kubernetes/interfaces.go
  pkg/operations/cordondrainvm.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/L

#3966 chore: update VHD 2020.10.21
  pkg/api/azenvtypes.go
Labels: size/S

#3967 docs: Remove double quotes(") at quickstart.md
  docs/tutorials/quickstart.md
Labels: lgtm, size/XS

#3953 fix: resource identifier not pass to custom cloud profile
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
Labels: approved, lgtm, size/L

#3940 feat: custom Windows log collection script
  cmd/get_logs.go
  cmd/get_logs_test.go
  docs/topics/get-logs.md
  pkg/api/types.go
Labels: size/L, windows

#3971 fix: page not done logic bug
  pkg/armhelpers/azurestack/resultPageClient.go
Labels: approved, lgtm, size/XS

#3972 fix: ensure flatcar configs use transparent Azure CNI
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/test_cluster_configs/flatcar/flatcar.json
Labels: approved, size/M

#3969 chore: longer default cordonDrainTimeout for Azure Stack Cloud
  cmd/upgrade.go
Labels: approved, lgtm, size/XS

#3962 test: Windows Metrics failure when High CPU
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/workloads/validate-windows-cpu-consumption.yaml
  test/e2e/test_cluster_configs/windows/reproductions/high-cpu.json
Labels: approved, lgtm, size/L

#3980 test: Jenkinsfile bool vars
  Jenkinsfile
  test/e2e/cluster.sh
Labels: approved, lgtm, size/XS

#3977 ci: Windows VHD pipeline tests
  .pipelines/vhd-builder-windows.yaml
  test/e2e/engine/template.go
  vhd/packer/sysprep.ps1
  vhd/packer/windows-vhd-builder.json
Labels: VHD, approved, lgtm, size/M, windows

#3937 feat: add support for Kubernetes v1.19.3
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#3942 feat: updates for container monitoring addon omsagent agent September 2020 release
  parts/k8s/addons/container-monitoring.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  test/e2e/kubernetes/kubernetes_test.go
Labels: do-not-merge/hold, lgtm, size/XL

#3970 fix: cancel Pod Eviction jobs when timeout
  pkg/operations/cordondrainvm.go
Labels: lgtm, size/M

#3976 test: Retry label when cluster first comes online
  test/e2e/kubernetes/node/node.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/M

#3982 chore: gofmt
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, size/S

#3981 test: "useManagedIdentity": false for VMSS masters
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/vmss_master.json
Labels: approved, size/XS

#3948 feat: add support for Kubernetes v1.18.10
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3958 chore: use transparent mode for Azure CNI
  examples/e2e-tests/kubernetes/release/default/definition.json
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/S

#3954 feat: add support for Kubernetes v1.17.13
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3934 feat: add support for Kubernetes v1.20.0-alpha.3
  .pipelines/pr-e2e.yaml
  Jenkinsfile
  cmd/generate_test.go
  examples/kubernetes-releases/kubernetes1.20.json
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#3879 chore: update go toolchain to v1.15.3
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  go.mod
  hack/tools/Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#3985 test: ensure azure-kms-provider E2E coverage
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
  examples/e2e-tests/kubernetes/release/default/definition.json
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/M

#3994 feat: add AKS linux VHD 2020.10.28
  pkg/api/azenvtypes.go
Labels: size/XS

#3991 feat: add support for Kubernetes v1.20.0-beta.0
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS
