Repository Azure/aks-engine, pull requests merged in 2020-03, with the labels that each got.

#2804 feat: Add IsCredentialAutoGenerated for WindowsProfile
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, lgtm

#2809 feat: release Windows VHD with 2C updates
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1075.200227.txt
Labels: windows

#2832 chore: default to large cluster settings on Azure Stack
  pkg/api/const.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: azurestack

#1322 wip: Windows containerd support
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/windows/kubernetes-hybrid.containerd.json
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/windowsparams.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/windows/kubernetes-kubernetesconfig.json
  scripts/build-windows-containerd.sh
Labels: approved, backlog, lgtm, size/XXL

#2781 feat: add support for single stack IPv6
  parts/k8s/addons/1.18/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/coredns.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/networkinterfaces.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualnetworks.go
Labels: size/L

#2635 feat: upgrade control plane only
  cmd/upgrade.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, do-not-merge/work-in-progress, size/S

#2890 fix: fixing nssm logging in windows CSE
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: windows

#2664 build: publish junit test results
  .pipelines/e2e-step-template.yaml
Labels: approved, lgtm, size/XS

#2911 feat: Updating AKS to use March 2020 Windows VHDs by default
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200315.txt
Labels: approved, lgtm, size/L, windows

#2912 docs: remove reference to raw Ubuntu from Azure Stack doc
  docs/topics/azure-stack.md
Labels: approved, area/docs, lgtm, size/XS

#2896 fix: add validation for new AKS engine Windows Version
  pkg/armhelpers/httpMockClient.go
  pkg/armhelpers/support_validator.go
  pkg/armhelpers/support_validator_test.go
Labels: approved, lgtm, size/M

#2915 fix: ensure label-nodes systemd service can be enabled
  parts/k8s/cloud-init/artifacts/label-nodes.service
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2908 fix: apply_network_config: false for 18.04-LTS
  .pipelines/pr-e2e.yaml
  cmd/generate_test.go
  examples/kubernetes-ubuntu-distros.json
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/remote/ssh.go
Labels: approved, lgtm, size/L

#2893 test: add test config to use gen2 images for agent pools
  .pipelines/pr-e2e.yaml
  cmd/generate_test.go
  examples/kubernetes-non-vhd-distros.json
  examples/kubernetes-ubuntu-distros.json
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/support_validator.go
  pkg/engine/armvariables_test.go
Labels: approved, lgtm, size/L

#2917 docs: ubuntu-18.04-gen2 distro
  docs/topics/clusterdefinitions.md
Labels: size/XS

#2904 test: create functions in network policy specific file and let tests call it.
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/namespace/namespace.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
Labels: lgtm, size/L

#2886 fix: honor custom{component}Image fields
  parts/k8s/kubernetesparams.t
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/components.go
  pkg/api/components_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: lgtm

#2906 fix: scale cannot find VM index for the VMAS+VHD+Linux case
  cmd/scale.go
  test/e2e/test_cluster_configs/availabilityset.json
Labels: approved, lgtm, size/S

#2907 fix: do not remove VMAS resources from template when adding a VMAS pool
  cmd/addpool.go
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/k8s_addpool_vmas.json
  test/e2e/test_cluster_configs/availabilityset.json
Labels: lgtm, size/XXL

#2922 test: only use 1 node per pool in no outbound test
  test/e2e/test_cluster_configs/no_outbound.json
Labels: size/XS

#2924 test: better skip test implementation
  test/e2e/runner/cli_provisioner.go
Labels: size/S

#2921 test: skip node ready test after scale down
  test/e2e/test_cluster_configs/base.json
Labels: approved, size/XS

#2914 fix: parse SGX driver url and compare checksum
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2918 chore: rev AKS Engine Linux VHDs to 2020.03.16
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202003_2020.03.16.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202003_2020.03.16.txt
Labels: approved, lgtm, size/L

#2926 test: simplified availabilityset E2E cluster config
  test/e2e/test_cluster_configs/availabilityset.json
Labels: approved, size/M

#2919 fix: check network from node to k8s api server in CSE
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: lgtm, size/S

#2854 feat: install Windows csi proxy during cluster creation
  docs/topics/clusterdefinitions.md
  docs/topics/csi-proxy-windows.md
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscsiproxyfunc.ps1
  parts/k8s/windowsnodereset.ps1
  pkg/api/common/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2929 fix: use explicit kubeconfig in label-nodes.sh
  parts/k8s/cloud-init/artifacts/label-nodes.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2905 feat: add UltraSSD support
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/test_cluster_configs/zones.json
Labels: lgtm, size/L

#2815 fix: use ntp instead of systemd-timesyncd in 18.04
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/kubernetes/scripts/time-sync-validate.sh
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2934 fix: $ERR_SYSTEMCTL_STOP_FAIL VHD CI errata
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2932 chore: rev default Kubernetes version to 1.15
  examples/e2e-tests/kubernetes/kubernetes-config/rbac-disabled.json
  pkg/api/common/const.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/M

#2930 feat: installing csi-proxy for windows at node deployment time
  docs/topics/clusterdefinitions.md
  docs/topics/csi-proxy-windows.md
  go.mod
  go.sum
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscsiproxyfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodereset.ps1
  pkg/api/common/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  test/e2e/go.sum
Labels: approved, lgtm, size/L

#2935 chore: improve --client-id flag validation message
  cmd/root.go
  cmd/root_test.go
Labels: approved, lgtm, size/L

#2939 chore: rev Linux VHDs to 2020.03.19
  .pipelines/pr-e2e.yaml
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202003_2020.03.19.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202003_2020.03.19.txt
Labels: approved, size/L

#2942 refactor: Parse sgx dcap version file, enable checksum
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2903 chore: update azure-policy addon versions
  examples/addons/azure-policy/README.md
  examples/addons/azure-policy/azure-policy.json
  parts/k8s/addons/azure-policy-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/XL

#2944 chore: update etcd to 3.3.19
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#2931 chore: optimize apt_get_purge CSE func
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#2951 test: don't test version if customWindowsPackageURL
  test/e2e/kubernetes/kubernetes_test.go
Labels: lgtm, size/XS

#2925 test: add egress tests which target pod and namespace.
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
  test/e2e/kubernetes/workloads/policies/backend-policy-allow-egress-pod-label.yaml
  test/e2e/kubernetes/workloads/policies/backend-policy-allow-egress-pod-namespace-label.yaml
Labels: lgtm, size/M

#2920 docs: update examples location for zh docs
  docs/topics/clusterdefinitions.zh-CN.md
  docs/tutorials/quickstart.zh-CN.md
Labels: area/docs, lgtm, size/S

#2958 ci: new VHD pipeline definition for Ubuntu + gen2 images
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  packer.mk
  vhd/packer/vhd-image-builder-ubuntu-gen2.json
Labels: approved, size/L

#2954 fix: Get WindowsVersion from registry instead of calling Get-ComputerInfo
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsinstallopensshfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M, windows

#2938 fix: check network to k8s api for vmss
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/M

#2966 test: don't grab ps logs during E2E operation
  test/e2e/runner/cli_provisioner.go
Labels: size/XS

#2945 feat: deprecate CoreOS support
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/coreos/kubernetes-coreos-hybrid.json
  examples/coreos/kubernetes-coreos.json
  examples/e2e-tests/kubernetes/coreos/coreos.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/support_validator.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
Labels: approved, lgtm, size/XL

#2959 fix: add NVv3 series to NVidia driver install list
  pkg/api/common/helper.go
Labels: approved, lgtm, size/S

#2964 test: promote --failFast to an e2e flag, defaulting to false
  test/e2e/config/config.go
  test/e2e/runner/ginkgo.go
Labels: approved, lgtm, size/XS

#2962 fix: use upstreamartifacts CDN URL for apmz
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2957 feat: add support for Kubernetes 1.18.0
  pkg/api/common/versions.go
  pkg/api/components_test.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2965 Cherry pick: check network to k8s api server
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: size/M

#2974 chore: force Basic LB SKU on Azure Stack
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: lgtm, size/S

#2975 test: reduce PR E2E cluster jobs
  .pipelines/e2e-job-template.yaml
  .pipelines/pr-e2e.yaml
  examples/e2e-tests/kubernetes/release/default/definition.json
Labels: approved, size/L

#2977 fix: add NVv3 series to NVidia driver install list (#2959)
  pkg/api/common/helper.go
Labels: size/S

#2978 chore: don't re-run provision.sh if already called. (#2843)
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
  pkg/engine/vmextensions.go
Labels: lgtm, size/S

#2976 chore: switch dev image to go 1.13 version
  .devcontainer.json
  .go-version
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  docs/community/developer-guide.md
  go.mod
  makedev.ps1
Labels: approved, lgtm, size/S

#2980 test: use 1.17 for E2E
  .pipelines/pr-e2e.yaml
Labels: approved, lgtm, size/XS

#2981 fix: use same cluster-autoscaler version in MCR
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#2982 feat: add support for Kubernetes 1.19.0-alpha.1
  Jenkinsfile
  cmd/generate_test.go
  examples/kubernetes-releases/kubernetes1.19.json
  parts/k8s/addons/1.19/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.19/ip-masq-agent.yaml
  parts/k8s/addons/1.19/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-tiller-deployment.yaml
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2953 fix: each apiserver process listens on its own IP address
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/busybox-master.yaml
Labels: approved, lgtm, size/M

#2864 feat: Windows containerd + azure-cni
  examples/windows/kubernetes-hybrid.azure-containerd.json
  examples/windows/kubernetes-hybrid.kubenet-containerd.json
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscontainerdfunc.ps1
  pkg/api/vlabs/validate.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2988 docs: include Basic LB SKU limitations in Azure Stack page
  docs/topics/azure-stack.md
Labels: area/docs, azurestack, size/L

#2936 feat: add csi-secrets-store addon
  docs/topics/clusterdefinitions.md
  examples/addons/csi-secrets-store/README.md
  examples/addons/csi-secrets-store/kubernetes-csi-secrets-store.json
  parts/k8s/addons/kubernetesmasteraddons-secrets-store-csi-driver-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XXL

#2991 fix: change gatekeeper namespace in azure-policy addon
  examples/addons/azure-policy/README.md
  examples/addons/azure-policy/azure-policy.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  parts/k8s/addons/azure-policy-deployment.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/k8s_versions.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/L

#2989 feat: etcd metrics URL
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2996 feat: cherry pick changes from master to support kubernetes 1.18
  docs/topics/clusterdefinitions.md
  docs/topics/csi-proxy-windows.md
  docs/topics/features.md
  examples/dualstack/README.md
  examples/windows/kubernetes-hybrid.containerd.json
  go.mod
  go.sum
  parts/k8s/addons/1.18/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/coredns.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/k8s/windowscsiproxyfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodereset.ps1
  parts/windowsparams.t
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/common/versions.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/networkinterfaces.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/windows/kubernetes-kubernetesconfig.json
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualnetworks.go
  scripts/build-windows-containerd.sh
  test/e2e/go.sum
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: size/XXL

#2997 test: UT for addons ip-masq-agent image override
  pkg/api/addons_test.go
Labels: approved, size/M

#2999 chore: remove mlocate if auditd disabled
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS
