Repository Azure/aks-engine, pull requests merged in 2020-07, with the labels that each got.

#3565 docs: fix incorrect calico addons section heading
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/XS

#3566 test: ensure all resource creation attempts are retried
  test/e2e/kubernetes/daemonset/daemonset.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/storageclass/storageclass.go
Labels: approved, size/XL

#3569 feat: Add aks custom cloud env
  pkg/api/types.go
Labels: size/M

#3559 Revert "Revert "feat: enable alternate kube-reserved cgroups (#3530)""
  docs/topics/clusterdefinitions.md
  examples/kubernetes-config/kubernetes-kube-reserved.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
Labels: aks, lgtm, size/L

#3560 test: testing the recommended flow of sgx-device-plugin
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/sgx-device-plugin-before-k8s-1-17.yaml
  test/e2e/kubernetes/workloads/sgx-device-plugin.yaml
  test/e2e/kubernetes/workloads/sgx-test-with-plugin.yaml
Labels: lgtm, size/L

#3556 feat: reconcile private hosts for AKS BYO DNS
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#3441 feat: Consume signed powershell scripts
  docs/topics/clusterdefinitions.md
  docs/topics/windows-provisioning-scripts.md
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/api/azenvtypes.go
  pkg/api/azenvtypes_test.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  scripts/build-windows-provisioning-scripts.sh
  scripts/validate-windows-provisioning-scripts.sh
  staging/provisioning/windows/kubeletstart.ps1
  staging/provisioning/windows/kubeproxystart.ps1
  staging/provisioning/windows/windowslogscleanup.ps1
  staging/provisioning/windows/windowsnodereset.ps1
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, size/XXL, windows

#3571 chore: set update strategy for the azure-cnms addon
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/addons/azure-network-policy.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3570 fix: kube-proxy upgrade from v1.15 to v1.16
  cmd/upgrade.go
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
  test/e2e/kubernetes/daemonset/daemonset.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#3576 Add AKS VHD version 2020.06.30
  pkg/api/azenvtypes.go
Labels: size/S

#3577 chore: add VHD with signed powershell scripts
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200702.txt
Labels: VHD, approved, size/L, windows

#3572 feat: add hosts config agent support for Windows nodes
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowshostsconfigagentfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  staging/provisioning/windows/hostsconfigagent.ps1
  staging/provisioning/windows/windowsnodereset.ps1
Labels: lgtm, size/L, windows

#3579 fix: validate signed powershell packages in Azure and China Cloud
  docs/topics/windows-provisioning-scripts.md
  scripts/validate-windows-provisioning-scripts.sh
Labels: approved, size/M

#3582 test: e2e driver pass identity system to upgrade and scale commands
  test/e2e/cluster.sh
Labels: lgtm, size/XS

#3583 feat: etcdStorageLimitGB for configurable etcd storage limit
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/L

#3585 enable /etc/hosts config agent for AKS private cluster BYO DNS
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: size/L

#3549 chore: Use moby 19.03.x packages
  .pipelines/e2e-step-template.yaml
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#3588 test: don't return from GetAllRunningByLabelWithRetry until we have pods
  test/e2e/kubernetes/pod/pod.go
Labels: approved, lgtm, size/XS

#3591 test: set default IDENTITY_SYSTEM
  test/e2e/cluster.sh
Labels: approved, size/XS

#3587 fix: use mcr.azk8s.cn for Azure CNI networkmonitor in China cloud
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#3574 fix: always extract kubelet and kubectl from a custom URL if defined
  docs/topics/kubernetes-developers.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/custom-hyperkube-validate.sh
  test/e2e/test_cluster_configs/custom_hyperkube.json
Labels: approved, lgtm, size/L

#3590 fix: use correct VMSS name comparison during Windows scale
  cmd/scale.go
Labels: approved, size/M

#3592 switch to use the new 07 vhd.
  pkg/api/azenvtypes.go
Labels: size/S

#3593 chore: switch to use the 07 vhd for gpu too.
  pkg/api/azenvtypes.go
Labels: aks, size/XS

#3584 chore: Update the signed powershell package version
  pkg/api/const.go
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#3596 chore: update go toolchain to 1.14.4
  .devcontainer.json
  .go-version
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  docs/community/developer-guide.md
  hack/tools/Makefile
  makedev.ps1
  pkg/api/addons.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
Labels: approved, lgtm, size/L

#3599 fix: updating hotfix packages used for windows inlcuding CVE and metric
  pkg/api/k8s_versions.go
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, lgtm, size/M, windows

#3604 feat: add support for Kubernetes 1.18.6
  pkg/api/common/versions.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3603 feat: add support for Kubernetes 1.17.9
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#3598 chore: July 2020 windows patches
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: VHD, size/XS, windows

#3610 chore: Cherrypick July patches to v0.53.0
  pkg/api/k8s_versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: VHD, aks, size/M, windows

#3606 chore: update Dashboard addon to v2.0.3
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3611 feat: Update VHD version 2020.07.16 and remove GPU VHDs
  pkg/api/azenvtypes.go
Labels: size/M

#3614 chore: Add Windows VHD with 7B
  pkg/api/azenvtypes.go
  pkg/api/k8s_versions.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-aks-17763.1339.200717.txt
Labels: lgtm, size/L

#3615 chore: remove more GPU image config
  pkg/armhelpers/support_validator.go
Labels: size/XS

#3616 feat: Add K8s1.16.13/1.17.9/1.18.6 for AKS
  pkg/api/common/versions.go
Labels: size/XS

#3594 feat: Support configurable Windows PauseImage
  docs/topics/clusterdefinitions.md
  examples/windows/kubernetes-pause-image.json
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
Labels: size/L, windows

#3617 chore: Release v0.53.0 update vhd with July patches
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-aks-17763.1339.200717.txt
Labels: size/L

#3608 chore: update CoreDNS to v1.7.0
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3602 feat: add support for Kubernetes 1.16.13
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3613 chore: add support for K8s v1.16.13 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#3612 chore: add support for k8s v1.17.9 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3619 chore: update Windows default VHD for July
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1339.200716.txt
Labels: VHD, lgtm, size/L, windows

#3625 fix: reinforce MCR migration during upgrade for older clusters
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, size/M

#3627 test: run pod schedule tests first
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#3635 test: move E2E global vars out of "not block ssh port" conditional block
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#3636 chore: bump cloud-controller-manager and cloud-node-manager to v0.5.1
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3629 feat: Set vnetCidr by the address space of the vnet
  pkg/engine/params.go
  pkg/engine/params_test.go
Labels: lgtm, size/L

#3638 test: don't run kubelet restart test if ssh is blocked
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#3630 chore: Pick signed powershell scripts, containerd, vhd 7b and hosts config agent support for Windows
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/k8s/windowscsiproxyfunc.ps1
  parts/k8s/windowshostsconfigagentfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/windowsparams.t
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/const.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  staging/provisioning/windows/hostsconfigagent.ps1
  staging/provisioning/windows/kubeletstart.ps1
  staging/provisioning/windows/kubeproxystart.ps1
  staging/provisioning/windows/windowslogscleanup.ps1
  staging/provisioning/windows/windowsnodereset.ps1
  vhd/packer/configure-windows-vhd.ps1
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1339.200716.txt
Labels: size/XXL

#3640 chore: update Windows default VHD for July (#3619)
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1339.200717.txt
Labels: lgtm, size/XS

#3643 feat: Support configurable Windows PauseImage (#3594)
  docs/topics/clusterdefinitions.md
  examples/windows/kubernetes-pause-image.json
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/azenvtypes.go
  pkg/api/vlabs/types.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/templates_generated.go
Labels: size/XL

#3644 chore: Upgrade CNI to v1.1.6
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#3649 chore: rev Linux VHDs to 2020.07.24
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.07.24.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.07.24.txt
Labels: approved, lgtm, size/L

#3641 fix: update windows docker version to fix log rotation error
  pkg/api/const.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/validate-windows-logging.yaml
Labels: approved, size/L, windows

#3654 fix: only remove CRI if re-installing
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, size/M

#3651 chore: Only use Windows telemetry client when enableTelemetry is true
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
Labels: aks, lgtm, size/L

#3652 feat: Add aks custom cloud and CSIProxyURL
  pkg/api/azenvtypes.go
  pkg/api/defaults-custom-cloud-profile.go
  pkg/api/defaults.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: aks, lgtm, size/S

#3653 feat: add support for Kubernetes 1.19.0-rc.3
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS
