Repository Azure/aks-engine, pull requests merged in 2020-01, with the labels that each got.

#2509 fix: add "Standard_DS3_v2" to "AcceleratedNetworking" supported list
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, lgtm, size/XS

#2512 fix: add "Standard_DS3_v2" to "AcceleratedNetworking" supported list (#2509)
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: size/XS

#2520 ci: collect logs during E2E runs
  test/e2e/runner.go
Labels: approved, lgtm, size/S

#2517 refactor: user-configurable flannel and scheduled maintenance addons
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/containeraddons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/containeraddons/1.17/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-scheduled-maintenance-deployment.yaml
  pkg/api/addons.go
  pkg/api/common/const.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/flannel/docker.json
Labels: approved, lgtm, size/XXL

#2521 chore: Updating Azure NPM to v1.0.31
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#2503 feat: add support for Kubernetes 1.18.0-alpha.1
  .pipelines/e2e-job-template.yaml
  .pipelines/pr-e2e.yaml
  Jenkinsfile
  cmd/generate_test.go
  examples/kubernetes-releases/kubernetes1.18.json
  parts/k8s/containeraddons/1.18/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/1.18/ip-masq-agent.yaml
  parts/k8s/containeraddons/1.18/kubernetesmaster-audit-policy.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/containeraddons/1.18/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-scheduler.yaml
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2524 test: don't test non-working >= 1.16 flannel + docker
  test/e2e/test_cluster_configs/flannel/docker.json
Labels: size/XS

#2467 fix: apply new master node labels for k8s v1.18+ compatibility
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#2504 feat: cleaning up old kubelet/kubeproxy logs for Windows nodes
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowslogscleanup.ps1
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L, windows

#2513 fix: configure addons before setting kubelet config
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: lgtm, size/L

#2527 chore: update addon-resizer
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#2535 fix: aci-connector region is ignored
  parts/k8s/addons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-aci-connector-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2542 test: use LOCATION env var for api model in E2E tests
  test/e2e/engine/template.go
Labels: approved, size/XS

#2533 fix: promote system addons to system-cluster-critical
  parts/k8s/addons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2536 test: use northeurope for byok testing
  test/e2e/test_cluster_configs/byok.json
Labels: approved, size/XS

#2544 test: use vanilla busybox image for E2E tests
  test/e2e/kubernetes/workloads/dns-liveness.yaml
Labels: approved, lgtm, size/XS

#2481 feat: update containermonitoring addon for december release
  parts/k8s/addons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  test/e2e/test_cluster_configs/container_monitoring.json
Labels: approved, lgtm, size/XXL

#2537 feat: build pipeline to create new marketplace vhd skus for windows
  .pipelines/marketplace-sku.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  vhd/publishing/new-windows-sku.sh
  vhd/publishing/windows-sku-template.json
Labels: approved, lgtm, size/L

#2546 perf: upgrade AKS tunnel image in VHD
  packer/install-dependencies.sh
Labels: lgtm, size/XS

#2529 feat: create windows vhd publishing file in build pipeline
  .pipelines/vhd-builder-windows.yaml
  packer.mk
  packer/generate-windows-vhd-publishing-info.sh
Labels: approved, lgtm, size/M, windows

#2554 fix: Remove PodPriority feature gate
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/S

#2556 fix: marketplace-sku.yaml - fix for secret variables
  .pipelines/marketplace-sku.yaml
Labels: approved, lgtm, size/XS

#2555 chore: bump coredns to v1.6.6
  packer/install-dependencies.sh
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#2564 chore: update VHD references to 2020.01.10
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.10.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.10.txt
  test/e2e/test_cluster_configs/no_outbound.json
Labels: approved, lgtm, size/L

#2547 feat: Azure Spot VMSS
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  examples/kubernetes-vmss-spot/kubernetes.json
  parts/agentparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner/cli_provisioner.go
  test/e2e/test_cluster_configs/base.json
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/flannel/docker.json
  test/e2e/test_cluster_configs/gpu.json
  test/e2e/test_cluster_configs/kube-dns.json
  test/e2e/test_cluster_configs/kubenet.json
  test/e2e/test_cluster_configs/large-vm-sku.json
  test/e2e/test_cluster_configs/network_policy/antrea.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/no_outbound.json
  test/e2e/test_cluster_configs/not_in_vhd.json
  test/e2e/test_cluster_configs/rbac_disabled.json
  test/e2e/test_cluster_configs/ubuntu_distro.json
  test/e2e/test_cluster_configs/vmss_master.json
  test/e2e/test_cluster_configs/windows/custom_image.json
  test/e2e/test_cluster_configs/windows/custom_vnet.json
  test/e2e/test_cluster_configs/windows/image_reference.json
  test/e2e/test_cluster_configs/windows/shared_image_gallery.json
  test/e2e/test_cluster_configs/windows/vhd_url.json
Labels: approved, lgtm, size/L

#2565 fix: k8s component versions errata
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
Labels: approved, lgtm, size/L

#2566 fix: update list of SKUs with accelerated networking support
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, lgtm, size/M

#2570 fix: don't configure password for "etcd" user
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2571 feat: Azure Spot VMSS (#2547)
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  examples/kubernetes-vmss-spot/kubernetes.json
  parts/agentparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner/cli_provisioner.go
  test/e2e/test_cluster_configs/base.json
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/flannel/containerd.json
  test/e2e/test_cluster_configs/flannel/docker.json
  test/e2e/test_cluster_configs/gpu.json
  test/e2e/test_cluster_configs/kube-dns.json
  test/e2e/test_cluster_configs/kubenet.json
  test/e2e/test_cluster_configs/large-vm-sku.json
  test/e2e/test_cluster_configs/network/cilium.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/no_outbound.json
  test/e2e/test_cluster_configs/not_in_vhd.json
  test/e2e/test_cluster_configs/rbac_disabled.json
  test/e2e/test_cluster_configs/ubuntu_distro.json
  test/e2e/test_cluster_configs/vmss_master.json
  test/e2e/test_cluster_configs/windows/custom_image.json
  test/e2e/test_cluster_configs/windows/custom_vnet.json
  test/e2e/test_cluster_configs/windows/image_reference.json
  test/e2e/test_cluster_configs/windows/shared_image_gallery.json
  test/e2e/test_cluster_configs/windows/vhd_url.json
Labels: size/L

#2567 feat: Win vhd release pipeline
  vhd/publishing/add-image-version-to-sku.sh
Labels: approved, size/M

#2400 feat: Cse tracing for windows nodes
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2576 test: don't run ssh tests on spot vmss pools
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#2578 ci: add AvailabilitySet + SLB E2E scenario
  test/e2e/test_cluster_configs/availabilityset-standard-lb.json
Labels: approved, lgtm, size/M

#2579 feat: add support for Kubernetes 1.17.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2581 feat: Set the default Windows sku and version when upgrading a VMSS
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L, windows

#2415 feat: add linux CSE tracing and metrics
  examples/kubernetes.json
  packer/install-dependencies.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2585 chore: lint
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
Labels: size/S

#2572 fix: enable SLB with private clusters
  pkg/engine/armresources.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/ipaddresses.go
  pkg/engine/ipaddresses_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/test_cluster_configs/private_cluster/basic_lb_1_master.json
  test/e2e/test_cluster_configs/private_cluster/basic_lb_3_masters.json
  test/e2e/test_cluster_configs/private_cluster/standard_lb_1_master.json
  test/e2e/test_cluster_configs/private_cluster/standard_lb_3_masters.json
Labels: approved, lgtm, size/XXL

#2597 feat: Set the default Windows sku and version when upgrading a VMSS
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: lgtm, size/L

#2598 chore: update VHD references to 2020.01.10 (#2564)
  pkg/api/azenvtypes.go
  releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.10.txt
  releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.10.txt
  test/e2e/test_cluster_configs/no_outbound.json
Labels: size/L

#2591 build: fetch img tool from upstreamartifacts storage
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2557 feat: Add Node Pool
  Jenkinsfile
  cmd/addpool.go
  cmd/addpool_test.go
  cmd/root.go
  cmd/root_test.go
  examples/addpool/addpool.sh
  examples/addpool/agentpool.json
  examples/addpool/apimodel.json
  pkg/api/apiloader.go
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/base.json
Labels: size/XL

#2594 fix: Fix e2e test failure
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/util/util.go
  test/e2e/kubernetes/workloads/pod-pvc.yaml
  test/e2e/kubernetes/workloads/pvc-azuredisk.yaml
  test/e2e/test_cluster_configs/availabilityset.json
  test/e2e/test_cluster_configs/sgx.json
Labels: approved, lgtm, size/M

#2599 test: fix unset ADD_NODE_POOL_INPUT var in cluster.sh test script
  test/e2e/cluster.sh
Labels: approved, size/XS

#2600 chore: update VHD references to 2020.01.15
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.15.txt
  vhd/release-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.15.txt
Labels: approved, lgtm, size/L

#2595 fix: Moving publish release notes step after e2e test runs so windows …
  .pipelines/vhd-builder-windows.yaml
Labels: approved, size/S

#2603 feat: Updating aks-windows vhd to to include jan patches
  vhd/packer/windows-vhd-builder.json
Labels: approved, size/XS

#2607 chore: Adding 1.17.1 package to windows vhd
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, size/XS

#2604 fix: Skip storage class e2e test when ephemeral disk is used
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/util/util.go
Labels: lgtm, size/S

#2610 feat: add support for Kubernetes 1.18.0-alpha.2
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2602 docs: remove VHD code comment suggesting registry is temporary
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2612 feat: add support for Kubernetes 1.17.2
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2589 feat: add support for Kubernetes 1.15.9
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#2586 test: consolidate E2E test cluster configurations
  Jenkinsfile
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/cuda-vector-add.yaml
  test/e2e/kubernetes/workloads/nvidia-smi.yaml
  test/e2e/test_cluster_configs/availabilityset-standard-lb.json
  test/e2e/test_cluster_configs/base.json
  test/e2e/test_cluster_configs/byok.json
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/gpu.json
  test/e2e/test_cluster_configs/kube-dns.json
  test/e2e/test_cluster_configs/large-vm-sku.json
  test/e2e/test_cluster_configs/not_in_vhd.json
  test/e2e/test_cluster_configs/rbac_disabled.json
  test/e2e/test_cluster_configs/sgx.json
  test/e2e/test_cluster_configs/storage_profile.json
  test/e2e/test_cluster_configs/ubuntu_distro.json
  test/e2e/test_cluster_configs/windows/custom_vnet.json
  test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json
  test/e2e/test_cluster_configs/zones.json
Labels: approved, size/XL

#2615 feat: fetching collect-windows-logs.ps1 during windows CSE
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, size/S

#2588 feat: add support for Kubernetes 1.16.6
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#2619 test: don't test for static node count if add node pool context
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#2620 test: configurable pvc E2E tests
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/XS

#2534 chore: update go-dev tools image
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  hack/tools/Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#2583 fix: create role assignment for master VMs
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armtype.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/masterarmresources.go
  pkg/engine/systemroleassignments.go
  pkg/engine/systemroleassignments_test.go
Labels: lgtm, size/XL

#2530 chore: Updating NPM CPU and Memory requests and limits
  parts/k8s/addons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2626 test: HPA/cluster-autoscaler fixes so we don't scale up too many pods
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#2625 test: modify vm sku during e2e upgrade tests
  test/e2e/cluster.sh
Labels: approved, size/S

#2629 test: allow cluster-autoscaler more nodes in everything test config
  test/e2e/test_cluster_configs/everything.json
Labels: size/XS

#2633 test: zones aren't available everywhere
  test/e2e/test_cluster_configs/cloud_controller_manager_zones.json
Labels: size/S

#2342 feat: validate VHD availability on azurestack
  cmd/deploy.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/azureclient.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/httpMockClientData/getVirtualMachineImage.json
  pkg/armhelpers/azurestack/httpMockClientData/listVirtualMachineImages.json
  pkg/armhelpers/azurestack/vmImage.go
  pkg/armhelpers/azurestack/vmImage_test.go
  pkg/armhelpers/httpMockClient.go
  pkg/armhelpers/httpMockClientData/getVirtualMachineImage.json
  pkg/armhelpers/httpMockClientData/listVirtualMachineImages.json
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/support_validator.go
  pkg/armhelpers/support_validator_test.go
  pkg/armhelpers/vmImage.go
  pkg/armhelpers/vmImage_test.go
Labels: approved, lgtm, size/XL

#2632 revert: "chore: update go-dev tools image (#2534)"
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  hack/tools/Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#2628 chore: support v1.15.9 on Azure Stack
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2639 fix: custom kube-controller-manager template should reference hyperkube
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  pkg/engine/templates_generated.go
Labels: approved, azurestack, lgtm, size/XS

#2627 chore: update Azure cloud-provider components to v0.4.1
  pkg/api/k8s_versions.go
  pkg/engine/template_generator_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#2636 feat: updating aks-engine to use jan windows images by default
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.973.200123.txt
Labels: approved, lgtm, size/L

#2646 fix: private cluster + multiple masters in backend ILB pool
  pkg/engine/networkinterfaces.go
  pkg/engine/networkinterfaces_test.go
Labels: approved, lgtm, size/S

#2647 feat: add new Standard_DC[x]s_v2 VM SKUs
  pkg/helpers/azureconst.go
Labels: approved, lgtm, size/S

#2593 build: fetch azure-vnet-cni from kubernetesartifacts storage
  parts/k8s/kubernetesparams.t
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMResponse.json
  pkg/engine/templates_generated.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2640 refactor: stop using type nesting in billing extensions
  pkg/engine/virtualmachinescalesets.go
Labels: approved, lgtm, size/XS

#2526 fix: default LB AllocatedOutboundPorts to 0
  pkg/engine/armresources_test.go
  pkg/engine/loadbalancers.go
  pkg/engine/loadbalancers_test.go
Labels: approved, size/M

#2613 chore: Bump moby to 3.0.10
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#2634 fix: enable upgrade in private cluster + jumpbox scenario
  docs/topics/upgrade.md
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/transform/transformtestfiles/k8s_template_jumpbox.json
  pkg/engine/transform/transformtestfiles/k8s_upgrade_template_jumpbox.json
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/XXL

#2617 build: fetch cni-plugins from kubernetesartifacts storage
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/azenvtypes.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMResponse.json
  pkg/engine/templates_generated.go
  pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2644 build: fetch etcd from MCR container image
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/azenvtypes.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#2643 fix: make Windows scaling work
  cmd/scale.go
Labels: approved, size/S

#2653 fix: persist new pool after addpool operation
  cmd/addpool.go
Labels: approved, size/XS

#2650 chore: use IsVMSSToBeUpgraded func to validate vmss pools in upgrade
  cmd/upgrade.go
  cmd/upgrade_test.go
Labels: approved, lgtm, size/L

#2623 docs: add support note to main readme
  README.md
Labels: approved, lgtm, size/XS

#2654 fix: remove extra param from 'systemctl_restart' invocation
  parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2656 docs: refer to kubernetesartifacts storage in examples and comments
  pkg/api/vlabs/validate.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMResponse.json
  pkg/engine/transform/transformtestfiles/k8s_template_jumpbox.json
  pkg/engine/transform/transformtestfiles/k8s_upgrade_template_jumpbox.json
Labels: approved, lgtm, size/S

#2660 chore: rev Linux VHDs to 2020.01.30
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.30.txt
  vhd/release-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.30.txt
Labels: approved, lgtm, size/L

#2659 refactor: cleanup duplicate functions and move apiversions to consts
  parts/k8s/addons/1.11/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.12/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.13/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.14/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.15/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/masteroutputs.t
  pkg/api/const.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armoutputs.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L
