Repository Azure/aks-engine, pull requests merged in 2020-08, with the labels that each got.

#3657 fix: Support USNat and USSec
  pkg/api/defaults-custom-cloud-profile.go
  pkg/helpers/helpers.go
Labels: lgtm, size/XS

#3650 chore: update cluster-autoscaler to latest patch versions
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3639 docs: update stale Istio page and example
  examples/service-mesh/README.md
  examples/service-mesh/istio.json
Labels: area/docs, lgtm, size/L

#3658 feat: cherry-pick #2960 into AKS official branch
  .pipelines/e2e-job-template.yaml
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
  pkg/armhelpers/httpMockClientData/deployVMRequest.json
  pkg/engine/armresources.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/keyvaults.go
  pkg/engine/masterarmresources.go
  pkg/engine/roleassignments.go
  pkg/engine/roleassignments_test.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  test/e2e/engine/template.go
Labels: aks, size/L

#3642 fix: Fix distro related change
  pkg/api/types.go
Labels: size/XS

#3662 feat: Support AKS custom cloud
  pkg/api/types.go
  pkg/helpers/helpers.go
Labels: size/S

#3634 feat: azure arc addon
  docs/design/get-logs.md
  docs/topics/clusterdefinitions.md
  examples/addons/azure-arc-onboarding/README.md
  examples/addons/azure-arc-onboarding/kubernetes-arc.json
  parts/k8s/addons/arc-onboarding.yaml
  pkg/api/addons.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/artifacts.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/templates_generated.go
  test/e2e/azure/cli.go
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
  test/e2e/test_cluster_configs/arc/kubernetes-arc.json
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/XL

#3671 fix: Generate AzureStackCloud.json for akscustomcloud
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/api/types.go
  pkg/engine/templates_generated.go
Labels: size/S

#3674 ci: clarify apt packages installed during VHD CI
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#3666 feat: add support for Kubernetes 1.19.0-rc.4
  .pipelines/vhd-builder-windows.yaml
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3678 feat: Set AKS VHD to 2020.08.06
  pkg/api/azenvtypes.go
Labels: size/XS

#3684 docs: update the SGX DCAP version mentioned in the sgx instructions
  docs/topics/sgx.md
Labels: approved, area/docs, lgtm, size/XS

#3682 docs: fix misleading sysctldConfig examples
  docs/topics/clusterdefinitions.md
Labels: approved, area/docs, lgtm, size/S

#3683 chore: update cluster-autoscaler to latest patch versions
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3690 fix: validate "basic" LB and fix related unit tests
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/M

#3691 fix: metrics-server upgrade from v1.15 to v1.16
  pkg/armhelpers/azurestack/kubeclient.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: lgtm, size/M

#3693 chore: Update docker version in VHD to fix log rotation issue
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3692 chore: update Windows VHD to include 8B patches
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: lgtm, size/XS, windows

#3688 chore: Hyperv and upstream Containerd package support
  docs/topics/features.md
  examples/windows/README.md
  examples/windows/kubernetes-hybrid.azure-containerd.json
  examples/windows/kubernetes-hybrid.kubenet-containerd.json
  examples/windows/kubernetes-hyperv.json
  parts/k8s/containerdtemplate.toml
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowscontainerdfunc.ps1
  parts/windowsparams.t
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/const.go
  pkg/engine/params.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  scripts/build-windows-containerd.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/containerd.json
Labels: approved, lgtm, size/XXL, windows

#3685 chore: force delete addon manager when addon manager pods get stuck on terminating state
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: lgtm, size/XS

#3689 feat: cluster upgrade operations upgrade pause image
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
Labels: lgtm, size/L

#3695 feat: add support for Kubernetes v1.16.14
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, lgtm, size/XS

#3669 chore: upgrade metrics-server to v0.3.7
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, lgtm, size/S

#3703 feat: Set AKS VHD version to 2020.08.13
  pkg/api/azenvtypes.go
Labels: size/XS

#3705 fix: Set windows VHD version to 17763.1339.200718
  pkg/api/azenvtypes.go
Labels: size/XS

#3698 feat: configurable microsoft apt repository
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#3673 fix: don't wait for pod-security-policy spec if disabled
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/armvariables_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#3706 docs: adding James to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3701 fix: use new Windows VHD image version
  pkg/api/azenvtypes.go
Labels: approved, size/XS

#3707 fix: update v0.53.0 to new 17763.1339.200718
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#3708 fix: update v0.52 to new 17763.1282.200626
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#3697 feat: add support for Kubernetes v1.18.8
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3709 fix: update v0.51 to new 17763.1217.200514
  pkg/api/azenvtypes.go
Labels: VHD, lgtm, size/XS, windows

#3710 fix: update v0.50 to new 17763.1158.200422
  pkg/api/azenvtypes.go
Labels: VHD, lgtm, size/XS, windows

#3696 feat: add support for Kubernetes v1.17.11
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3704 feat: add support for Kubernetes v1.16.14 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: azurestack, lgtm, size/XS

#3699 fix: add rbac rules for nodes/status in cloud-node-manager.yaml
  parts/k8s/addons/cloud-node-manager.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3702 feat: add support for Kubernetes v1.17.11 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, azurestack, lgtm, size/XS

#3727 docs: update limitations in dualstack docs
  examples/dualstack/README.md
Labels: approved, area/docs, lgtm, size/XS

#3725 fix: Patch v1.15.11, v1.15.12, v1.16.10, v1.16.13, v1.17.7, v1.17.9, v1.18.4 v1.18.6
  pkg/api/k8s_versions.go
  vhd/packer/configure-windows-vhd.ps1
Labels: lgtm, size/L

#3721 fix: do not restart addon-manager if a reboot is required
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3728 chore: update csi-secrets-store addon manifest and images
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/L

#3733 feat: update aks vhd to 20200819
  pkg/api/azenvtypes.go
Labels: size/XS

#3731 chore: Update Windows VHD to 8B with hotfixes for Windows CPU metrics
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/k8s_versions.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/validate-windows-logging.yaml
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.200820.txt
Labels: lgtm, size/L

#3737 feat: collect hyperv containerd logs
  parts/k8s/windowscontainerdfunc.ps1
  pkg/engine/templates_generated.go
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/M

#3739 chore: Update moby version to 19.03.12
  pkg/api/const.go
Labels: size/XS

#3738 test: fix ginkgo failFast
  docs/community/running-tests.md
  test/e2e/config/config.go
  test/e2e/runner/ginkgo.go
Labels: approved, area/docs, area/test, lgtm, size/S

#3743 fix: fix issue where installing a different version of containerd vs …
  parts/k8s/windowscontainerdfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS, windows

#3742 ci: use 1.4.0 containerd release for windows in CI
  docs/topics/features.md
  examples/windows/kubernetes-hybrid.azure-containerd.json
  examples/windows/kubernetes-hybrid.kubenet-containerd.json
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/containerd.json
Labels: approved, area/ci, area/docs, lgtm, size/S, windows

#3744 chore: add new Azure VM SKUs
  cmd/get_skus_test.go
  pkg/helpers/azure_skus_const.go
Labels: approved, lgtm, size/XXL

#3750 chore: rev Linux VHDs to 2020.08.24
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.08.24.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.08.24.txt
Labels: approved, size/XXL

#3723 chore: specify containerd version to install with moby-engine package
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/components_test.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
  pkg/versions/compare.go
  pkg/versions/compare_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#3752 feat: variable upgrade timeout based on num nodes
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/S

#3756 test: disable azure-arc-onboarding addon in everything cluster config
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/S

#3757 fix: use cached v1.15-azs kube-proxy on Azure Stack
  pkg/api/addons.go
  pkg/api/addons_test.go
Labels: approved, lgtm, size/M

#3758 fix: Restart=always docker systemd service
  parts/k8s/cloud-init/artifacts/health-monitor.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3759 test: validate kubelet and docker systemd during E2E
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/systemd-validate.sh
Labels: approved, do-not-merge/hold, size/M

#3745 test: add REBOOT_CONTROL_PLANE_NODES E2E config
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/reboot-control-plane-node.yaml
  test/e2e/runner/cli_provisioner.go
Labels: approved, size/L

#3764 test: don't try to kill docker if using containerd
  test/e2e/kubernetes/scripts/systemd-validate.sh
Labels: approved, size/S

#3763 chore: always install moby-runc
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#3754 feat: add support for Kubernetes v1.19.0
  Jenkinsfile
  parts/k8s/addons/aad-pod-identity.yaml
  parts/k8s/addons/metrics-server.yaml
  pkg/api/common/versions.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/no_outbound.json
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3765 fix: ensure cleanup scripts can login w/ sp
  test/e2e/cleanup.sh
  vhd/packer/vhd-rg-cleanup.sh
Labels: approved, lgtm, size/S

#3766 doc: update azure stack doc for aks-engine v0.55.0
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack.json
  examples/azure-stack/kubernetes-windows.json
Labels: lgtm, size/M

#3729 fix: validate k8s control plane before addons
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/armresources_test.go
  pkg/engine/const.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L

#3740 chore: update NPM to latest version 1.1.7
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS
