Repository Azure/aks-engine, pull requests merged in 2020-05, with the labels that each got.

#3162 feat: Create Windows containerd VHDs
  .pipelines/vhd-builder-windows.yaml
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/windows-vhd-builder.json
Labels: approved, size/M, windows

#3136 feat: block imds from VMSS nodes if aad-pod-identity + msi
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2624 fix: added resource limits for networkmonitor daemonset
  parts/k8s/addons/1.16/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.17/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.18/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.19/azure-cni-networkmonitor.yaml
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#3167 refactor: simplify kubelet systemd service
  docs/topics/clusterdefinitions.md
  parts/k8s/cloud-init/artifacts/kubelet.service
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#3175 docs: remove obsolete api versions documentation
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/M

#3174 feat: add warning message for empty Location string
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/S

#3172 fix: update dcap checksum file
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: lgtm, size/XS

#3183 chore: check all error returns in tests
  cmd/generate_test.go
  cmd/get_locations_test.go
  cmd/get_skus_test.go
  cmd/root_test.go
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/apiloader_test.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azureclient_test.go
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/azurestack/converter_test.go
  pkg/armhelpers/compute_test.go
  pkg/armhelpers/converter_test.go
  pkg/engine/armresources_test.go
  pkg/engine/armvariables_test.go
  pkg/engine/engine_test.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/output_test.go
  pkg/engine/params_k8s_test.go
  pkg/engine/params_test.go
  pkg/engine/tenantid_test.go
  pkg/engine/transform/transform_test.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/helpers/helpers_test.go
Labels: approved, lgtm, size/XL

#3182 refactor: simplify golangci-lint invocation
  scripts/validate-go.sh
Labels: approved, lgtm, size/XS

#3181 chore: update go-dev image to v1.27.0
  .devcontainer.json
  .pipelines/pr-e2e.yaml
  .pipelines/vhd-builder-ubuntu-gen2.yaml
  .pipelines/vhd-builder.yaml
  Makefile
  hack/tools/Makefile
  makedev.ps1
Labels: approved, lgtm, size/S

#3180 feat: proximity placement group support
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/azurestack/compute_test.go
  pkg/armhelpers/compute_test.go
  pkg/engine/armtype_test.go
  pkg/engine/availabilitysets.go
  pkg/engine/transform/transform.go
  pkg/engine/transform/transform_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/byo_infra.json
Labels: size/L

#3177 docs: refresh documentation store
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prowci/README.md
  CONTRIBUTING.md
  cmd/addpool.go
  cmd/deploy.go
  cmd/generate.go
  cmd/rotate_certs.go
  cmd/scale.go
  cmd/upgrade.go
  cmd/version.go
  docs/README.md
  docs/community/README.md
  docs/community/developer-guide.md
  docs/community/planning-process.md
  docs/community/release-checklist.md
  docs/community/running-tests.md
  docs/design/custom-container-images.md
  docs/faq.md
  docs/howto/kubernetes-large-clusters.md
  docs/howto/troubleshooting.md
  docs/topics/aad.md
  docs/topics/architecture.md
  docs/topics/certificaterotation.md
  docs/topics/clusterdefinitions.md
  docs/topics/coredns.md
  docs/topics/csi-proxy-windows.md
  docs/topics/features.md
  docs/topics/get-logs.md
  docs/topics/gpu.md
  docs/topics/hybrid-environment.md
  docs/topics/keyvault-secrets.md
  docs/topics/kubernetes-walkthrough.md
  docs/topics/monitoring.md
  docs/topics/scale.md
  docs/topics/upgrade.md
  docs/topics/windows-and-kubernetes.md
  docs/topics/windows-vhd.md
  docs/topics/windows.md
  docs/tutorials/custom-vnet.md
  docs/tutorials/deploy.md
  docs/tutorials/quickstart.md
  docs/tutorials/quickstart.zh-CN.md
  examples/addons/cluster-autoscaler/README.md
  examples/addons/keyvault-flexvolume/README.md
  examples/disks-storageaccount/README.md
  examples/multiple-nodepools/README.md
  examples/networkpolicy/README.md
  extensions/prometheus-grafana-k8s/README.md
Labels: approved, lgtm, size/L

#3187 refactor: use simpler file names for addons maintenance
  parts/k8s/addons/aad-default-admin-group-rbac.yaml
  parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
  parts/k8s/addons/azurefile-csi-driver-deployment.yaml
  parts/k8s/addons/container-monitoring.yaml
  parts/k8s/addons/scheduled-maintenance-deployment.yaml
  parts/k8s/addons/secrets-store-csi-driver.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3184 chore: check all error returns in main code
  .golangci.yml
  cmd/addpool.go
  cmd/deploy.go
  cmd/generate.go
  cmd/get_logs.go
  cmd/rotate_certs.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/azureclient.go
  pkg/armhelpers/azurestack/converter.go
  pkg/armhelpers/azurestack/deploymentError.go
  pkg/armhelpers/converter.go
  pkg/armhelpers/deploymentError.go
  pkg/engine/armvariables.go
  pkg/engine/customfiles.go
  pkg/engine/engine.go
  pkg/engine/transform/apimodel_merger.go
  pkg/helpers/pki.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, lgtm, size/L

#3048 style: mutex is not necessary now that rand uses local object
  pkg/api/types.go
Labels: lgtm

#3190 chore: add new M-series SKUs
  cmd/get_skus_test.go
  pkg/helpers/azure_skus_const.go
Labels: approved, lgtm, size/L

#3195 chore: append Azure Stack suffix to custom components images
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/components.go
  pkg/api/components_test.go
  pkg/engine/templates_generated.go
Labels: lgtm, size/M

#3189 refactor: consolidate azure-cni-networkmonitor addon spec
  parts/k8s/addons/1.16/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.17/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.18/azure-cni-networkmonitor.yaml
  parts/k8s/addons/1.19/azure-cni-networkmonitor.yaml
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  pkg/api/common/versions_test.go
  pkg/engine/templates_generated.go
Labels: approved, size/XL

#3200 test: reduce node count in E2E "everything" config
  test/e2e/test_cluster_configs/everything.json
Labels: size/XS

#3197 feat: add support for Kubernetes 1.19.0-alpha.3
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3199 fix: aad-pod-identity taints foo works in k8s < 1.16
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/artifacts/untaint-nodes.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3206 test: rationalize "everything" E2E config for coredns autoscaler test
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/S

#3191 ci: enable staticcheck linter
  .golangci.yml
  pkg/api/apiloader_test.go
  pkg/api/defaults.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/azurestack/compute.go
  pkg/armhelpers/compute.go
  pkg/engine/engine_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, lgtm, size/M

#3198 refactor: consolidate cluster-autoscaler addon spec
  parts/k8s/addons/1.14/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.15/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/cluster-autoscaler.yaml
  parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3214 docs: update sgx install instructions to dcv2 vms and newer resource …
  docs/topics/sgx.md
Labels: lgtm, size/L

#3209 chore: Updating Windows VHD build to use mcr.microsoft.com/oss/kubernetes/pause:1.3.1
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#3213 refactor: use newer "az deployment group" CLI syntax
  README_zh-CN.md
  docs/community/e2e-output-example.log
  docs/topics/windows.md
  docs/tutorials/custom-vnet.md
  docs/tutorials/day2-operations.md
  docs/tutorials/quickstart.md
  test/e2e/cleanup.sh
  vhd/packer/vhd-rg-cleanup.sh
Labels: approved, lgtm, size/M

#3211 refactor: consolidate metrics-server addon spec
  parts/k8s/addons/1.14/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/1.15/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/metrics-server.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3215 fix: set Windows Defender process exclusion for containerd
  parts/k8s/kuberneteswindowsfunctions.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS, windows

#3212 feat: add support for Kubernetes 1.15.12
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3224 update: Update AKS VHD version
  pkg/api/azenvtypes.go
Labels: aks, size/S

#3204 chore: Updating Antrea version to 0.6.0
  examples/networkpolicy/README.md
  parts/k8s/addons/antrea.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/api/addons.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#3221 docs: add missing link to upgrade doc
  docs/tutorials/quickstart.md
Labels: approved, area/docs, lgtm, size/XS

#3216 chore: get-logs command on Azure Stack
  cmd/get_logs.go
  scripts/collect-logs.sh
Labels: azurestack, lgtm, size/L

#3208 chore: Update Policy addon versions
  examples/addons/azure-policy/README.md
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/XS

#3205 docs: rewrite monitoring topic
  docs/static/img/k8s-monitoring-grafana1.png
  docs/static/img/k8s-monitoring-grafana2.png
  docs/topics/monitoring.md
Labels: approved, area/docs, lgtm, size/L

#3178 chore: Updating Azure NPM to v1.1.2
  parts/k8s/addons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/M

#3230 docs: update sgx plugin docs
  docs/topics/sgx.md
Labels: size/M

#3226 fix: don't validate Windows version in update scenario
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/M, windows

#3201 feat: enable alternate kube-reserved cgroups
  docs/topics/clusterdefinitions.md
  examples/kubernetes-config/kubernetes-kube-reserved.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/cse.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/L

#3223 chore: pull cached Azure Stack Windows binaries from shared SA
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/S

#3233 chore: bump csi-secrets-store to v0.0.10, keyvault provider to 0.0.5
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3218 docs: Update quickstart.md to add scoop install guide
  docs/tutorials/quickstart.md
Labels: area/docs, lgtm, size/XS

#3225 chore: update nvidia device plugin
  pkg/api/azenvtypes.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  vhd/packer/install-dependencies.sh
Labels: gpu, lgtm, size/S

#3231 fix: update Azure Stack Windows binaries component name
  pkg/api/common/const.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/params_k8s.go
Labels: approved, azurestack, lgtm, size/S

#3192 chore: updating cni to v1.1.2
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#3236 chore: update Windows VHD to use May 2020 updates
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, windows

#3232 fix: USER_ASSIGNED_IDENTITY_ID is empty in azure.json
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/L, windows

#3238 fix: Add Windows node pool to containerd tests
  test/e2e/test_cluster_configs/containerd.json
Labels: approved, lgtm, size/S

#3239 ci: ensure sku title/summary/longsummary is unique when creating new …
  vhd/publishing/new-windows-sku.sh
  vhd/publishing/windows-sku-template.json
Labels: approved, size/XS

#3242 ci: passing container runtime var to new-windows-sku.sh
  .pipelines/marketplace-sku.yaml
Labels: size/XS

#3237 chore: update zip name for mooncake mirror
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/XS

#3228 fix: custom cloud Azure CNI config for Windows
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S, windows

#3179 cherry-pick: modify container runtime data dir
  cmd/generate_test.go
  docs/topics/architecture.md
  docs/topics/clusterdefinitions.md
  examples/kubernetes-config/kubernetes-containerd-tmpdir.json
  examples/kubernetes-config/kubernetes-docker-tmpdir.json
  go.mod
  go.sum
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/common/const.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/common/types.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/go.sum
  test/e2e/test_cluster_configs/everything.json
  vendor/github.com/BurntSushi/toml/.gitignore
  vendor/github.com/BurntSushi/toml/.travis.yml
  vendor/github.com/BurntSushi/toml/COMPATIBLE
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/Makefile
  vendor/github.com/BurntSushi/toml/README.md
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/encoding_types.go
  vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/session.vim
  vendor/github.com/BurntSushi/toml/type_check.go
  vendor/github.com/BurntSushi/toml/type_fields.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
Labels: aks, size/XXL

#3243 docs: remove out of date Calico upgrade note
  examples/networkpolicy/README.md
Labels: approved, lgtm, size/S

#3235 refactor: consolidate nvidia-device-plugin addon spec
  parts/k8s/addons/1.17/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/addons/nvidia-device-plugin.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, gpu, lgtm, size/XL

#3241 docs: AKS-engine (on Stack) considerations around the use of proxy servers
  docs/topics/README.md
  docs/topics/proxy-servers.md
Labels: area/docs, size/L

#3251 Revert "fix: USER_ASSIGNED_IDENTITY_ID is empty in azure.json"
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, size/L

#3247 fix: don't dry-run cluster-init spec
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#3249 test: az deployment group create in E2E runner
  test/e2e/azure/cli.go
Labels: approved, lgtm, size/XS

#3248 chore: remove defunct build-windows-k8s.sh script
  Makefile
  scripts/build-windows-k8s.sh
Labels: approved, azurestack, lgtm, size/L

#3258 feat: Update vhd version 2020.05.13
  pkg/api/azenvtypes.go
Labels: aks, size/XS

#3264 docs: fix capitalization
  docs/topics/sgx.md
Labels: lgtm, size/XS

#3263 feat: Updating Windows VHDs to include May patches
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200513.txt
Labels: approved, lgtm, size/L, windows

#3265 chore: rev Linux VHDs to 2020.05.13
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202005_2020.05.13.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202005_2020.05.13.txt
Labels: approved, size/L

#3260 fix: update Windows image validate on Azure Stack Hub
  pkg/armhelpers/support_validator.go
  pkg/armhelpers/support_validator_test.go
Labels: approved, lgtm, size/S, windows

#3254 fix: USER_ASSIGNED_IDENTITY_ID is empty in azure.json
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: lgtm, size/L

#3266 chore: Update Windows VHD image to 5B with some fixes
  parts/k8s/kubeletstart.ps1
  parts/k8s/kubeproxystart.ps1
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodereset.ps1
  pkg/api/agentPoolOnlyApi/v20170831/types.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/azenvtypes.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200513.txt
Labels: size/XXL

#3259 fix: resilient etcd data disk mounting
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#3273 refactor: move etcd data disk mounting to cloud init
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/mountetcd.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/const.go
  pkg/engine/engine_test.go
  pkg/engine/templates_generated.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/L

#3268 chore: Update Windows VHD image to 5B with some fixes
  parts/k8s/kubeletstart.ps1
  parts/k8s/kubeproxystart.ps1
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  parts/k8s/windowsnodereset.ps1
  pkg/api/agentPoolOnlyApi/v20170831/types.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/azenvtypes.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/const.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200513.txt
Labels: aks, size/XXL

#3281 fix: Fix last revert change
  pkg/engine/template_generator.go
Labels: size/XS

#3277 refactor: consolidate azure-cloud-provider addon spec
  parts/k8s/addons/1.15/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  parts/k8s/addons/azure-cloud-provider.yaml
  parts/k8s/addons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3272 chore: cherry pick c7109ed99 to get the latest azure cni versions
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: aks, size/S

#3276 chore: don't force create etcd_disk filesystem
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3275 chore: disable 18.04 + N series VM node pool
  docs/topics/clusterdefinitions.md
  docs/topics/gpu.md
  examples/addons/nvidia-device-plugin/README.md
  examples/addons/nvidia-device-plugin/nvidia-device-plugin.json
  examples/kubernetes-config/kubernetes-docker-tmpdir.json
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, do-not-merge/hold, size/L

#3283 refactor: consolidate azure-network-policy addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/azure-network-policy.yaml
  pkg/api/addons.go
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3289 refactor: consolidate cilium addons specs
  parts/k8s/addons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/addons/cilium.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3287 test: add stability test tolerance for calico cluster test configs
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#3297 fix: ensure /mnt is ext4
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/scripts/host-os-fs.sh
Labels: approved, lgtm, size/M

#3298 chore: make 1.18 the default Kubernetes version
  pkg/api/common/const.go
  pkg/api/defaults-kubelet_test.go
Labels: approved, lgtm, size/XS

#3300 fix: fix issue provisioning windows nodes with kubenet
  parts/k8s/kubeletstart.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3293 fix: apiserver connection timeout for private apiserver
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3284 refactor: consolidate pod-security-policy addon spec
  parts/k8s/addons/1.15/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml
  parts/k8s/addons/pod-security-policy.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3301 fix: whitespace trimming in cloud-provider spec is broken
  parts/k8s/addons/azure-cloud-provider.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/M

#3302 fix: addon-manager definition should be under "labels"
  parts/k8s/addons/azurefile-csi-driver-deployment.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#3294 fix: increase apiserver connection timeout for private apiserver
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: size/S

#3303 fix: ensure ERR_K8S_API_SERVER_DNS_LOOKUP_FAIL is returned when DNS check fails
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: lgtm, size/M

#3308 fix: prevent panic in Windows scale if no tags
  cmd/scale.go
  pkg/armhelpers/utils/util_test.go
Labels: approved, lgtm, size/S

#3310 chore: remove support for Kubernetes 1.14
  Jenkinsfile
  cmd/generate_test.go
  examples/azure-stack/kubernetes-windows.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/rbac-disabled.json
  examples/kubernetes-releases/kubernetes1.14.json
  examples/windows/kubernetes.json
  parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
  pkg/api/addons_test.go
  pkg/api/common/versions.go
  pkg/api/components_test.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/mockclients.go
  pkg/engine/engine_test.go
  pkg/engine/loadbalancers_test.go
  pkg/engine/templates_generated.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  test/e2e/test_cluster_configs/container_monitoring.json
  test/e2e/test_cluster_configs/everything.json
  test/e2e/test_cluster_configs/network_policy/antrea.json
  test/e2e/test_cluster_configs/network_policy/antrea_azure.json
  test/e2e/test_cluster_configs/network_policy/azure.json
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
  test/e2e/test_cluster_configs/network_policy/cilium.json
  test/e2e/test_cluster_configs/no_outbound.json
  test/e2e/test_cluster_configs/sgx.json
  test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XXL

#3314 test: use common timeout for repeat tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/S

#3316 test: skip azurefile test if using containerd
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XS

#3296 cherry pick c7109ed99 to get the latest azure cni versions
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: aks, size/S

#3317 docs: aks-ubuntu-18.04 is default distro
  docs/topics/clusterdefinitions.md
Labels: approved, lgtm, size/XS

#3313 fix: ensure pod-security-policy is the first addon loaded
  parts/k8s/addons/pod-security-policy.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  pkg/engine/const.go
  pkg/engine/cse.go
  pkg/engine/cse_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#3319 Adding VHD label to repo
  labels.yaml
Labels: approved, lgtm, size/XS

#3299 feat: add support for Kubernetes 1.19.0-beta.0
  .pipelines/pr-e2e.yaml
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#3320 ci: moving windows vhd/image related test configs to westus2
  test/e2e/test_cluster_configs/windows/cse_benchmark_aks_vhds.json
  test/e2e/test_cluster_configs/windows/cse_benchmark_win_vhds.json
  test/e2e/test_cluster_configs/windows/custom_image.json
  test/e2e/test_cluster_configs/windows/image_reference.json
  test/e2e/test_cluster_configs/windows/shared_image_gallery.json
  test/e2e/test_cluster_configs/windows/vhd_url.json
Labels: approved, area/ci, size/L, windows

#3144 fix: use ctr to remove containerd containers
  parts/k8s/windowsnodereset.ps1
  pkg/engine/templates_generated.go
  test/e2e/config/config.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/runner.go
Labels: approved, lgtm, size/L, windows

#3311 feat: add support for Kubernetes 1.17.6
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3312 feat: add support for Kubernetes 1.16.10
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3309 feat: add support for Kubernetes 1.18.3
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3323 refactor: consolidate kube-rescheduler addon spec
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/addons/kube-rescheduler.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#3325 chore: rev default etcd version to 3.3.22
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/test_cluster_configs/everything.json
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3334 chore: Add LicenseType in WindowsProfile
  docs/topics/clusterdefinitions.md
  docs/topics/windows-and-kubernetes.md
  examples/windows/kubernetes-windows-1903.json
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: size/L

#3335 fix: Fix initAKSCustomCloud script; use customized outbound test url
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/init-aks-custom-cloud.sh
  pkg/api/types.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
Labels: size/S

#3336 feat: Update ASK VHD to 2020.05.21
  pkg/api/azenvtypes.go
Labels: size/XS

#3337 fix: Fix VMAS cse
  pkg/engine/vmextensions.go
Labels: size/S

#3328 chore: update coredns to 1.6.9
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3327 chore: update kube-dashboard addon to v2.0.1
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3340 ci: enable multiple static resource group exclusions in cleanup script
  test/e2e/cleanup.sh
  vendor/modules.txt
  vhd/packer/vhd-rg-cleanup.sh
Labels: approved, do-not-merge/hold, size/S

#3338 chore: k8s v1.17 conformance model for Azure Stack
  examples/azure-stack/conformance/kubernetes1.17.json
Labels: lgtm, size/M

#3348 test: run everything E2E config against all cluster versions
  test/e2e/test_cluster_configs/everything.json
Labels: size/XS

#3347 refactor: consolidate ip-masq-agent addon spec
  parts/k8s/addons/1.16/ip-masq-agent.yaml
  parts/k8s/addons/1.17/ip-masq-agent.yaml
  parts/k8s/addons/1.18/ip-masq-agent.yaml
  parts/k8s/addons/1.19/ip-masq-agent.yaml
  parts/k8s/addons/ip-masq-agent.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/XL

#3332 chore: update CNI binary to 0.8.6
  pkg/api/const.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3345 chore: add legal notice for Windows VHD
  vhd/notice/notice_windows.txt
  vhd/packer/windows-vhd-builder.json
Labels: VHD, approved, lgtm, size/XXL, windows

#3344 feat: Enabling SSH on windows nodes by default (#2759)
  docs/topics/clusterdefinitions.md
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: aks, size/L

#3350 fix: use right nodeSelector for cluster-autoscaler addon
  parts/k8s/addons/cluster-autoscaler.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3357 chore: remove old labels.yaml file
  labels.yaml
Labels: approved, lgtm, size/M

#3364 fix: Sync downloadAzureCNI
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: size/XS

#3353 chore: upgrade cni to v1.1.3
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3355 refactor: consolidate audit-policy "addon" spec
  parts/k8s/addons/1.16/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.17/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.18/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/1.19/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/audit-policy.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#3356 refactor: consolidate aad-pod-identity addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/aad-pod-identity.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3366 fix: use nvidia drivers version 418.126.02 for 18.04
  docs/topics/gpu.md
  examples/addons/nvidia-device-plugin/README.md
  examples/addons/nvidia-device-plugin/nvidia-device-plugin.json
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, lgtm, size/L

#3363 refactor: consolidate cloud-node-manager addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-cloud-node-manager.yaml
  parts/k8s/addons/cloud-node-manager.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3367 chore: change MTU only if not Azure CNI on Azure Stack
  parts/k8s/cloud-init/artifacts/cse_customcloud.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3361 refactor: consolidate calico addon spec
  parts/k8s/addons/1.15/calico.yaml
  parts/k8s/addons/1.16/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/calico.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, lgtm, size/XXL

#3359 refactor: consolidate blobfuse-flexvolume addon spec
  parts/k8s/addons/1.18/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/addons/blobfuse-flexvolume.yaml
  parts/k8s/addons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, needs-rebase, size/XL

#3358 refactor: consolidate aci-connector addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/aci-connector.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, needs-rebase, size/XXL

#3372 chore: get-logs collects vhd-install.complete
  scripts/collect-logs.sh
Labels: lgtm, size/XS

#3370 chore: rev pause image to 1.3.1
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/k8s_versions.go
  pkg/api/types_test.go
  pkg/engine/template_generator_test.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3349 docs: update sgx doc and sgx-test tag
  docs/topics/sgx.md
  docs/topics/sgx/device-plugin-before-k8s-1-17.yaml
  docs/topics/sgx/device-plugin.yaml
  test/e2e/kubernetes/workloads/sgx-test.yaml
Labels: area/docs, lgtm, size/L

#3374 test: remove Kubernetes version restrictions from sgx tests
  test/e2e/test_cluster_configs/sgx.json
Labels: size/XS

#3352 feat: add support for GPU VHD
  pkg/api/azenvtypes.go
  pkg/api/common/helper.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/armhelpers/support_validator.go
Labels: aks, size/M
