Repository Azure/aks-engine, pull requests merged in 2020-02, with the labels that each got.

#2661 fix: don't expire adminUser or etcd accounts
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2662 fix: update CSE moby version substring match
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2657 test: wait for "Ready" nodes, where appropriate
  test/e2e/cluster.sh
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, size/L

#2668 test: delete pod if exists in run pod scenario
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#2669 fix: #2667 change apiVersion of deployments from v1beta2 to v1
  .prowci/deck.yaml
  .prowci/hook.yaml
  .prowci/tide.yaml
Labels: lgtm, size/XS

#2670 test: enable scale/upgrade for base E2E cluster config
  Jenkinsfile
  test/e2e/test_cluster_configs/base.json
Labels: size/XS

#2665 chore: Updating Azure NPM to v1.0.32
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2676 chore: don't refer to hyperkube in template if > 1.16
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2678 test: replace containerd+kubenet with containerd+azure
  examples/kubernetes.json
  test/e2e/test_cluster_configs/containerd.json
  test/e2e/test_cluster_configs/network/kubenet.json
  test/e2e/test_cluster_configs/network/kubenet_containerd.json
Labels: approved, size/M

#2651 refactor: extract common script parameters into function
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/engine/armvariables.go
  pkg/engine/armvariables_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XL

#2681 fix: unknown ostype when getting an index should probably create an error
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
Labels: lgtm, size/S

#2658 feat: Updating Antrea version to v0.3.0
  parts/k8s/addons/antrea.yaml
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/L

#2606 feat: multi AI telemetry keys
  Makefile
  docs/topics/telemetry.md
  go.mod
  go.sum
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/armvariables.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/telemetry/telemetry.go
  scripts/ginkgo.coverage.sh
  test/e2e/Makefile
  test/e2e/go.sum
Labels: approved, lgtm, size/L

#2655 build: fetch k8s Windows .zip from kubernetesartifacts storage
  Makefile
  docs/howto/building-windows-kubernetes-binaries.md
  docs/topics/architecture.md
  docs/topics/clusterdefinitions.md
  parts/k8s/windowskubeletfunc.ps1
  parts/windowsparams.t
  pkg/api/azenvtypes.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/params_k8s.go
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/L

#2688 fix: raising dynamic port range for windows to better support clusters with 200+ services
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsconfigfunc.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S, windows

#2692 fix: update to use single omsagent yaml for all k8s versions to avoid any manual errors and easy maintainbility
  parts/k8s/addons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2693 fix: add ProgressPreference=SilentlyContinue to disable progress bar
  scripts/collect-windows-logs.ps1
Labels: approved, lgtm, size/XS, windows

#2689 fix: Set the default values for WindowsSku and ImageVersion by publisher and offer in creating
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/L, windows

#2696 test: don't get vms before resource group exists
  test/e2e/azure/cli.go
  test/e2e/runner.go
Labels: approved, size/M

#2697 test: curl as a stability test client
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/S

#2663 feat: read vm size from instance metadata service for windows cse telemetry
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M, windows

#2694 docs: proposal for Azure locations + SKUs automation
  docs/design/automate-skus.md
Labels: approved, area/docs, lgtm, size/L

#2699 chore: gofmt to avoid lint errors
  hack/tools/tools.go
  pkg/api/defaults_test.go
Labels: approved, lgtm, size/XS

#2700 test: enable configurable LoadBalancer test timeout
  test/e2e/cluster.sh
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/S

#2703 test: add LB_TEST_TIMEOUT default
  test/e2e/cluster.sh
Labels: approved, size/XS

#2705 refactor: put Azure locations list in a separate source file
  pkg/api/types_test.go
  pkg/helpers/azure_locations.go
  pkg/helpers/azure_locations_test.go
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
Labels: approved, lgtm, size/L

#2702 feat: adding mcr.microsoft.com/oss/kubernetes/pause:1.3.0 to windows VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#2690 add the missing images in vhd for AKS.
  packer/install-dependencies.sh
Labels: size/L

#2706 refactor: put Azure DC/OS SKUs list in a separate source file
  pkg/helpers/azure_skus.go
  pkg/helpers/azure_skus_dcos.go
  pkg/helpers/azure_skus_dcos_test.go
  pkg/helpers/azure_skus_test.go
Labels: approved, lgtm, size/XXL

#2540 refactor: user-configurable components
  docs/topics/clusterdefinitions.md
  parts/k8s/manifests/1.17/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/1.17/kubernetesmaster-kube-scheduler.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/1.18/kubernetesmaster-kube-scheduler.yaml
  parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
  pkg/api/common/const.go
  pkg/api/components.go
  pkg/api/components_test.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/defaults.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#2674 docs: add data collection (telemetry) notice to readme
  README.md
Labels: approved, lgtm, size/XS

#2718 unblocking e2e tests by hardcording iis image
  test/e2e/engine/template.go
Labels: approved, size/XS

#2717 feat: abort/warn if apimodel contains properties not supported by Azure Stack
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/testdata/azurestack/kubernetes.json
Labels: approved, lgtm, size/L

#2707 feat: add support for Kubernetes 1.17.3
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2719 chore: use k8s 1.17 for e2e tests in windows vhd pipeline
  .pipelines/vhd-builder-windows.yaml
Labels: approved, lgtm, size/XS

#2711 refactor: add KubernetesImageBaseType
  cmd/rotate_certs.go
  cmd/rotate_certs_test.go
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/azenvtypes.go
  pkg/api/common/const.go
  pkg/api/components.go
  pkg/api/components_test.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/engine_test.go
  pkg/engine/params_k8s.go
  pkg/engine/template_generator.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XXL

#2710 feat: add support for Kubernetes 1.16.7
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#2709 feat: add support for Kubernetes 1.15.10
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2724 fix: remove requirement for ldflags or make test
  pkg/telemetry/telemetry.go
Labels: approved, lgtm, size/XS

#2728 chore: rev AKS Engine Linux VHDs to 2020.02.12
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202002_2020.02.12.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202002_2020.02.12.txt
Labels: approved, lgtm, size/L

#2729 fix: Adding skuLongSummary to sku template publishing file to unblock…
  vhd/publishing/windows-sku-template.json
Labels: approved, lgtm, size/XS

#2727 fix: update apiserver encryption provider config flag
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
Labels: approved, lgtm, size/M

#2730 chore: update cluster-autoscaler to 1.17.1
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2731 feat: updating windows VHD for Feb k8s versions
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.973.200213.txt
Labels: approved, lgtm, size/L

#2732 fix: apply large ipv4 neigh GC settings to nodes of all sizes
  parts/k8s/cloud-init/artifacts/kubelet.service
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/scripts/net-config-validate.sh
Labels: approved, lgtm, size/S

#2738 docs: remove references to "Public Preview" from Azure Stack page
  docs/topics/azure-stack.md
Labels: size/XS

#2739 fix: init Azure clients consistently
  pkg/armhelpers/azureclient.go
Labels: approved, lgtm, size/M

#2725 fix: Set vnetCidr by the address space of the vnet
  pkg/engine/params.go
  pkg/engine/params_test.go
Labels: aks, approved, lgtm, size/M

#2744 test: remove non-working SGX E2E cluster config
  test/e2e/test_cluster_configs/sgx.json
Labels: approved, lgtm, size/M

#2687 Add template/options for using Shared Image Gallery
  examples/kubernetes-sig-containerd.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/kubernetes/scripts/host-os-dns-validate.sh
  test/e2e/kubernetes/scripts/time-sync-validate.sh
  test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
  test/e2e/test_cluster_configs/sig_containerd.json
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#2746 chore: cse cleanup
  examples/kubernetes-sig-containerd.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/network/kubenet_containerd.json
  test/e2e/test_cluster_configs/sig_containerd.json
Labels: approved, lgtm, size/L

#2682 feat: add support for Kubernetes 1.18.0-alpha.3
  pkg/api/common/versions.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/L

#2742 chore: update image base for windows vhd
  vhd/packer/windows-vhd-builder.json
Labels: approved, lgtm, size/XS

#2750 fix: Set vnetCidr by the address space of the vnet (#2725)
  pkg/engine/params.go
  pkg/engine/params_test.go
Labels: lgtm, size/M

#2749 ci: stop testing k8s 1.13
  .pipelines/pr-e2e.yaml
  Jenkinsfile
Labels: approved, lgtm, size/S

#2722 feat: enable MCR KubernetesImageBaseType
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/azenvtypes.go
  pkg/api/components.go
  pkg/api/components_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/mocks.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator_test.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
Labels: approved, lgtm, size/XL

#2748 feat: add support for Kubernetes 1.18.0-alpha.5
  pkg/api/common/versions.go
Labels: approved, lgtm, size/XS

#2751 chore: installing Docker EE 19.03.5 by default in Windows VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS

#2754 chore: latent lint
  pkg/api/addons_test.go
Labels: size/M

#2649 chore: use azure containerd packages
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#2756 chore: more lint!
  pkg/api/addons_test.go
Labels: size/M

#2753 test: configurable CONTAINER_RUNTIME via E2E
  test/e2e/cluster.sh
  test/e2e/engine/template.go
  test/e2e/test_cluster_configs/flannel/docker.json
Labels: approved, size/M

#2757 feat: update pause image to 1.3.0 (includes 1903 and 1909 support)
  parts/k8s/windowskubeletfunc.ps1
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/M, windows

#2761 chore: use MCR URI to validate outbound connectivity
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: approved, lgtm, size/S

#2767 test: add deployment stability tests
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/L

#2766 fix: support Azure containerd install in Debian
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2760 chore: bump keyvault-flexvol to v0.0.16
  examples/addons/keyvault-flexvolume/README.md
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2774 fix: only configAddons if addons enabled
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#2769 fix: apiserver broken due to incorrect kms cachesize setting
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: approved, size/XS

#2776 chore: update cluster-autoscaler for 1.15 and 1.16
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2778 test: get pod network info if dns validation fails
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/M

#2783 chore: update coredns to 1.6.7
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2784 test: reorder E2E tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/XL

#2755 chore: rationalize AKS Engine VHD config
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L

#2775 fix: components works with Azure Stack
  pkg/api/components.go
  pkg/api/components_test.go
Labels: approved, lgtm, size/M

#2790 chore: adding azure-cni v1.0.33 artifacts to VHDs
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2793 Adding Kalya to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2785 fix: use non-reserved exit codes for bcc/bpf install
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#2786 feat: Feb windows updates
  pkg/api/azenvtypes.go
  pkg/api/const.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1039.2000220.txt
Labels: approved, lgtm, size/L

#2791 feat: add support for Kubernetes 1.18.0-beta.1
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#2795 docs: add CSE example in upgrade do-not-dos
  docs/topics/upgrade.md
Labels: approved, lgtm, size/XS

#2796 chore: Adding 2C patches to windows VHD which addresses some networking issues
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, lgtm, size/XS

#2780 chore: Update the containerd config
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/templates_generated.go
Labels: lgtm, size/L

#2797 test: improved master/agent pod validation
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/busybox-agent.yaml
  test/e2e/kubernetes/workloads/busybox-master.yaml
  test/e2e/kubernetes/workloads/nginx-master.yaml
Labels: approved, size/L

#2771 feat: "aks-engine get-locations" command
  cmd/get_locations.go
  cmd/get_locations_test.go
  cmd/root.go
  cmd/root_test.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/azurestack/azureclient.go
  pkg/armhelpers/azurestack/httpMockClient.go
  pkg/armhelpers/azurestack/httpMockClientData/listLocations.json
  pkg/armhelpers/azurestack/subscriptions.go
  pkg/armhelpers/azurestack/subscriptions_test.go
  pkg/armhelpers/httpMockClient.go
  pkg/armhelpers/httpMockClientData/listLocations.json
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/subscriptions.go
  pkg/armhelpers/subscriptions_test.go
  pkg/helpers/azure_locations.go
  pkg/helpers/azure_locations_test.go
Labels: approved, size/XXL
