Repository Azure/aks-engine, pull requests merged in 2020-06, with the labels that each got.

#3375 fix: rev pause image to 1.3.1
  pkg/api/k8s_versions.go
  pkg/api/types_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/transform/transformtestfiles/k8s_template_jumpbox.json
  pkg/engine/transform/transformtestfiles/k8s_upgrade_template_jumpbox.json
  vhd/packer/install-dependencies.sh
Labels: aks, size/S

#3378 chore: rev Linux VHDs to 2020.05.29
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202005_2020.05.29.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202005_2020.05.29.txt
Labels: approved, lgtm, size/L

#3377 chore: add support for K8s 1.16.10 & 1.17.6 on Azure Stack
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3376 chore: Bump moby version to 3.0.12
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3381 feat: Add gen2 GPU SKU and OS config
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/armhelpers/support_validator.go
Labels: size/L

#3379 test: Add test support for windows server 1909
  examples/windows/kubernetes-windows-1909.json
  test/e2e/engine/template.go
Labels: approved, lgtm, size/M, windows

#3382 fix: Update GPU driver version to 418.126.02
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  pkg/engine/templates_generated.go
Labels: size/XS

#3384 chore: remove unused, deprecated blobfuse spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  pkg/engine/templates_generated.go
Labels: approved, size/L

#3386 test: print podsecuritypolicy resources during E2E
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#3385 refactor: consolidate flannel addon spec
  parts/k8s/addons/1.17/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/flannel.yaml
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/cloud-init/masternodecustomdata.yml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XXL

#3389 refactor: consolidate keyvault-flexvolume addon spec
  parts/k8s/addons/1.17/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/keyvault-flexvolume.yaml
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3390 refactor: consolidate kube-dns addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/kube-dns.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3387 feat: deprecate heapster addon
  docs/topics/clusterdefinitions.md
  parts/k8s/addons/1.16/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-heapster-deployment.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/armresources_test.go
  pkg/engine/artifacts.go
  pkg/engine/artifacts_test.go
  pkg/engine/const.go
  pkg/engine/masterarmresources_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  pkg/engine/transform/transformtestfiles/k8s_addpool_vmas.json
  pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/engine/transform/transformtestfiles/k8s_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/engine/transform/transformtestfiles/master_resources_scale_temaplate.json
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, size/XXL

#3391 refactor: consolidate kube-proxy addon spec
  parts/k8s/addons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/kube-proxy.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3395 chore: rev AKS Engine VHDs to 2020.06.02
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.02.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.02.txt
Labels: approved, size/L

#3396 feat: configurable calico logging verbosity
  docs/topics/clusterdefinitions.md
  parts/k8s/addons/1.15/calico.yaml
  parts/k8s/addons/calico.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, size/L

#3397 refactor: consolidate smb-flexvolume addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/addons/smb-flexvolume.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XL

#3399 refactor: consolidate tiller addon spec
  parts/k8s/addons/1.16/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/addons/1.17/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/addons/1.18/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/addons/1.19/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/addons/tiller.yaml
  pkg/engine/const.go
  pkg/engine/templates_generated.go
Labels: approved, size/XXL

#3322 chore: Add EnableAHUB in WindowsProfile
  docs/topics/clusterdefinitions.md
  docs/topics/windows-and-kubernetes.md
  examples/windows/kubernetes-wincni.json
  examples/windows/kubernetes-windows-1903.json
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/test_cluster_configs/windows/vhd_ahub.json
Labels: approved, lgtm, size/L, windows

#3365 chore: update node-problem-detector to v0.8.2
  examples/addons/node-problem-detector/README.md
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3405 feat: update AKS VHD to 2020.05.31
  pkg/api/azenvtypes.go
Labels: size/XS

#3407 chore: rev Windows VHD to 17763.1217.200603
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200603.txt
Labels: approved, size/L

#3406 chore: standardize nodeSelectors
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/addons/cluster-autoscaler.yaml
  parts/k8s/addons/coredns.yaml
  pkg/engine/templates_generated.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#3410 chore: use local kubeconfig if no outbound
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3394 feat: add "get-versions --azure-env" flag to list custom clouds supported versions
  cmd/get_versions.go
  cmd/upgrade.go
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/common/const.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/armvariables_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  test/e2e/engine/template.go
Labels: approved, azurestack, lgtm, size/L

#3409 chore: update kube-addon-manager to v9.1.1
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3408 feat: add support for Kubernetes 1.19.0-beta.1
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3401 fix: Set spg only when spg is not set
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: aks, size/L

#3360 chore: Update aks-release to azure cni 1.1.3
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/converterfromapi_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200603.txt
Labels: aks, size/L

#3412 test: expose misconfigured interfaces by downloading large-enough files
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/S

#3330 fix: Enable e2e to install ginko if required
  docs/community/running-tests.md
  test.mk
Labels: approved, area/test, lgtm, size/M

#3400 fix: log kubelet status and fix nc output stderr
  pkg/engine/armresources_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  pkg/engine/vmextensions.go
  pkg/engine/vmextensions_test.go
Labels: aks, size/M

#3393 feat: re-enable container runtime dir relocation
  cmd/generate_test.go
  docs/topics/architecture.md
  docs/topics/clusterdefinitions.md
  examples/kubernetes-config/kubernetes-containerd-tmpdir.json
  examples/kubernetes-config/kubernetes-docker-tmpdir.json
  go.mod
  go.sum
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/common/const.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/common/types.go
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/go.sum
  test/e2e/test_cluster_configs/everything.json
  vendor/github.com/BurntSushi/toml/.gitignore
  vendor/github.com/BurntSushi/toml/.travis.yml
  vendor/github.com/BurntSushi/toml/COMPATIBLE
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/Makefile
  vendor/github.com/BurntSushi/toml/README.md
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/encoding_types.go
  vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/session.vim
  vendor/github.com/BurntSushi/toml/type_check.go
  vendor/github.com/BurntSushi/toml/type_fields.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
Labels: aks, lgtm, size/XXL

#3403 feat: Update container monitoring addon for may omsagent release
  docs/tutorials/containermonitoringaddon.md
  parts/k8s/addons/container-monitoring.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/M

#3421 pull just azure cni changes from https://github.com/Azure/aks-engine/…
  pkg/api/azenvtypes.go
Labels: size/XS

#3420 fix: only schedule mic on Linux nodes
  parts/k8s/addons/aad-pod-identity.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/XS

#3418 test: add sac test configs
  test/e2e/test_cluster_configs/windows/sac/sac-1903.json
  test/e2e/test_cluster_configs/windows/sac/sac-1909.json
Labels: lgtm, size/L

#3423 chore: update aad-pod-identity manifest and version
  parts/k8s/addons/aad-pod-identity.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: size/L

#3424 chore: bump csi-secrets-store image versions
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3419 chore: standardize nodeSelector declarations in addons
  parts/k8s/addons/kubernetes-dashboard.yaml
  parts/k8s/addons/metrics-server.yaml
  parts/k8s/addons/nvidia-device-plugin.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3422 fix: disable apiserver insecure-port
  docs/topics/clusterdefinitions.md
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  pkg/api/defaults-apiserver.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
Labels: approved, lgtm, size/M

#3428 docs: remove references to "whitelist"
  docs/topics/upgrade.md
  examples/cosmos-etcd/readme.md
  pkg/api/common/versions.go
  test/e2e/config/config.go
Labels: approved, area/docs, lgtm, size/S

#3426 fix: FlexVolume broken issue on Windows
  parts/k8s/kubeletstart.ps1
  pkg/engine/templates_generated.go
Labels: lgtm, size/S, windows

#3430 feat: enable configurable apiserver --anonymous-auth
  docs/topics/clusterdefinitions.md
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/M

#3427 feat: add UltraSSD support port to aks-release-v0.47.0-1
  docs/topics/clusterdefinitions.md
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
Labels: aks, size/M

#3431 fix: Fix cleanup container image
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: size/XS

#3432 fix: FlexVolume broken issue on Windows
  parts/k8s/kubeletstart.ps1
  pkg/engine/templates_generated.go
Labels: size/S

#3433 fix: Use mirror in China for AzureChinaCloud
  pkg/api/azenvtypes.go
  pkg/api/azenvtypes_test.go
Labels: lgtm, size/M

#3444 test: generic async top nodes interface for E2E
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, size/M

#3380 feat: flatcar nodes
  cmd/generate_test.go
  docs/topics/clusterdefinitions.md
  docs/topics/features.md
  examples/e2e-tests/kubernetes/flatcar/flatcar.json
  examples/flatcar/kubernetes-flatcar-hybrid.json
  examples/flatcar/kubernetes-flatcar.json
  parts/k8s/addons/blobfuse-flexvolume.yaml
  parts/k8s/addons/keyvault-flexvolume.yaml
  parts/k8s/addons/smb-flexvolume.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_helpers.sh
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/support_validator.go
  pkg/engine/engine_test.go
  pkg/engine/template_generator.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/vmextensions.go
  test/e2e/kubernetes/scripts/time-sync-validate.sh
  test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
  test/e2e/test_cluster_configs/flatcar/OWNERS
  test/e2e/test_cluster_configs/flatcar/flatcar.json
Labels: approved, size/XL

#3451 fix: add retry for the image clean up.
  parts/k8s/cloud-init/artifacts/cse_install.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: lgtm, size/M

#3452 fix: Updating Azure NPM to v1.1.4
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3455 test: test Azure NetworkPolicy against all Kubernetes versions
  test/e2e/test_cluster_configs/network_policy/azure.json
Labels: size/XS

#3415 feat: Dualstack support for Windows containers
  parts/k8s/kubeletstart.ps1
  parts/k8s/kubeproxystart.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowsnodereset.ps1
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/L, windows

#3459 export the missing functions.
  parts/k8s/cloud-init/artifacts/cse_install.sh
Labels: size/XS

#3460 fix: forgot to do the templates generation.
  pkg/engine/templates_generated.go
Labels: size/XS

#3434 chore: Add EnableAHUB in WindowsProfile (#3322)
  docs/topics/clusterdefinitions.md
  docs/topics/windows-and-kubernetes.md
  examples/windows/kubernetes-wincni.json
  examples/windows/kubernetes-windows-1903.json
  parts/k8s/kuberneteswindowsfunctions.ps1
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/engine/templates_generated.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
  test/e2e/test_cluster_configs/windows/vhd_ahub.json
Labels: aks, size/L

#3454 fix: make security context configs more restrictive
  docs/topics/sgx/device-plugin-before-k8s-1-17.yaml
  docs/topics/sgx/device-plugin.yaml
Labels: approved, lgtm, size/S

#3461 chore: update pause image to 1.3.2
  parts/k8s/kuberneteswindowsfunctions.ps1
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/k8s_versions.go
  pkg/api/types_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3457 docs: supported versions for Azure Stacks using VHD 2020.05.13
  docs/topics/azure-stack.md
  examples/azure-stack/kubernetes-azurestack.json
  examples/azure-stack/kubernetes-windows.json
Labels: area/docs, azurestack, size/S

#3464 test: don't perform stability tests on long-running cluster configs
  test/e2e/cluster.sh
  test/e2e/test_cluster_configs/availabilityset.json
  test/e2e/test_cluster_configs/base.json
Labels: approved, size/S

#3469 chore: Add June Patches
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200610.txt
Labels: size/L

#3472 feat: use 2020.06.10 VHD for AKS
  pkg/api/azenvtypes.go
Labels: size/S

#3468 chore: Add June Windows Patches
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200610.txt
Labels: VHD, approved, lgtm, size/L, windows

#3467 chore: rev azure-sdk-for-go to v43.0.0
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
  vendor/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2017-03-01/apimanagement/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-03-30/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/users.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2018-02-14/keyvault/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2018-02-14/keyvault/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2017-10-01/network/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-08-01/network/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-01-01-preview/authorization/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/authorization/mgmt/2018-09-01-preview/authorization/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-06-01/subscriptions/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2017-10-01/storage/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2018-02-01/storage/version.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3463 chore: update metrics-server to v0.3.6
  pkg/api/k8s_versions.go
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3471 feat: add support for Kubernetes v1.19.0-beta.2
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3448 chore: add csi windows related images
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, lgtm, size/XS, windows

#3475 test: assign default stability iterations in cluster.sh
  test/e2e/cluster.sh
Labels: size/XS

#3447 fix: Do not mutate OrchestratorVersion when set default
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: aks, size/M

#3466 feat: enable windows daemonset in container monitoring addon
  docs/tutorials/containermonitoringaddon.md
  parts/k8s/addons/container-monitoring.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
  pkg/engine/testdata/key-vault-certs/kubernetes.json
  test/e2e/test_cluster_configs/container_monitoring.json
Labels: approved, lgtm, size/L

#3479 docs: minor description change in Azure Stack documentation
  docs/topics/azure-stack.md
Labels: approved, lgtm, size/XS

#3482 test: basic pods Running E2E tests for all addons
  pkg/api/addons_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/L

#3483 test: use full toleration for testing scheduling to control plane
  test/e2e/kubernetes/workloads/busybox-master.yaml
Labels: approved, size/XS

#3474 chore: triage "k8s-master" references for eventual removal
  cmd/get_logs.go
  cmd/rotate_certs_test.go
  pkg/api/common/const.go
  pkg/api/types_test.go
  pkg/armhelpers/mockclients.go
  pkg/engine/armvariables_test.go
  pkg/operations/k8sapi_ops_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, lgtm, size/M

#3486 test: retry pod scheduling attempts
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/M

#3485 chore: Support to change LicenseType for Windows
  docs/topics/clusterdefinitions.md
  pkg/api/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: approved, lgtm, size/M

#3487 test: use regular timeout for functional DNS test
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, size/XS

#3488 feat: ensure all AKS required ports on api-server are exposed
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/S

#3490 fix: scale + AvailabilitySet errata
  cmd/scale.go
Labels: approved, size/M

#3481 fix: addons bootstrapping errata
  examples/e2e-tests/kubernetes/release/default/definition.json
  parts/k8s/addons/azure-policy-deployment.yaml
  parts/k8s/addons/kubernetes-dashboard.yaml
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
Labels: approved, size/L

#3492 chore: Support to change LicenseType for Windows (#3485)
  docs/topics/clusterdefinitions.md
  pkg/api/types.go
  pkg/engine/virtualmachines.go
  pkg/engine/virtualmachines_test.go
  pkg/engine/virtualmachinescalesets.go
  pkg/engine/virtualmachinescalesets_test.go
Labels: size/M

#3498 test: skip stability tests for "everything" E2E cluster config
  test/e2e/test_cluster_configs/everything.json
Labels: approved, size/XS

#3493 feat: enable configurable usageReportingEnabled in calico addon
  parts/k8s/addons/calico.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/network_policy/calico.json
  test/e2e/test_cluster_configs/network_policy/calico_azure.json
Labels: approved, size/M

#3496 feat: add support for Kubernetes 1.16.11
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3499 feat: add support for Kubernetes 1.17.7
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#3500 feat: add support for Kubernetes 1.18.4
  pkg/api/common/versions.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/M

#3504 fix: change string comparison way to remove case-sensitive for customer input.
  pkg/api/types.go
Labels: aks, size/L

#3509 chore: add support for K8s v1.17.7 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/XS

#3506 chore: add 1.16.11, 1.17.7, 1.18.4 hotfix packages to Windows VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3512 feat: Use VHD 2020.06.18
  pkg/api/azenvtypes.go
Labels: size/S

#3510 fix: use hotfix Windows builds for 1.18.4, 1.17.7, and 1.16.11
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S

#3513 fix: Make sure nvidia utility and compute bins can be mounted into container
  parts/k8s/cloud-init/artifacts/cse_config.sh
  pkg/engine/templates_generated.go
Labels: size/XS

#3511 test: pointing Windows containerd binaries to nightly builds for e2e …
  test/e2e/test_cluster_configs/containerd.json
Labels: approved, lgtm, size/XS

#3516 chore: Updates the pause image to 1.4.0
  cmd/generate_test.go
  docs/howto/mixed-cluster-ingress.md
  docs/topics/windows-and-kubernetes.md
  examples/windows/kubernetes-windows-automatic-update.json
  examples/windows/kubernetes-windows-version.json
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/k8s_versions.go
  pkg/api/types_test.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/workloads/iis-azurefile.yaml
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/L, windows

#3515 [WIP] chore: increase default cloud provider's rate limits on Azure Stack
  examples/azure-stack/kubernetes-azurestack.json
  examples/azure-stack/kubernetes-windows.json
  pkg/api/const.go
Labels: approved, do-not-merge/work-in-progress, lgtm, size/S

#3523 fix: ensure cron systemd job restarts
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, size/S

#3524 fix: add validation for enableVMSSNodePublicIP + Basic LB
  docs/topics/clusterdefinitions.md
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, size/S

#3527 chore: rev Linux VHDs to 2020.06.22
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.22.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.22.txt
Labels: approved, size/L

#3528 fix: add windows hotfix overrides for 1.18.2, 1.16.10, 1.15.12 for AKS
  pkg/api/k8s_versions.go
Labels: approved, lgtm, size/S, windows

#3526 chore: improve vmss validation now that vmss is default
  pkg/api/vlabs/validate.go
Labels: approved, size/XS

#3404 chore: bump moby to 3.0.13
  parts/k8s/kubernetesparams.t
  pkg/api/const.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: lgtm, size/S

#3530 feat: enable alternate kube-reserved cgroups
  docs/topics/clusterdefinitions.md
  examples/kubernetes-config/kubernetes-kube-reserved.json
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/masternodecustomdata.yml
  parts/k8s/cloud-init/nodecustomdata.yml
  pkg/api/converterfromapi.go
  pkg/api/converterfromapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/engine/template_generator.go
  pkg/engine/template_generator_test.go
  pkg/engine/templates_generated.go
  test/e2e/test_cluster_configs/everything.json
Labels: lgtm, size/L

#3525 chore: Adding 1.15.12, 1.16.10, 1.18.2 hotfix packages for windows to VHD
  vhd/packer/configure-windows-vhd.ps1
Labels: VHD, approved, lgtm, size/XS, windows

#3535 chore: add support for K8s v1.16.11 on Azure Stack
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/XS

#3537 chore: get-logs collects audit logs
  scripts/collect-logs.sh
Labels: lgtm, size/XS

#3534 docs: add Azure API throttling doc
  docs/howto/troubleshooting.md
  docs/topics/azure-api-throttling.md
Labels: approved, size/L

#3532 fix: use kube-proxy image instead of hyperkube for 1.16
  parts/k8s/addons/kube-proxy.yaml
  pkg/api/addons.go
  pkg/api/addons_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/engine/templates_generated.go
  vhd/packer/install-dependencies.sh
Labels: approved, do-not-merge/hold, lgtm, size/M

#3539 fix: updating hotfix packages used for windows to include hyperkube a…
  pkg/api/k8s_versions.go
  vhd/packer/configure-windows-vhd.ps1
Labels: approved, size/S, windows

#3536 fix: always use /var/run/reboot-required
  parts/k8s/cloud-init/artifacts/cse_config.sh
  parts/k8s/cloud-init/artifacts/cse_main.sh
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#3540 fix: downgrade blobfuse to 1.1.1 since there is breaking change on 1.2.3
  parts/k8s/cloud-init/artifacts/cse_install.sh
  pkg/engine/templates_generated.go
Labels: lgtm, size/XS

#3544 fix: remove K8s v1.17 support on Azure Stack
  docs/topics/azure-stack.md
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3547 feat: Add support for 1.15.12/1.16.10/1.17.7/1.18.4
  pkg/api/common/versions.go
Labels: size/XS

#3548 test: fix UT
  pkg/api/vlabs/validate_test.go
Labels: approved, size/XS

#3545 docs: update throttling doc
  docs/topics/azure-api-throttling.md
Labels: approved, size/L

#3538 test: enable CustomKubeProxyImage override
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/cluster.sh
  test/e2e/engine/template.go
Labels: approved, size/M

#3550 chore: updating windows VHD used by aks-engine to include June k8s pa…
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200625.txt
Labels: VHD, approved, lgtm, size/L, windows

#3555 feat: use AKS VHD 2020.06.25
  pkg/api/azenvtypes.go
  pkg/api/common/versions.go
Labels: size/S

#3554 chore: updating windows VHD used by aks-engine to include June k8s packages
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/api/azenvtypes.go
  pkg/api/k8s_versions.go
  pkg/engine/templates_generated.go
  vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200625.txt
Labels: lgtm, size/L, windows

#3558 chore: rev Linux VHDs to 2020.06.25
  pkg/api/azenvtypes.go
  vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.25.txt
  vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.25.txt
Labels: approved, lgtm, size/L

#3562 fix: change addons image pull policy to IfNotPresent
  parts/k8s/addons/aci-connector.yaml
  parts/k8s/addons/azure-policy-deployment.yaml
  parts/k8s/addons/cilium.yaml
  parts/k8s/addons/container-monitoring.yaml
  parts/k8s/addons/kubernetes-dashboard.yaml
  parts/k8s/addons/secrets-store-csi-driver.yaml
  parts/k8s/addons/smb-flexvolume.yaml
  pkg/engine/templates_generated.go
Labels: approved, lgtm, size/M

#3553 feat: add support for Kubernetes v1.18.5
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, lgtm, size/S

#3552 feat: add support for Kubernetes v1.17.8
  pkg/api/common/versions.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/XS

#3551 feat: add support for Kubernetes v1.16.12
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  vhd/packer/configure-windows-vhd.ps1
  vhd/packer/install-dependencies.sh
Labels: approved, size/S

#3564 test: enable daemonset E2E test conveniences
  test/e2e/kubernetes/daemonset/daemonset.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, size/L
