Repository Azure/aks-engine, pull requests merged in 2021-05, with the labels that each got.

#4422 fix: distinguish ctrd and smalldisk windows image in upgrade scenario
  cmd/upgrade.go
Labels: windows

#4413 ci: workaround image publishing errors
  vhd/publishing/new-sku-and-add-image-version.sh
Labels: aks, windows

#4325 feat: enable working, validated exec livenessProbes
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/dns-liveness.yaml
  test/e2e/kubernetes/workloads/exec-liveness-always-fail.yaml
  test/e2e/kubernetes/workloads/exec-liveness-assume-1-second-default-timeout.yaml
  test/e2e/kubernetes/workloads/exec-liveness-timeout-always-fail.yaml
  test/e2e/kubernetes/workloads/exec-liveness.yaml
Labels: do-not-merge/hold
